### ISSUE TITLE
reaper-operator role.yaml has roles it shouldn't have and they can cause conflicts.

### ISSUE THREAD

**Issue by uwburn** [k8ssandra/k8ssandra#1012]
## Bug Report
**Describe the bug**
Installation of multiple releases fails due to leader-election-role already existing. Look like leader-election-role is missing the release name as a prefix

**To Reproduce**

1. helm install -f k8ssandra.yaml k8ssandra_1 k8ssandra/k8ssandra
1. helm install -f k8ssandra.yaml k8ssandra_2 k8ssandra/k8ssandra
1. See error

Where k8ssandra.yaml is a valid values override file, just like in the online documentation.

**Expected behavior**
Two releases should be able to co-exist.

**Environment (please complete the following information):**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
minikube

**Additional context**
I'm pretty new to k8s, helm and k8ssandra, but i'm trying to use k8ssandra as a dependency of an application i'm migrating to k8s and ran into this issue when testing multiple releases.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-780) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-780
┆Priority: Medium

**Comment by burmanm** [comment]
I don't think we support multiple releases per namespace at this point, but multiple installation per Kubernetes cluster should work.

**Comment by uwburn** [comment]
Understood, it was somewhat strange as other roles were prefixed, while that one was not and ended up conflicting.

**Comment by burmanm** [comment]
It's probably not the only problem that it would run to, given that two cass-operators should not exist in the same namespace (but preventing that becomes nightmare in Helm) or one should be disabled so that they both won't try to reconcile the same datacenter.

**Comment by burmanm** [comment]
Or was this reaper operator issue, let me check.

**Comment by burmanm** [comment]
It appears in commit https://github.com/k8ssandra/k8ssandra/commit/5c2e0f0bbcb3a3910d4dfe4777cf6bb06dd4443a there was duplicate leader-role appended to the role.yaml. That should not be here, since the real leader role account is prefixed.

**Comment by burmanm** [comment]
Thanks for the report, I've pushed a PR to fix this role naming issue in the next release.

**Comment by uwburn** [comment]
> It's probably not the only problem that it would run to, given that two cass-operators should not exist in the same namespace (but preventing that becomes nightmare in Helm) or one should be disabled so that they both won't try to reconcile the same datacenter.

Good to know! Anyway it was just something i'm going to experience while testing things up, not really a problem switching namespace.

Thanks for great support!
