### ISSUE TITLE
K8SSAND-793 ⁃ Ability to update cassandra.yaml in k8ssandra

### ISSUE THREAD

**Issue by madireddyr** [k8ssandra/k8ssandra#1023]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-793) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆epic: Advanced Component Configuration
┆fixVersions: k8ssandra-1.4.0
┆friendlyId: K8SSAND-793
┆priority: Medium

**Comment by jsanda** [comment]
Hey @madireddyr 

Can you provide some more details for what exactly you want? K8ssandra does already provide the ability to generate an updated cassandra.yaml for the C* properties that it exposes. It does not however expose all C* settings.

**Comment by madireddyr** [comment]
@jsanda  : we would like to configure below params , 



authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
hints_directory
data_file_directories
commitlog_directory
row_cache_size_in_mb
saved_caches_directory
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32
file_cache_size_in_mb: 2048
disk_optimization_strategy: ssd
memtable_allocation_type
memtable_flush_writers: 4
auto_snapshot: true
concurrent_compactors
slow_query_log_timeout_in_ms

**Comment by jsanda** [comment]
While k8ssandra does not directly expose `authenticator` and `authorizer` it does make auth configurable. It also makes the auth-related caches configurable. See https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L66 and https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L91.

For `hint_directory`, data_file_directories`, `commitlog_directory`, and `saved_caches_directory` do you want to be able to specify volumes and mount points? 

For reference I created #351 a while back to make the commit log configurable.

For `disk_optimization_strategy` do you think we need to take the storage class used into consideration?

It should be pretty straightforward to make the rest configurable. I do want to point out that we are working on an operator for k8ssandra (https://github.com/k8ssandra/k8ssandra-operator). For settings like `concurrent_reads` and `concurrent_writes` where the recommended settings are based on the number of cores, the operator could by default calculate that setting based on the cpu resources assigned to the Cassandra pods.

Once we get this flushed out a bit more, I would like to break this up into multiple tickets.

**Comment by madireddyr** [comment]
@jsanda : Yes hint_directory , data_file_directories , commitlog_directory we want to mount to different volumes , for performance reasons  .
Yes disk_optimization_strategy : should be based on type of storage and configurable
While we await  k8ssandra-operator , what are the options to configure concurrent_reads and concurrent_writes etc

**Comment by jdonenine** [comment]
@Miles-Garnsey take a peek at the discussion going on here, as you get into the configuration stuff this might give some more context for other pieces we could expose.
