### ISSUE TITLE
K8SSAND-804 ⁃ Make rack name for Stargate configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1028]
**Is your feature request related to a problem? Please describe.**
The rack for Stargate is configured via the `RACK_NAME` env var. It is hard coded to `default`.

**Describe the solution you'd like**
As a short term solution I would like the `RACK_NAME` env var to be configurable. 

This is a complete solution for a couple reasons. First, If the Cassandra cluster utilizes multiple racks, this won't allow you to specify Stargate instances for each rack. Secondly, cass-operator uses rack to create node affinity. We probably want to do the same for Stargate. These will be addressed in k8ssandra-operator. See https://github.com/k8ssandra/k8ssandra-operator/issues/17 and https://github.com/k8ssandra/k8ssandra-operator/pull/85.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-804) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-804
┆priority: Medium

**Comment by bradfordcp** [comment]
With k8ssandra-operator do we set the rack name and spread pods across AZs @jsanda ? If so I'm inclined to close this ticket.
