### ISSUE TITLE
Upgrading from Cassandra 3.11 to 4.0 fails if num_tokens is not set

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1029]
## Bug Report

**Describe the bug**
The default value for `num_tokens` in 3.11 is 256. The default in 4.0 is 16. We have a helper template that sets the default based on the Cassandra version. In k8ssandra 1.3.0 we made the default Cassandra version 4.0. Cassandra does not allow you to change the value of `num_tokens` in an existing datacenter.

**To Reproduce**

1. Install k8ssandra 1.2.0 using default values.
1. Upgrade to 1.3.0
1. The following exception will be reported in Cassandra's logs:

```
ERROR [main] 2021-08-16 21:56:18,179 CassandraDaemon.java:909 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot change the number of tokens from 256 to 16
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1068)
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1017)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:799)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:729)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:420)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:763)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:887)
```

It causes Cassandra to fail startup.

**Expected behavior**
`num_tokens` should not be changed when upgrading, regardless of Cassandra version.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
1.3.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-805) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-805
┆Priority: Medium

**Comment by johnsmartco** [comment]
Thanks John. Workaround for 1.3.0 Release Notes?  Or would the user need to uninstall, and install K8ssandra again starting with cassandra.version: “4.0.0”, new DC, and desired num_tokens configured as well? (Assuming downtime to uninstall / install is acceptable)

**Comment by jsanda** [comment]
I just opened #1031 with a fix. 

A work around for 1.3.0 would be to explicitly set `num_tokens` even if the default is used. For 3.11.x, the default is 256. For 4.0 the default has changed to 16.

The user should not have to reinstall k8ssandra. If the user is on 3.11.x and wants to upgrade to 4.0 and also switch to 16 for `num_tokens` then user needs to follow the proper procedure for doing that which is a datacenter migration.

**Comment by jsanda** [comment]
@jdonenine we might want to consider releasing a 1.3.1 for this.
