### ISSUE TITLE
Upgrade cass-operator to 1.8.0-rc.1

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1074]
We want to get cass-operator 1.8.0 released and make that the default version in the next release of k8ssandra. We should upgrade to rc-1 now to help get cass-operator ready for release.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-845) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-845
┆Priority: Medium

**Comment by burmanm** [comment]
Fixed by #1119
