### ISSUE TITLE
Make 4.0.0 the default deployment on main

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1077]
**Is your feature request related to a problem? Please describe.**
Because of the pending test failures the work to make 4.0.0 the default deployment was never merged to main, it should now be possible with the test issues addressed.

**Describe the solution you'd like**
Merge content from https://github.com/k8ssandra/k8ssandra/pull/1014 which was originally reverted.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-850) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-850
┆Priority: Medium

**Comment by jsanda** [comment]
4.0.0 is the default. See [here](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L11).

**Comment by adejanovski** [comment]
Closing the issue then. Thanks @jsanda
