### ISSUE TITLE
K8SSAND-873 ⁃ ClusterName in cass-operator services should be cleaned to match DNS requirements

### ISSUE THREAD

**Issue by reddeppas** [k8ssandra/k8ssandra#1090]
**Type of question**

How to perform a Cassandra migration from existing DC to K8ssandra. Our existing cluster names are Camel Case 
and the Cass-operator fails with the below Kubernetes validation. It's trying to create a headless service with labeling from cluster name. is there any way I can override this value?

controller-runtime.controller","msg":"Reconciler error","controller":"cassandradatacenter-controller","request":"k8ssandra/dc2","error":"Service \"MrDvrCassandraTv3t-dc2-service\" is invalid: metadata.name: Invalid value: \"REDACTED\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","stacktrace":"github.com/go-logr/zapr.(_zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(_Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(

**What did you do?**
Deployed k8ssandra using k8ssandra helm charts. 

**Did you expect to see some different?**
Expected handled this cass-operator. Creating a new cluster I don't see any issue. If I add seed nodes and try to create a cluster with Camel Casefails. 
**Environment**
Kubernetes 1.19.11 and AKS cluster

* Helm charts version
K8ssandra version is 1.3.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-873) by [Unito](https://www.unito.io)
┆Reviewer: 5e66c4695df5fb0cfee2e364
┆fixVersions: cass-operator-1.8.0
┆friendlyId: K8SSAND-873
┆priority: Medium

**Comment by burmanm** [comment]
At the moment there's no way to override the naming of the service, it takes ``dc.Spec.ClusterName`` as the first parameter in the service name.

**Comment by reddeppas** [comment]
@burmanm Thanks for the response. All our cluster's names are camelcase. I don't think adding seed nodes to k8ssandra will work in this case. Is there any better approach to migrate data from the Cassandra cluster running on VMs to the k8ssandra cluster?

**Comment by burmanm** [comment]
I wasn't referring to adding seed nodes, I changed the topic to fix the creation of services to allow using clusterNames which do not match the Kubernetes requirements. That would simplify the migration to k8ssandra.

**Comment by reddeppas** [comment]
@burmanm Thanks for the update. Is there a timeline for when this fix will be delivered?

**Comment by burmanm** [comment]
It's targeted for 1.8.0, so this or next week (if we find something buggy).

**Comment by burmanm** [comment]
@reddeppas 1.8.0 is now merged to k8ssandra, so a newest --devel install should work for your cluster.

**Comment by reddeppas** [comment]
Thanks a lot for quicker resolution @burmanm

**Comment by reddeppas** [comment]
@burmanm Do I need to use devel helm chart for testing this?

**Comment by burmanm** [comment]
Yes, but I need to push the newer image to k8ssandra first.

**Comment by reddeppas** [comment]
@burmanm Sure. please let me know once it is done I can test it.

**Comment by reddeppas** [comment]
@burmanm Can you please confirm if the newer image was pushed to k8ssandra? Thanks

**Comment by jsanda** [comment]
@reddeppas cass-operator 1.9.0 was released yesterday so the changes are available.

**Comment by burmanm** [comment]
@reddeppas Sorry, this should be available in the stable version now (k8ssandra 1.4.0).

**Comment by reddeppas** [comment]
@burmanm Thanks.. Will test it and let you know

**Comment by reddeppas** [comment]
@burmanm  Do I need to create secrets manually or does it take the release name as the default secret name?

**Comment by reddeppas** [comment]
Thanks @burmanm I was able to install the helm chart after manually creating secrets for superuser,reaper,medusa and jmx-reaper .  these secret names are still appending cluster name
