### ISSUE TITLE
Cassandra won't start when deployed on GKE with 1.4.0-SNAPSHOT 

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1094]
## Bug Report

**Describe the bug**
Cassandra fails to start with the current `main` as the process cannot create directories for data nor commit logs when deploying on GKE:

```
ERROR [main] 2021-09-09 16:21:28,902 CassandraDaemon.java:909 - Exception encountered during startup
java.lang.ExceptionInInitializerError: null
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:260)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:763)
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:887)
Caused by: java.lang.IllegalStateException: Failed to mkdirs /opt/cassandra/data/data; unable to start server
    at org.apache.cassandra.config.DatabaseDescriptor.createAllDirectories(DatabaseDescriptor.java:1422)
    at org.apache.cassandra.db.commitlog.CommitLog.<init>(CommitLog.java:94)
    at org.apache.cassandra.db.commitlog.CommitLog.construct(CommitLog.java:77)
    at org.apache.cassandra.db.commitlog.CommitLog.<clinit>(CommitLog.java:64)
    ... 3 common frames omitted
```

Looking at the directories and symlinks, it looks like `/var/lib/cassandra` isn't mounted so that the `cassandra`  user can write to it:

![Capture d’écran 2021-09-09 à 18 42 48](https://user-images.githubusercontent.com/5096002/132730197-29110aeb-08a5-44cd-b5ef-5c09f303e471.png)
![Capture d’écran 2021-09-09 à 18 43 44](https://user-images.githubusercontent.com/5096002/132730209-4a8a4135-effb-49ed-b3df-d12acee80e9e.png)

**To Reproduce**
Deploy K8ssandra 1.4.0-SNAPSHOT on GKE using the following Helm values file:

```
cassandra:
  version: "4.0.0"
  heap:
   size: 4g
  gc:
    g1:
      enabled: true
      setUpdatingPauseTimePercent: 5
      maxGcPauseMillis: 300
  resources:
    requests:
      memory: "8Gi"
      cpu: "2000m"

  datacenters:
  - name: dc1
    size: 3
  ingress:
    enabled: false

  cassandraLibDirVolume:
    storageClass: standard-rwo
    size: 300Gi
```

**Expected behavior**
Cassandra should start and data volumes should mount so that required directories can be created by the `cassandra` user.
In K8ssandra 1.3.1, the rights for the `/var/lib/cassandra` are set differently, allowing Cassandra to start properly:
![Capture d’écran 2021-09-09 à 19 03 32](https://user-images.githubusercontent.com/5096002/132730683-190727ee-67a5-401f-b4db-0a33427e0de7.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-875) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-875
┆Priority: Medium

**Comment by jsanda** [comment]
@jeffbanks could this be related to the recent security related work?

**Comment by jeffbanks** [comment]
@jsanda I will take a look to see what is going on, most likely permission due to recent restrictions.
