### ISSUE TITLE
Upgrading from versions 0.12.0 and earlier of the k8ssandra and k8ssandra-cluster charts fails

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#110]
## Bug Report

**Describe the bug**

**To Reproduce**

1. Make sure you have the latest charts:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "datastax" chart repository
...Successfully got an update from the "k8ssandra" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

$ helm search repo k8ssandra
NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
k8ssandra/k8ssandra        	0.14.0       	3.11.7     	Configures and provisions the full k8ssandra stack
k8ssandra/k8ssandra-cluster	0.14.0       	3.11.7     	Configures and creates a k8ssandra cluster
k8ssandra/backup           	0.14.0       	0.1.0      	Creates a CassandraBackup
k8ssandra/restore          	0.14.0       	0.1.0      	Creates a CassandraRestore
```

1. `helm install k8ssandra k8ssandra/k8ssandra --version 0.12.0`
1. `helm install upgrade-test k8ssandra/k8ssandra-cluster --version 0.12.0`
1. `helm upgrade k8ssandra k8ssandra/k8ssandra`
1. Upgrading `upgrade-test` fails:

```
$ helm upgrade upgrade-test k8ssandra/k8ssandra-cluster
Error: UPGRADE FAILED: cannot patch "upgrade-test-reaper-k8ssandra" with kind Reaper: Reaper.reaper.cassandra-reaper.io "upgrade-test-reaper-k8ssandra" is invalid: [spec.serverConfig.cassandraBackend.cassandraService: Required value, spec.serverConfig.cassandraBackend.clusterName: Required value]
```

**Expected behavior**
`helm upgrade` should work without error.

* Kubernetes version information:
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.600", GitCommit:"3415f17fc893455f55dd732b92b7036a59609135", GitTreeState:"clean", BuildDate:"2020-10-20T23:58:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**
Reaper CRD changes were made for #45 which were introduced in version 0.13.0 or 0.14.0 of the charts. The errr above says that the `spec.serverConfig.cassandraBackend.clusterName` field is required; however, it was removed from the CRD. 

The real problem is that Helm does not add/update CRDs with `helm upgrade`. See this [ticket](https://github.com/helm/helm/issues/6581) for details.

We need to implement a [hook](https://helm.sh/docs/topics/charts_hooks/) to ensure any CRD changes are applied.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-76) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
John talked to me about this one and we believe we can push this to post-1.0.0.  I'm going to bump down in priority from my original.

**Comment by burmanm** [comment]
I transferred this from P3 bucket to Todo only, I think this is only going to be applicable post-1.0.0 in any case, due to the merging of the charts. Updating is going to be next to impossible from pre-merge to post-merge in any case. And as such, we can see if we break something post 1.0.0 and then continue with the ticket (the code itself should be quite ready).

**Comment by jsanda** [comment]
Agreed about it only being relevant post-1.0.0.
