### ISSUE TITLE
K8SSAND-919 ⁃ There needs to be an integration test for a default installation

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1110]
I was reviewing/testing #950 and the local install failed because the management-api image couldn't be found. The default image in the PR had been changed to `k8ssandra/cass-management-api:4.0.1-v0.1.29` which is incorrect. Looks like it should be `k8ssandra/cass-mgmtapi:4.0.1-v0.1.29`. What's interesting though is that all of the tests in GHA pass. 

We need an integration test that that performs a default installation without overriding any chart properties. Such a test would have caught this and potentially other similar issues where we always override various chart properties.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-919) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-919
┆priority: Medium

**Comment by burmanm** [comment]
Is there a bug in docker hub files then? It should be: ``k8ssandra/cass-management-api:version``

**Comment by jsanda** [comment]
There is no 4.0.1 `cass-management-api` image. @emerkle826 can you chime here?

**Comment by emerkle826** [comment]
Yes, sorry about that. I had to manually push the 4.0.0 and 4.0.1 images and I screwed up. When I tagged Management API v0.1.29, it built a 4.0.1 image but pushed it as 4.0.0, and didn't build/push a true 4.0.0 image. I built the 2 locally and pushed, but pushed with the wrong tags. It's been corrected in the Management API repo, but I'll fix the images here shortly.

**Comment by emerkle826** [comment]
I've re-tagged Management API v0.1.29 and all the images should now be in the correct locations in DockerHub.

**Comment by adejanovski** [comment]
@jsanda, do we still want to do this or should we close it as "won't do"?

**Comment by jsanda** [comment]
We can close it.
