### ISSUE TITLE
K8SSAND-921 ⁃ Restore operation is rerun when Cassandra pods are restarted

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1112]
## Bug Report
**Describe the bug**
Install k8ssandra with backup/restored enabled. Perform a backup followed by a restore. After the restore completes, delete a Cassandra pod. When the pod is restarted the `medusa-restore` init container perform the restore operation again. It shouldn't though. 

The regression was introduced in Medusa 0.10.1 in this commit [https://github.com/thelastpickle/cassandra-medusa/commit/d1756f2879f6968ffe130c359861d1a35fa2481a](https://github.com/thelastpickle/cassandra-medusa/commit/d1756f2879f6968ffe130c359861d1a35fa2481a).

The `BACKUP_NAME` and `RESTORE_KEY` env vars have to be set in the `medusa-restore` init container in order for a restore to be performed. This is done by medusa-operator `BACKUP_NAME` specifies the backup to restore. `RESTORE_KEY` is written out to a file after the restore completes. We compare the value in the file to `RESTORE_KEY`. We perform a restore if the file does not exist or if the values differ.

The restore python script is invoked with `exec`:

```java
exec python3 -m medusa.service.grpc.restore
```

With `exec` no subshell is created so the container exits after the python script returns. The file that stores the restore key is created after calling the python script. This means that the `/var/lib/cassandra/.last-restore` file is never created

**To Reproduce**

1. Install k8ssandra with backup/restore enabled. Any storage backend can be used.
1. Perform a backup and wait for it to complete
1. Restore the backup and wait for it to complete
1. Run `kubectl exec -it <cassandra-pod> -c cassandra -- ls -a /var/lib/cassandra` to verify that the file was not created. Note that it is ok to run the command against the cassandra container as the file is written to a shared volume.
1. Delete the Cassandra pod
1. Check the logs of the `medusa-restore` init container and you see that it performs the restore operation again

**Expected behavior**
`/var/lib/cassandra/.last-restore` should be created after the initial restore and no restore operation should be performed if the Cassandra pod is deleted and recreated. 

As part of the solution I would like to see a test to cover this scenario. The test should scrape the logs of `medusa-restore` to verify whether the restore is performed both before and after the pod is deleted.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
k8ssandra 1.2.0, 1.3.0, 1.3.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-921) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-921
┆Priority: Medium

**Comment by networkingana** [comment]
Should i remove the MedusaRestoreJobs after restore is finished, I had the same issue for restoring backup after whole cluster restart, resulting in losing production data. I use k8ssandra-operator chart 1.7.1, i can see the file .last_restore created, i can see the uid in the .restore_mappings as well, the environment variables BACKUP_NAME and RESTORE_KEY are set after restart and the uid is same in the .last_restore and RESTORE_KEY, do I do something wrong?
