### ISSUE TITLE
K8SSAND-942 ⁃ The cass-operator chart should install cert-manager when the webhook is enabled

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1117]
Cass Operator 1.8.0 introduces a dependency on Cert Manager for its webhook functionality. The cass-operator chart starting with version 0.31.0 defaults to using Cass Operator 1.8.0 (using release candidate builds since 1.8.0 hasn't been officially released yet). When the webhook is enabled, I expect the cert-manager chart to be installed as well.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-942) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-942
┆priority: Medium

**Comment by bradfordcp** [comment]
Should it install cert-manager or require that it be present?

**Comment by jsanda** [comment]
If the webhook is enabled, then yes cert-manager should be installed by the chart. 

It makes sense to have an option to disable that in case you want to install cert-manager separately.

**Comment by bradfordcp** [comment]
> Prometheus and Ingress are not dependencies of cass-operator. cass-operator runs perfectly fine without them. If the webhook is enabled, cert-manager needs to be installed.

cass-operator runs just fine without cert-manager if the webhook is disabled.

The difference between the relationship with reaper-operator and cert-manager is that one is part of the package we deploy and the other is, most likely, installed and operating at a level above our deployment. Specifically, I see cert-manager (and prometheus, ingress, etc) as being run in a more centralized manner for the cluster providing services for a number of installed services.

You could make the argument that we should be doing the same with all of our operators which is something to evaluate.

**Comment by jsanda** [comment]
>Specifically, I see cert-manager (and prometheus, ingress, etc) as being run in a more centralized manner for the cluster providing services for a number of installed services.

Agreed. That's why I think installing it should be optional. If however we don't install it when the webhook is enabled, the cass-operator install will fail.

**Comment by jsanda** [comment]
There should be a way to disable installing cert-manager when the webhook is enabled precisely to allow using a different cert-manager installation.

**Comment by bradfordcp** [comment]
@jsanda does this ticket still need to be prioritized?

**Comment by jsanda** [comment]
Yeah

**Comment by jsanda** [comment]
Closing  since the cert-manager [docs](https://cert-manager.io/docs/installation/helm/) explicitly say not to do this:

>Be sure never to embed cert-manager as a sub-chart of other Helm charts; cert-manager manages non-namespaced resources in your cluster and care must be taken to ensure that it is installed exactly once.
