### ISSUE TITLE
K8SSAND-959 ⁃ Deployments on k8s v1.22 fail

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1127]
## Bug Report
**Describe the bug**
Deployments on k8s v1.22 fail.

**To Reproduce**

1. Create a kind cluster running node version v1.22.0

```
kind create cluster --image "kindest/node:v1.22.0"
```

1. Attempt to deploy k8ssandra into that cluster

```
helm install k8ssandra k8ssandra/k8ssandra --set cassandra.version=4.0.1 --version 1.4.0-20211004145806-e99b5990 --devel
```

1. Observe the following error:

```
Error: failed to install CRD crds/reaper.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Expected behavior**
Deployments on v1.22 (and older versions as reasonable) should succeed without errors and warnings about API versions.

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T20:01:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
Kind

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-959) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-959
┆Priority: Medium

**Comment by jsanda** [comment]
This has been resolved.
