### ISSUE TITLE
Make cass-operator namespace-scoped by default

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#113]
I want to make this change in conjunction with #59. cass-operator and prometheus-operator are configured with cluster-wide scope. Everything else is namespace-scoped. We want everything (if possible) to be namespace-scoped.

**Comment by burmanm** [comment]
To make things smooth, the https://github.com/datastax/cass-operator/issues/301 needs to be addressed as well before upgrading the cass-operator image.
