### ISSUE TITLE
K8SSAND-1012 ⁃ How to use sstableloader with K8ssandra from a remote machine

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1155]
Hi

I'm running K8ssandra v.3.11.10 and Helm Chart v1.3.1. I have a Cluster with 3 nodes deployed on K8s v.1.19.x provisioned by Rancher. On a remove host, I have a 50G cassandra snapshot. 

Ran manually the keyspace creation on the new cluster, now I'm trying to stream the data from outside. I opened port 9042 on the Ingress Controller so I can connect from outside via tools like TablePlus to the Cassandra instance. 

When trying to use sstableloader it looks like this is not working as it probably ties the internal IPs to send outside the cluster ? 
Maybe I need to open different ports ? 

```
/sstableloader -u k8ssandra-superuser -pw xxxxxxxxx -d cassandra.apps.mydomain.com /tmp/cassandra/data/test/timeserie_int_daily-c01d0a1a5c7535fcab533c91d693c0e0

Established connection to initial hosts
Opening sstables and calculating sections to stream
Streaming relevant part of /tmp/cassandra/data/test/timeserie_int_daily-c01d0a1a5c7535fcab533c91d693c0e0/mc-1-big-Data.db  to [/10.42.1.186, cassandra.apps.mydomain.com/10.4.194.89, /10.42.3.228]
ERROR 14:19:05,713 [Stream #b3628540-38e4-11ec-b7ba-ab6107b349a7] Streaming error occurred on session with peer 10.4.194.89
java.net.ConnectException: Connection refused

WARN  14:21:12,884 [Stream #b3628540-38e4-11ec-b7ba-ab6107b349a7] Stream failed
Streaming to the following hosts failed:
[/10.42.1.186, cassandra.apps.mydomain.com/10.4.194.89, /10.42.3.228]
java.util.concurrent.ExecutionException: org.apache.cassandra.streaming.StreamException: Stream failed
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:98)
        at org.apache.cassandra.tools.BulkLoader.main(BulkLoader.java:48)
Caused by: org.apache.cassandra.streaming.StreamException: Stream failed
        at org.apache.cassandra.streaming.management.StreamEventJMXNotifier.onFailure(StreamEventJMXNotifier.java:88)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
```

I didn't see any examples with sstableloader and K8ssandra really.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1012) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1012
┆priority: Medium

**Comment by jsanda** [comment]
Hey @mikekuzak 

`sstabeloader` uses the storage port which should be 7000.

**Comment by mikekuzak** [comment]
Hi @jsanda 
Thanks for the info. I don't see port 7000 being available in any K8ssandra Service by default. I see only the following ports on k8ssandra-dc1-service> I have checked the other once too.  

<html>
<body>
<label style="box-sizing: inherit; color: rgb(61, 61, 61); display: inline-block; font-family: Prompt, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Port Mapping</label><span style="color: rgb(69, 69, 69); font-family: Prompt, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(242, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span>

Port Name |   | Publish the service port |   | Protocol |   | Target Port |  
-- | -- | -- | -- | -- | -- | -- | --
native |   | 9042 |   | TCP |   | 9042 |  
tls-native |   | 9142 |   | TCP |   | 9142 |  
mgmt-api |   | 8080 |   | TCP |   | 8080 |  
prometheus |   | 9103 |   | TCP |   | 9103 |  
thrift |   | 9160 |   | TCP |   | 9160


</body>
</html>

The k8ssandra pod has this port labeled as 'internode' which is not exposed to outside in any form. 

<html>
<body>
<label style="box-sizing: inherit; color: rgb(61, 61, 61); display: inline-block; font-family: Prompt, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Port Mapping</label><span style="color: rgb(69, 69, 69); font-family: Prompt, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(242, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span>

Port Name | Publish the container port |   | Protocol |   | As a |   | On listening port |  
-- | -- | -- | -- | -- | -- | -- | -- | --
native | 9042 |   | TCP |   | ClusterIP |   | Same as container port |  
tls-native | 9142 |   | TCP |   | ClusterIP |   | Same as container port |  
internode | 7000 |   | TCP |   | ClusterIP |   | Same as container port |  
tls-internode | 7001 |   | TCP |   | ClusterIP |   | Same as container port |  
jmx | 7199 |   | TCP |   | ClusterIP |   | Same as container port |  
mgmt-api-http | 8080 |   | TCP |   | ClusterIP |   | Same as container port |  
prometheus | 9103 |   | TCP |   | ClusterIP |   | Same as container port |  
thrift | 9160 |   | TCP |   | ClusterIP |   | Same as container port


</body>
</html>

**Comment by jsanda** [comment]
Can you try creating another service for the storage port? Configure it with the same selector as the dc service.

**Comment by mikekuzak** [comment]
Did that, so now port 7000 and 9042 are open on the ingress controller. Did check with telnet. 

```
progress: [cassandra.apps.mydomain.com/10.4.194.89]0:1/1 100% total: 100% 0.000KiB/s (avg: 0.000KiB/s)
WARN  09:41:36,817 [Stream #097bb980-3b18-11ec-af97-3d2b986fc1d8] Stream failed
Streaming to the following hosts failed:
[/10.42.1.186,cassandra.apps.mydomain.com/10.4.194.89, /10.42.2.164]
java.util.concurrent.ExecutionException: org.apache.cassandra.streaming.StreamException: Stream failed
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:98)
        at org.apache.cassandra.tools.BulkLoader.main(BulkLoader.java:48)
Caused by: org.apache.cassandra.streaming.StreamException: Stream failed
        at org.apache.cassandra.streaming.management.StreamEventJMXNotifier.onFailure(StreamEventJMXNotifier.java:88)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
        at org.apache.cassandra.streaming.StreamResultFuture.maybeComplete(StreamResultFuture.java:215)
        at org.apache.cassandra.streaming.StreamResultFuture.handleSessionComplete(StreamResultFuture.java:191)
        at org.apache.cassandra.streaming.StreamSession.closeSession(StreamSession.java:481)
        at org.apache.cassandra.streaming.StreamSession.onError(StreamSession.java:571)
        at org.apache.cassandra.streaming.ConnectionHandler$IncomingMessageHandler.run(ConnectionHandler.java:324)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" org.apache.cassandra.tools.BulkLoadException: java.util.concurrent.ExecutionException: org.apache.cassandra.streaming.StreamException: Stream failed
```
This is a 3 node K8s cluster. Do I need to open instead a nodePort and get to each Node directly? Doesn't seem to work through ingress.

**Comment by jsanda** [comment]
The ingress controller you are using might only support HTTP. K8ssandra uses Traefik for non-HTTP traffic. Check out the [docs](https://docs.k8ssandra.io/tasks/connect/ingress/) to learn more about that. 

If you can do a NodePort service, that might be an easier option.

**Comment by mikekuzak** [comment]
I'm running the nginx-ingress-controller and have forwarded the TCP ports:

![image](https://user-images.githubusercontent.com/18675587/139688142-191d3327-c66c-4a5c-886e-ac819ca08383.png)

Somehow I believe this has do to with the fact that the repose comes from internal cluster IP which are not understood outside the cluster.

**Comment by jsanda** [comment]
Let me ask about this part of log you previously reported:

```
Streaming to the following hosts failed:
[/10.42.1.186,cassandra.apps.mydomain.com/10.4.194.89, /10.42.2.164]
```

Are 10.42.1.186 and 10.42.2.164 cluster IPs? 

Is cassandra.apps.mydomain.com the service you have configured with your ingress?

The problem might be that `sstableloader` is resolving the hostname and trying to use the IP. I need to investigate to see if that is the case. If it is, then for now another option could be to use host networking with a nodeport service.

**Comment by mikekuzak** [comment]
yes, these are the internal Cluster IPs. where cassandra.apps.mydomain.com is the external DNS going though a LB and nginx-ingress-controller. 

![image](https://user-images.githubusercontent.com/18675587/139693333-f1f09c9d-6a2b-4828-af9d-2486239414b4.png)

**Comment by jsanda** [comment]
I briefly looked at `BulkLoader.java` which is what the `sstableloader` script calls. It looks like it calls the `init` method of  the `NativeSSTableLoaderClient` class. That method initializes a driver connection as follows:

```java
        Cluster.Builder builder = Cluster.builder().addContactPointsWithPorts(hosts).allowBetaProtocolVersion();

        if (sslOptions != null)
            builder.withSSL(sslOptions);
        if (authProvider != null)
            builder = builder.withAuthProvider(authProvider);

        try (Cluster cluster = builder.build(); Session session = cluster.connect())
        ...
```

I think the driver needs to be configured to use an AddressTranslator. I don't it is possible to do this with `sstableloader` today. We probably need to raise an upstream ticket with the Cassandra project. This of course won't help you right now, so I suggest going to the hostnetworking + nodeport service route.

**Comment by bradfordcp** [comment]
To clear things up here a little bit, the only reason we can utilize an ingress with native protocol traffic is due to the availability of SNI at the driver level.

Given sstableloader is using the storage port instead of native protocol it has no concept of SNI or really any translation of addresses. Closing this ticket for now, but we do recognize the value here and will include this use case in roadmap / feature planning.
