### ISSUE TITLE
K8SSAND-1015 ⁃ When can we expect a new release of the k8ssandra chart with version 1.8 of k8ssandra/cass-operator?

### ISSUE THREAD

**Issue by shurkanTwo** [k8ssandra/k8ssandra#1157]
**Type of question**

Open question

- - -
We would like to install the k8ssandra helm chart, however we just saw that the cass-operator is still on version 1.7.1.

When can we expect a release of the k8ssandra helm chart including version 1.8 of cass-operator (especially because of the included bug fixes)?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1015) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1015
┆Priority: Medium

**Comment by jdonenine** [comment]
Hi @shurkanTwo , very soon.  We're working on wrapping up the remaining open issues that are planned for K8ssandra v1.4, which will be the release that moves to Cass Operator v1.8.

We're currently shooting for having it available around the middle of November.

**Comment by shurkanTwo** [comment]
@jdonenine thanks for your quick reply. Looking forward to the update! 😄

**Comment by shurkanTwo** [comment]
Is there a link for version 1.4 were I can keep track of the progress and issues that are still pending for the new version?
