### ISSUE TITLE
K8SSAND-1016 ⁃ How to manually define JWT secret for Stargate API

### ISSUE THREAD

**Issue by caniko** [k8ssandra/k8ssandra#1158]
**Type of question**

How to perform a particular operation

**What did you do?**
I am in the development phase of my K8ssandra project and run K8ssandra locally on minikube. I have created a Django server that generates JWT tokens for its users.

Furthermore, I was hoping to use these JWT tokens for authentication on Stargate API. I don't know how to activate JWTs in K8ssandra, and it is not mentioned anywhere in the documentation. Moreover, I am also not sure how to share a common secret between Stargate and Django, that would allow Django JWTs to be used in Stargate authentication. Is there a setting that I missed? Does K8ssandra even support this feature?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1016) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1016
┆priority: Medium

**Comment by jdonenine** [comment]
This isn't something that's inherently part of K8ssandra, no.  I think it's probably more of a question of how you would integrate that with Stargate, if you can.  Once that's known you'd then want to think about how in the K8s world you'd need to orchestrate that integration and configure it -- at that point you could think about how to achieve it with K8ssandra.

The beginning of that thread would need to start with the Stargate team.  It looks like you've opened up a question on their side and Doug replied, have you managed to get things working on that side manually at this point?

**Comment by adutra** [comment]
FYI I recall a discussion with Doug where I've been told that JWT-based authentication should be preferred over the (default) table-based authentication. Unfortunately, K8ssandra 1.x and 2.x both use the table-based approach, and that's currently not configurable. We might want to investigate how to make this configurable, keeping in mind that when JWT auth is enabled by the user, then the user would be required to provide their own JWT token server.

**Comment by jsanda** [comment]
I am closing this since we are not actively adding new features in 1.x and since we a corresponding [issue](https://github.com/k8ssandra/k8ssandra-operator/issues/531) in k8ssandra-operator.
