### ISSUE TITLE
K8SSAND-1036 ⁃ Is there any way of changing additional cassandra.yaml parameters ? 

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1166]
Hi All,

When looking though the Helm charts I couldn't find a way to change some additional settings like: 

Especially: 

* batch_size_warn_threshold_in_kb
* batch_size_fail_threshold_in_kb

But also these: 

* counter_write_request_timeout_in_ms
* request_timeout_in_ms
* read_request_timeout_in_ms
* range_request_timeout_in_ms
* write_request_timeout_in_ms 

Thanks for any suggestion on how to adjust these.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1036) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆epic: Advanced Component Configuration
┆fixVersions: k8ssandra-1.4.0
┆friendlyId: K8SSAND-1036
┆priority: Medium

**Comment by jdonenine** [comment]
Hey @mikekuzak it would be possible to manipulate the CassandraDatacenter resources that get deployed after installation, but you would lose those settings when you upgrade the charts later, so admittedly it's not a perfect answer.

With 1.x we've taken a very opinionated view of directly representing the settings available within the charts.  For the k8ssandra-operator we've kicked around a lot the question of if that's the best way to go or should we be able to just dump a blob of configuration in and pass it through.  Much more flexible but it then lacks the saftey we might like.

We'd definitely be interested to hear what you think about that tradeoff -- is having access to any and every configuration option more important for you there?

**Comment by mikekuzak** [comment]
HI @jdonenine 

I checked the cassandra config and the default values seem actually fine I guess

```
unlogged_batch_across_partitions_warn_threshold: 10
batch_size_warn_threshold_in_kb: 64
compaction_large_partition_warning_threshold_mb: 100
batch_size_fail_threshold_in_kb: 640
tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
dynamic_snitch_badness_threshold: 0.1
gc_warn_threshold_in_ms: 1000
```
But querying the data via stargate :9042 brings back the following exception:
`
Batch for [mpi.timeserie_double_daily, mpi.timeserie_metadata] is of size 2
8505, exceeding specified threshold of 5120 by 23385.
`
which does not reflect these thresholds I think.

**Comment by jsanda** [comment]
While we are still trying to figure out the best way(s) to expose and manage configs, I do think it is worthwhile to expose some of these settings in the short term. These and other settings have come up before (see #1023). If you want to use K8ssandra for production, it certainly makes sense to want a lot of these properties to be configurable.
