### ISSUE TITLE
K8SSAND-1049 ⁃ Can medusa restore to a different Cluster, same dc names ? 

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1185]
**What did you do?**
We have 2 K8s environments QA, DEV. Cassandra has been deployed with Medusa and configured to the same minio bucked from these 2 environments. Both Environments have the same dc, rack name, same node count. 

Ran backup on the QA K8s Cluster: 

```
helm install minio-backup k8ssandra/backup -n k8ssandra --set name=cassandra-backup-20211113,cassandraDatacenter.name=dc1
```

Checked in Minio:

![image](https://user-images.githubusercontent.com/18675587/141790405-1bedeb8a-3cef-4090-a396-d6d4c0e2c003.png)

Tried to restore from Minio to the second cluster. 

```
helm install minio-restore k8ssandra/restore --set name=restore-backup-20211113,backup.name=cassandra-backup-20211113,cassandraDatacenter.name=dc1 -n k8ssandra
```

The medusa operator is now constantly throwing errors:

```
2021-11-15T13:31:43.946Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "cassandra.k8ssandra.io", "reconcilerKind": "CassandraRestore", "controller": "cassandrarestore", "name": "restore-backup-20211113", "namespace": "k8ssandra", "error": "CassandraBackup.cassandra.k8ssandra.io \"cassandra-backup-20211113\" not found"}
```

Looks like restore only works on the cluster where the backup has been taken ?

**Did you expect to see some different?**
Restore to any cluster.

**Environment**
Cassandra 3.11.10, 3 node cluster

* Helm charts version
v1.3.3

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1049) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1049
┆Priority: Medium

**Comment by jdonenine** [comment]
Hey @mikekuzak it is indeed not currently possible.  We have a project scoped out to tackle it however.  You can check out the bulk of that here if you're interested:  https://k8ssandra.atlassian.net/browse/K8SSAND-515

There's also a design document you can checkout here:  https://github.com/k8ssandra/k8ssandra/blob/main/technical-docs/2021-05-remote-restore-redesign.md

**Comment by jdonenine** [comment]
Going to close this issue itself out as the feature discussed here is already broken down into greater detail in the series of issues necessary for it in https://k8ssandra.atlassian.net/browse/K8SSAND-515.
