### ISSUE TITLE
K8SSAND-1094 ⁃ Compatibility testing for K8s v1.23

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1223]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
K8s v1.23 is now available and should be accounted for in version compatibility testing.

**Describe alternatives you've considered**
N/A

**Additional context**
https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1094) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1094
┆priority: Medium

**Comment by adejanovski** [comment]
Our focus now being on k8ssandra-operator, I'll close this ticket.
