### ISSUE TITLE
K8SSAND-1176 ⁃ How to persist PV's, things tried and behavior noticed, and reason it's needed.

### ISSUE THREAD

**Issue by Macfelon** [k8ssandra/k8ssandra#1261]
Hi, I had opened an issue before but closed it, asking for an option to not delete the PVC's when a pod is scaled down (via cluster restart, scale change, etc).

It was communicated if we stop the DC, the PVC's would not be deleted.

I had created a new class that retained my PV's, tried to stop the DC (there isn't really a stop option?  This confuses us).  But re-synced with a replace, and it retained my PV's but created a whole new set of PV's because in a multi-node environment it's all going as Dynamic.

Now, the reason this is needed, is we have a product called Pega that uses Cassandra as both a transient data source but also uses it for what is called adaptive learning and the data is only on the Cassandra DB's, not anywhere else.  When we perform cluster maintenance we lose the DC and also the PV's with K8ss.  Bitnami Cass preserves them and reaquires them on restart.

So, either we are doing something wrong with our DC or there is a gap we need to overcome.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1176) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1176
┆priority: Medium

**Comment by jsanda** [comment]
There is a `stopped` property in the CassandraDatacenter spec. When `true` cass-operator will scale all StatefulSets down to zero. PVs remain intact.

If you are using k8ssandra, be aware this this property is not exposed in the Helm charts. You will need to apply the change directly to the CassandraDatacenter.

I'm not quite sure I understand how things are going wrong for you, but I can tell you that PVs are retained and reused both when setting `stopped: false` and when recreating the CassandraDatacenter provided the name is the same.

**Comment by Macfelon** [comment]
Good Morning, 

So we tried the following:  

kubectl patch cassandradatacenter/dc1 -p '[{"op": "replace", "path": "/status/conditions/1/status", "value": "True"}]' --type=json --namespace=datastax
cassandradatacenter.cassandra.datastax.com/dc1 patched

status:
cassandraOperatorProgress: Ready
conditions:

lastTransitionTime: "2022-01-19T14:41:11Z"
message: ""
reason: ""
status: "False"
type: ScalingUp
lastTransitionTime: "2022-01-18T21:11:47Z"
message: ""
reason: ""
status: "False"
type: Stopped
lastTransitionTime: "2022-01-18T21:11:47Z"
message: ""
reason: ""
status: "False"
type: ReplacingNodes

And as you see in the existing properties it doesn't seen to take effect but properties like Size when we update it does take effect, so we are still confused on this issue.

**Comment by burmanm** [comment]
Hey, good attempt, but Status fields are not usersetable (they're for the operator to indicate the status - it does not read updates you set there). The correct field is `.spec.stopped` (https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_types.go#L157) as seen in the test here:

https://github.com/k8ssandra/cass-operator/blob/master/tests/scale_up_stop_resume/scale_up_park_unpark_suite_test.go#L84

So set it to "true" when you want to stop the pods and false when you want to resume it.

**Comment by Macfelon** [comment]
Ok, yes, this has been able to be done now, thank you!

**Comment by sbbagal13** [comment]
@Macfelon , @burmanm I am facing same issue , I didn't get the solution from above discussion. Could you please give some more details on resolving this ?

**Comment by chenweisomebody126** [comment]
> Hey, good attempt, but Status fields are not usersetable (they're for the operator to indicate the status - it does not read updates you set there). The correct field is `.spec.stopped` (https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_types.go#L157) as seen in the test here:
> 
> https://github.com/k8ssandra/cass-operator/blob/master/tests/scale_up_stop_resume/scale_up_park_unpark_suite_test.go#L84
> 
> So set it to "true" when you want to stop the pods and false when you want to resume it.

Hey @burmanm , it seems the links you posted here no longer point to the test code. Do you mind guide me to an example?
Thanks!
