### ISSUE TITLE
K8SSAND-1195 ⁃ K8ssandra 1.4.x compatability with K8s

### ISSUE THREAD

**Issue by shurkanTwo** [k8ssandra/k8ssandra#1276]
**Type of question**

 Open question

I would like to know with which K8s versions K8ssandra 1.4.0 / 1.4.1 is compatible with?
In your documentation it is stated, that K8s version 1.17 is supported: https://docs.k8ssandra.io/install/local/
However if I look at the changelog of K8ssandra release v1.4.0 the following two changes suggest, that it is only compatible with K8s version 1.19, because networking.k8s.io/v1 is only availabel as of version 1.19 of K8s?

* [ENHANCEMENT] Support both v1beta1 and v1 ingress formats for k8s 1.22 compatibility
* [ENHANCEMENT] #1150 Update CRD versions to v1 from v1beta1 allowing compatibility with k8s 1.22.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1195) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1195
┆priority: Medium

**Comment by jdonenine** [comment]
If you take a look at this test https://github.com/k8ssandra/k8ssandra/blob/main/.github/workflows/k8s_matrix_test.yaml you'll see the series of versions that we test against. We are still testing a 1.17 patch right now.

**Comment by shurkanTwo** [comment]
@jdonenine Thats awesome and good to know. Thanks a lot!
