### ISSUE TITLE
K8SSAND-1202 ⁃ Provide examples of custom chart configurations

### ISSUE THREAD

**Issue by pmcfadin** [k8ssandra/k8ssandra#1279]
A question raised in the K8ssandra discord that could be easily answered by an example:

"I don't want all the features like Medusa, reaper, etc. I would like to have a simpler chart"

The solution is to have some example configs under the /example directory in the main repo that shows what a chart would look like.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1202) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1202
┆priority: Medium

**Comment by AbhijithGanesh** [comment]
I would like to work on this and make an example of a custom chart

**Comment by jdonenine** [comment]
That's probably a good idea for some initial content -- recently a similar kind of question has come up around a helm chart for only cass-operator... which you basically have with K8ssandra and disabling the stuff you don't care about.

A directory of sample values.yaml files for different scenarios would be a nice to have.  We'd be happy to have you kick that off @AbhijithGanesh

**Comment by AbhijithGanesh** [comment]
Yeah I wanted something like that for one of my projects and discussed about this with the community members. I understand it's just disabling it with the `enable` flag. Anyways I'll ask if I run into issues

**Comment by adejanovski** [comment]
Closing as K8ssandra is now deprecated.
