### ISSUE TITLE
K8SSAND-80 ⁃ Add integration tests for Stargate

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#132]
#68 added initial support for Stargate. We need to integration tests for the Stargate functionality.

**TODO:** Flush out the details for what verification the test(s) should perform.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-80) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-80
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/132?planning-poker) with ZenHub @burmanm @adutra @jsanda @Miles-Garnsey

**Comment by bradfordcp** [comment]
Good point @adutra, closing in favor of the integration tests in 2x
