### ISSUE TITLE
K8SSAND-1299 ⁃ Tests fail when /docs is not present

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1337]
**Describe the bug**
In #1333 we removed the `/docs` directory from the main branch since that content will now live on the `docs` branch.  When I did that a whole bunch of tests failed.  It appears that test are referencing example values within the docs content.

Here is an example of one of the failures:

```
Output: ***
                    stdout: ***
                        Lines: nil,
                        merged: ***
                            Mutex: ***state: 0, sema: 0***,
                            Lines: [
                                "Error: open /home/runner/work/k8ssandra/k8ssandra/docs/content/en/tasks/connect/ingress/kind-deployment/traefik.values.yaml: no such file or directory",
                            ],
                        ***,
                    ***,
                    stderr: ***
                        Lines: [
                            "Error: open /home/runner/work/k8ssandra/k8ssandra/docs/content/en/tasks/connect/ingress/kind-deployment/traefik.values.yaml: no such file or directory",
                        ],
                        merged: ***
                            Mutex: ***state: 0, sema: 0***,
                            Lines: [
                                "Error: open /home/runner/work/k8ssandra/k8ssandra/docs/content/en/tasks/connect/ingress/kind-deployment/traefik.values.yaml: no such file or directory",
                            ],
                        ***,
                    ***,
                    merged: ***
                        Mutex: ***state: 0, sema: 0***,
                        Lines: [
                            "Error: open /home/runner/work/k8ssandra/k8ssandra/docs/content/en/tasks/connect/ingress/kind-deployment/traefik.values.yaml: no such file or directory",
                        ],
                    ***,
```

Our tests shouldn't rely on the docs not changing content over time, so we should make the test content self-contained.  With the test content self-contained we can then safely remove `/docs` again.

**To Reproduce**

1. Delete `/docs` directory
1. Run the integration tests

**Expected behavior**
Test success should not depend on content from `/docs`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1299) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-v1.5.0
┆friendlyId: K8SSAND-1299
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/1337?planning-poker) with ZenHub @emerkle826 @jeffbanks @Miles-Garnsey

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/1337?planning-poker) with ZenHub @adejanovski @jeffbanks
