### ISSUE TITLE
Disabling Reaper generates an invalid CassandraDatacenter manifest

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#135]
## Bug Report

**Describe the bug**
Reaper is enabled by default. Disabling it generates an invalid CassandraDatacenter manifest.

**To Reproduce**
1. `helm install k8ssandra k8ssandra/k8ssandra`
2. `helm install reaper-test k8ssandra/k8ssandra-cluster --set repair.repaer.enabled=false
3. See the error:

```
Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: [spec.podTemplateSpec.spec.initContainers: Invalid value: "null": spec.podTemplateSpec.spec.initContainers in body must be of type array: "null", spec.podTemplateSpec.spec.containers.env: Invalid value: "null": spec.podTemplateSpec.spec.containers.env in body must be of type array: "null"]
```

**Expected behavior**
The chart should install cleanly with Reaper disabled.

**Environment (please complete the following information):**

* Helm charts version info
0.17.0

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by burmanm** [comment]
This type of detection was something I wanted to investigate with helm testing also. Not sure if `helm lint` catches these, but just installing with different properties to kind should. Or perhaps even envtest if we find a way..
