### ISSUE TITLE
K8SSAND-1329 ⁃ jmx-credentials container should run as non-root user

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1358]
**Is your feature request related to a problem? Please describe.**
The `jmx-credentials` init container runs if either authentication or Reaper is enabled. It uses a busybox image which runs as root. 

**Describe the solution you'd like**
For improved security it should use a non-root user as most of our containers do.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1329) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1329
┆priority: Medium

**Comment by burmanm** [comment]
The image is not the problem, the problem is that there's no default securityContext. That applies to nearly all the images, they don't set the securityContext to prevent running as root.

**Comment by jsanda** [comment]
Closed by #1359
