### ISSUE TITLE
K8SSAND-1536 ⁃ Cluster scoped Helm deployments for k8ssandra-operator v1.1 are broken

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1417]
The `clusterrole.yaml` template file for k8ssandra-operator wasn't updated during the v1.1 release and is missing entries for newly created CRDs.
This causes cluster scoped deployments to fail as the operator cannot access MedusaBackup objects.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1536) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1536
┆priority: Medium

**Comment by discostur** [comment]
@adejanovski when do you expect a new bugfix release? just tried to upgrade k8ssandra-operator from 1.0.2 -> 1.1.1 and hit the bug you fixed in #1419 ...

**Comment by jsanda** [comment]
@discostur would you mind opening a new issue that includes the specific error(s) you hit? Thanks.

**Comment by discostur** [comment]
@jsanda it's not a new issue, i just upgraded the operator and the new CRD didn't get installed; Just waiting for a new release which contains the fixes in #1419 ...

**Comment by jsanda** [comment]
#1419 didn't include any CRD changes. The main change was to the clusterrole.yaml template. That should be available in version 0.37.4 of the k8ssandra-operator chart.
