### ISSUE TITLE
Set up a stable Helm chart repo

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#145]
**Is your feature request related to a problem? Please describe.**
This issue is related to #67.

Let me first summarize the workflow for how new chart versions are made available:

* Submit a PR with a chart change
  * The PR must update the version number of all charts. 
  * GH Actions currently  requires the version number to be the same across all charts
*  PR is merged
* Create and push new tag in git
  * GH Actions publish new charts to k8ssandra Helm chart repo 
  * Charts are published only when a new git tag is pushed

There are a couple problems here. First, creating a git tag/release for every chart change seems like overkill and makes the git tags a bit meaningless. Secondly, there is no way for a user to only consume stable chart versions.

**Describe the solution you'd like**
Users should be able to consume only stable, i.e., released chart versions. We can set up a second chart repo for this. Let's call it k8ssandra-stable. 

Here is a modified workflow might look like:

* Submit a PR with a chart change
  * The PR updates the version of the changed chart
* PR is merged
* GH Actions runs and publishes new chart version to k8ssandra Helm repo
* Other chart changes get merged
* At a later time we create a git tag/release
  * GH Actions publishes the chart version in the git tag to the k8ssandra-stable Helm repo

With these changes, we no longer have to push a new git tag every we want to make a new chart version available. This will allow us to make our usage of git tags more meaningful. Users can consume every new chart version. Users can also choose to only consume stable, released chart versions.

**Comment by bradfordcp** [comment]
I think you shared a link with me at some point @jsanda for a project on github composed of multiple charts ()something Prometheus related IIRC). They had a tag / release for each chart version (of which the charts were versioned separately).

CI handled detection of the new version and created a new GH release with attached artifacts.

**Comment by bradfordcp** [comment]
I'm in agreement though, the current setup is not very flexible. :(

**Comment by jeffbanks** [comment]
I like the idea of a second repo for released charts.  This should minimize any confusion about knowing the stable chart versions.

**Comment by jsanda** [comment]
> I think you shared a link with me at some point @jsanda for a project on github composed of multiple charts ()something Prometheus related IIRC). They had a tag / release for each chart version (of which the charts were versioned separately).
> 
> CI handled detection of the new version and created a new GH release with attached artifacts.

You are probably thinking of https://github.com/prometheus-community/helm-charts.

Initially I tried to think about this like how we typically handle tagging images. For most projects that produce images, when changes are merged into the main branch, a new image is built and tagged with the commit hash. The image is then pushed to a repo. When a release is done, the same image is also tagged with the release version number. Both image tags are available in the image repo.

We do not really have the same tagging functionality with Helm charts. Using an additional, "stable" chart repo gets us closer though.

**Comment by burmanm** [comment]
Adding to this (so it won't be forgotten), the cleaner image and other Dockerbuilds we create in this repo should be automatically updated to the correct hash in the chart version which is tagged.

As in, I send a fix to the cleaner -> that triggers a new Dockerbuild -> that newly created dockertag should be upgraded to the values.yaml and then a new Helm version should be created.
