### ISSUE TITLE
Make Cassandra heap size configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#158]
**Is your feature request related to a problem? Please describe.**
I should be able to configure the JVM heap size for Cassandra.

**Describe the solution you'd like**
There are a lot of heap properties that can be configured for the JVM. For this ticket, I want to focus on only the following three:

* -Xms - min heap size
* -Xmx - max heap size
* -Xmn - new generation size

I prefer to add support for other heap settings in separate tickets. I want to make sure sufficient investigation is devoted to each of the settings since heap and GC settings is a complex topic.

For a good overview on GC tuning and regions, see the [GC Tuning](https://thelastpickle.com/blog/2018/04/11/gc-tuning.html) post on the TLP blog.

The min and max sizes should be the same, so we can have a single property for them, e.g., `heapSize`.

For the new generation, Cassandra uses this formula to calculate a default value - `min(100 * num_cores, 1/4 * heap size)`. This is often times a bad default that can lead to a lot of promotions to the old generations. In terms of GC, promotions are expensive. In my experience I have seen that allocating 50% of the heap to the new generation, particularly in ready heavy workloads yields much better performance. I suggestion we go with half the total heap as a default for the new generation.

We might have properties that look something like this:

```yaml
# example values.yaml
k8ssandra:
  configuration:
    jvm:
      heapSize: 8GB
      newGenerationSize: 4GB
```
When we add multi-DC support (#83) we will want to make this configurable at the DC level as well.

**Comment by jsanda** [comment]
My example in the description of how the properties might look is **not** good. We are going to want to have a top-level `cassandra` property that will have various properties. Auth is a good example. For auth we might have this:

```yaml
cassandra:
  auth:
    enabled: true
```
We want to be careful about throwing stuff under a `jvm` property because it could easily wind up being a dumping ground. If there were just a handful of JVM settings, that might be fine, but there are lots. There are are a lot for each of the garbage collectors. Then we have setting for heap memory. There are properties to configure GC logging. We want to provide some organization and be opinionated about it.

With all that said, I might lean towards something like this:

```yaml
cassandra:
  jvm:
     heapSize:
     heapNewGenerationSize: 
```

I realize it is not all that different from the initial example, but it is import to convey that we should spend time thinking about what should be exposed and how.

**Comment by Miles-Garnsey** [comment]
I was thinking it would be nice to be able to pull these settings out of configMaps if people want to customise them. Would there be interest in that? 

It is nice to keep CRD configurations to a minimum so they don't become monolithic. This way we'd be splitting cassandra.yaml, jvm.options, and other configs out into their own resources.

**Comment by jsanda** [comment]
Hey @Miles-Garnsey,

If you haven't already, take a look at https://github.com/k8ssandra/k8ssandra/pull/109 for some background on the tentative design approach.

Storing the various settings in ConfigMaps would require modifications in cass-operator. cass-operator would have to watch for changes in the ConfigMaps and then apply those changes to the CassandraDatacenter. This would have to be done because the CassandraDatacenter spec is the source of truth. Additionally, cass-operator would have to know which ConfigMaps to watch for each CassandraDatacenter. 

I don't want to simply expose configs in such a way that they map 1-to-1 to various config files. I don't see a lot of value add in that. Where it makes sense, I also want to define configs at the cluster level with the option to override them at the DC level. Heap settings are good candidate for this IMO.

**Comment by Miles-Garnsey** [comment]
I can see your point there @jsanda. Some users may want more customisation though, and you can't expose every possible config for every JVM and GC choice.

This will only become more of an issue with the flexibility 4.0 provides on GC and JVM choices. If you were using an exotic GC (e.g. Shenandoah or similar), how do you ensure that the operator doesn't override whatever custom settings it needs?

I've often been disappointed in the past when operators don't expose some config setting I've needed. I'm wary of this issue as it can completely prevent users from adopting an otherwise perfectly good operator.

**Comment by jeffbanks** [comment]
For release 1.0, the current design includes the following for heap configurations.

- Heap config defined only at cluster level.
- Heap config defined only at DC level.
- Heap config defined at both levels.
- Heap config not existing at either level (defaults to values specified in cassdc.yaml).

Scoped overrides:
- Heap `min` (-Xms) and `max` (-Xmx) values will be set to same values based on the `heap.size` value and map to cass-operator's  `initial_heap_size` and `max_heap_size`.
- Heap `newGenSize` (-Xmn) value will map to cass-operator's `heap_size_young_generation`. 

[Reference documentation ](https://github.com/datastax/cass-operator/blob/master/docs/user/jvm_server_configuration.md)for Cassandra 3.x and 4.x configuration builder keys.

_**Example**_:

```yaml
cassandra:
  # cluster-level settings
  heap:
    # min & max equal
    size: 700M
    newGenSize: 1.4Gi
  # dc specific settings
  dataCenters:
    - name: dc1
      size: 1
      heap:
        size: 600M
        newGenSize: 1.2Gi
    - name: dc2
      size: 1
```
