### ISSUE TITLE
Getting 404 for https://helm.k8ssandra.io/stable

### ISSUE THREAD

**Issue by daveherrington** [k8ssandra/k8ssandra#1627]
## Bug Report

**Describe the bug**
https://helm.k8ssandra.io/stable is broken (404).

**To Reproduce**
1. Navigate to https://helm.k8ssandra.io/stable
2. See 404 error

**Expected behavior**
Expect to be able to get the helm chart from this location.

**Screenshots**
n/a

**Comment by bradfordcp** [comment]
That URL is a helm chart repo. Helm will pull the URL `https://helm.k8ssandra.io/stable/index.yaml` which contains a list of all published charts. Note that `helm.k8ssandra.io` is just hosted on an object store, it does not present a user interface.

```console
> curl -I https://helm.k8ssandra.io/stable/index.yaml
HTTP/2 200 
...

> helm repo add k8ssandra https://helm.k8ssandra.io/stable
"k8ssandra" has been added to your repositories

> helm repo list
NAME                	URL                                                         
k8ssandra           	https://helm.k8ssandra.io/stable    

> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "k8ssandra" chart repository
Update Complete. ⎈Happy Helming!⎈
```

**Comment by bradfordcp** [comment]
See these docs for how to use the helm repository: https://docs-v1.k8ssandra.io/install/local/#configure-the-k8ssandra-helm-repository
