### ISSUE TITLE
Issue with Replication Alteration During K8ssandra v1 to K8ssandra-Operator Migration

### ISSUE THREAD

**Issue by vcanuel** [k8ssandra/k8ssandra#1632]
Hi,

I'm currently in the process of migrating a K8ssandra v1 cluster to K8ssandra-operator, following the guide provided at [K8ssandra Migration Documentation](https://docs.k8ssandra.io/tasks/migrate/).

I've encountered an issue during the "Decommission dc1" section. The guide suggests updating the K8ssandraCluster object definition by removing the externalDatacenters and additionalSeeds sections for the new datacenter. However, when I implement these changes, each operator attempts to alter the replication settings within their own data center through the MigrationManager. This action leads to a disrupted cluster state.

For instance, in the system_auth keyspace:

    DC1 sets replication to: {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'dc1': '3'}
    DC2 sets replication to: {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'dc2': '3'}

This discrepancy in replication settings between data centers is causing operational problems. Is there a way to halt or manage the migration process on the first datacenter to prevent this conflict?

Any guidance or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by adejanovski** [comment]
Hi @vcanuel,

> However, when I implement these changes, each operator attempts to alter the replication settings within their own data center through the MigrationManager.

K8ssandra v1 shipped with cass-operator as the only operator. I don't think it should attempt to modify the replication by itself if you remove the externalDatacenter entries on the k8ssandra-operator side.

Could you be more specific about your installation for both DCs and indicate which operator instances are triggering the replication changes?

In any case, I'd recommend to turn off the deployment of the operator that is responsible for the DC which will be decommissioned and perform the changes in the K8ssandraCluster object. You can then delete the Cassandra statefulsets in the decommissioned DC and the associated PVCs/PVs.

**Comment by vcanuel** [comment]
Hi,

Thank you for your recommendation. We have since resolved the issue by decommissioning dc1, so further investigation into the original problem isn't possible. Your insights might be helpful for similar situations in the future. We can close this issue now.

Best regards,

Vincent.
