### ISSUE TITLE
If metrics are set to :8080, then the containerPort should be set also

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra#1634]
## Bug Report

**Describe the bug**
When the metrics.address is set, we have to add the corresponding containerPort also, unless it is set to 127.0.0.1 in which case we shouldn't expose it.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

`$ helm ls -A` 

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 

* Kubernetes version information:

`kubectl version`

* Kubernetes cluster kind:

**Additional context**

**Comment by Miles-Garnsey** [comment]
ContainerPort isn't strictly necessary if the port is exposed via a service, I assume this is just for informational/self-documenting purposes? What's the error we actually get?
