### ISSUE TITLE
Prometheus monitoring for Stargate

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#164]
**Describe the solution you'd like**
Data scraped by the Prometheus instance running within the cluster should include metric data exposed by Stargate

**Additional context**
The assumption is that Stargate already provides a Prometheus metrics endpoint that can be accessed for data.  If not, the work to expose those metrics should be done in the stargate repo.

**Comment by burmanm** [comment]
There's ServiceMonitor instance for the Stargate, isn't it working?

**Comment by jakerobb** [comment]
There was a ServiceMonitor, but it didn't have the right metadata for Prometheus to pick it up. As part of figuring out #249, I fixed it so I could see what was happening. I'll open a PR shortly.
