### ISSUE TITLE
Provide out-of-the-box grafana dashboards for visualizing Stargate metrics

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#165]
**Describe alternatives you've considered**
Like we do for Cassandra running within the cluster, we should provide a pre-built dashboard for monitoring the key metrics related to the Stargate deployment within the cluster.

**Additional context**
If the Stargate team does not already have a dashboard definition that could be used, work with them to define the metrics of interest that should be included.

**Comment by jakerobb** [comment]
I've addressed this as part of diagnosing #249. I'll open a PR shortly.
