### ISSUE TITLE
Add support for Cassandra 4.0-beta4

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#168]
**Is your feature request related to a problem? Please describe.**
K8ssandra only supports 3.x Cassandra - I'd like to use the latest 4.0 beta.

**Describe the solution you'd like**
Similar to #144 we'd like to have flexible support for selecting the Cassandra version that a cluster is deployed with.  This should include 4.0-beta4.

**Describe alternatives you've considered**

**Additional context**
This will only be included in K8ssandra as a beta quality feature.  Once Cassandra 4.0 is GA'd we can update support here to become GA quality and fully on par with the 3.11.x support in #144.

**Comment by jsanda** [comment]
I am giving this a low complexity because the changes on the k8ssandra side primarily involve some minor template updates. The bulk of the work is in https://github.com/datastax/management-api-for-apache-cassandra/issues/65.
