### ISSUE TITLE
K8SSAND-85 ⁃ Configure Traefik ingress to support TLS/mTLS termination

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#171]
**Is your feature request related to a problem? Please describe.**
There is currently no in-built mechanism for providing encrypted communication to/from the cluster.

**Describe the solution you'd like**
Provide configuration to use Traefik for TLS/mTLS termination for the cluster.

**Additional context**
This is _not_ encryption within the cluster.  Leverage the configuration already provided in cass-operator for guidance:

https://www.google.com/url?q=https://github.com/datastax/cass-operator/tree/master/docs/ingress/traefik&sa=D&ust=1610070803748000&usg=AOvVaw2NJw9X6yhzTU0DEjH03g6l

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-85) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-85
┆priority: Medium

**Comment by adejanovski** [comment]
Closing as K8ssandra is now deprecated.
