### ISSUE TITLE
K8SSAND-86 ⁃ Allow for services to be externally exposed through NodePorts

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#172]
**Is your feature request related to a problem? Please describe.**
I don't want to run a full ingress service, but I want external access to my services.

**Describe the solution you'd like**
I want to be able to access services within the cluster (CQL, Medusa, Reaper, Grafana, Prometheus, Stargate) through NodePort mappings.

**Describe alternatives you've considered**
Ingress

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-86) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-86
┆priority: Medium

**Comment by jsanda** [comment]
Closing as won't fix since new feature work is now being done in the k8ssandra-operator repo.
