### ISSUE TITLE
management-api docker-entrypoint.sh fails for C* 3.11.8 and 3.11.9

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#181]
## Bug Report

**Describe the bug**
I cannot deploy Cassandra 3.11.8 or 3.11.9. The `docker-entrypoint.sh` script for management-api fails with this error:

```
Starting Management API
/docker-entrypoint.sh: line 68: /opt/mcac-agent/config/metric-collector.yaml: Permission denied
```

**To Reproduce**
1. Install the k8ssandra chart:

```
$ helm install k8ssandra ./k8ssandra
```

2. Install the k8ssandra-cluster chart:

```
helm install test ./k8ssandra-cluster # Default C* version has already been updated to 3.11.9
```

3. Cassandra pods fail to start

Here are my results for the different images I tried:

* datastax/cassandra-mgmtapi-3_11_7:v0.1.17 (worked)
* datastax/cassandra-mgmtapi-3_11_8:v0.1.17 (failed)
* datastax/cassandra-mgmtapi-3_11_9:v0.1.17 (failed)

**Environment (please complete the following information):**

* Helm charts version info
0.21.0

* Helm charts user-supplied values

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1201", GitCommit:"160736941f00e54acb1c0a4647166b6f6eb211d9", GitTreeState:"clean", BuildDate:"2020-12-08T19:38:26Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by suyambuganesh82** [comment]
I just tried the latest helm chart and I have the same issue in GKE 1.18.12. "/docker-entrypoint.sh: line 68: /opt/mcac-agent/config/metric-collector.yaml: Permission denied"

**Comment by johankritzinger** [comment]
Same issue, and setting k8ssandra.cassandraVersion to "3.11.7" works.

**Comment by jsanda** [comment]
I figured out what is going on. With 3.11.8 and 3.11.9 the Cassandra pod spec is configured with a SecurityContext as follows:

```yaml
  securityContext:
    fsGroup: 999
    runAsGroup: 999
    runAsUser: 999
```
That is configured by cass-operator. Here is the relevant code:

```go
// Calculate if this Docker Image run as the cassandra user?
// This is meant to be used when the CassandraDatacenter does not
// explicitly set the DockerImageRunsAsCassandra field.
func CalculateDockerImageRunsAsCassandra(version string) bool {
	if version == "3.11.6" || version == "3.11.7" || version == "4.0.0" {
		return false
	}

	// Otherwise, we assume the image is running as the "cassandra" user

	return true
}
```

We should be able to set `dockerImageRunsAsCassandra: false` in the CassandraDatacenter spec to work around this. At some point we definitely want to look at supporting running Cassandra as a non-root user, but I don't think that has to happen right now as part of this fix.
