### ISSUE TITLE
Allow enablling/disabling prometheus and grafana

### ISSUE THREAD

**Issue by florissmit10** [k8ssandra/k8ssandra#183]
**Is your feature request related to a problem? Please describe.**
We use a rancher based k8s environment which has a bundled grafana & prometheus. Deploying both prometheus operators causes quite some problems. It is currently not possible to disable the installation of prometheus/grafana

**Describe the solution you'd like**
Prometheus and grafana should get enabled flags to conditionally apply their respective configurations

**Describe alternatives you've considered**
We thought about disabling the rancher monitoring, but thats tricky since it also monitors other worksloads.

**Comment by jsanda** [comment]
Hi @florissmit10 

Thanks for submitting the issue. Do want to you submit PRs for this?

**Comment by florissmit10** [comment]
> Hi @florissmit10
> 
> Thanks for submitting the issue. Do want to you submit PRs for this?

Yes I will pick this up the coming week!

**Comment by bradfordcp** [comment]
To be clear, is the goal to just disable the installation of Prometheus and Grafana components or the ServiceMonitor and Dashboard custom resources as well?

In your environment how are dashboards added to Grafana? Are they loaded in via a Custom Resource or ConfigMap?

**Comment by florissmit10** [comment]
In our environment we could a ServiceMonitor since the prometheus operator is used. Grafana is not provided by an operator so the dashboard CRD's wont work. 
Maybe we could add the following options for maximum flexibility:
`
  grafana.enabled
  grafana.enableDashboards
  prometheus.enabled
  prometheus.enableServiceMonitor
`

**Comment by jsanda** [comment]
We also have the operators - grafana-operator and prometheus-operator. I tend to favor the following:

* `grafana.enabled` - for all Grafana related resources including dashboards and data source
* `grafanaOperator.enabled`
* `prometheus.enabled` - for all Prometheus related resources including ServiceMonitor
* `prometheusOperator.enabled`

**Comment by jsanda** [comment]
@bradfordcp will #176 take care of this?

**Comment by jsanda** [comment]
Closed by #176
