### ISSUE TITLE
K8SSAND-92 ⁃ Delete backups from remote storage when CassandraBack object is deleted

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#216]
**Is your feature request related to a problem? Please describe.**
If I create a CassandraBackup, that causes a backup operator to be performed by Medusa on each of the Cassandra nodes. Backups are stored in remote storage, e.g., an S3 bucket. If I delete the CassandraBackup object, the backup files are orphaned in the S3 bucket. 

**Describe the solution you'd like**
medusa-operator should add a finalizer to the CassandraBackup object. Kubernetes will block deletion of the CassandraBackup until the finalizer is cleared. The backup controller should clear the finalizer after the backup has been removed from remote storage. Medusa's gRPC API provides a `DeleteBackup` operation which makes the necessary calls to delete the backup from remote storage.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-92) by [Unito](https://www.unito.io)
┆Reviewer: Michael Burman
┆epic: Remote Cluster Restore
┆friendlyId: K8SSAND-92
┆priority: Medium

**Comment by burmanm** [comment]
Additional note, this adds a finalizer - so the cleaner must be modified also to remove all these CassandraBackups before trying to uninstall the helm release.

**Comment by lcoram** [comment]
The opposite also appears to be an issue - if you trigger a purge in medusa that removes backups in the s3 storage, they are still in the list of cassandraBackups. If it is recommended to use max_backup_age and max_backup_count in medusa to control the number of backups this is an issue. Are there any plans for properly exposing the medusa purge functionality? However, if deleting the cassandraBackups themselves resulted in them being deleted from storage I could see creating a cronJob to thin out / delete the backups.

**Comment by jsanda** [comment]
>Are there any plans for properly exposing the medusa purge functionality

I don't think there is anything beyond this ticket at the moment.

>If it is recommended to use max_backup_age and max_backup_count in medusa to control the number of backups, this is an issue

It would be great to if you could capture this in a separate feature request issue.

>However, if deleting the cassandraBackups themselves resulted in them being deleted from storage I could see creating a cronJob to thin out / delete the backups.

A CronJob would work. When we build support for scheduled backups, I could see us using a scheduling library like https://github.com/robfig/cron. If we go this route we could reuse that for purging backups as well. Lastly, the controller-runtime, which is main library used for building operators, provides some APIs for handling resources out of cluster which could also be applicable in this scenario.

**Comment by adejanovski** [comment]
We're now planning on implementing this feature in k8ssandra-operator, adding a finalizer on the upcoming MedusaBackup objects.
I'll close this ticket and recreate one on the k8ssandra-operator project.

**Comment by adejanovski** [comment]
Ticket created: https://github.com/k8ssandra/k8ssandra-operator/issues/494
