### ISSUE TITLE
Cleaner job fails when there is no CassandraDatacenter installed

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#218]
## Bug Report

**Describe the bug**
I am testing some template changes that resulted in a failure with a partial deployment. In other words, some resources were created before hitting the failure. Running `helm uninstall` fails with this:

```
$ helm uninstall auth-test
Error: job failed: BackoffLimitExceeded
```

Here are the logs from the cleaner job:

```
$ kubectl logs auth-test-cleaner-job-k8ssandra-7bjfl
2021/01/21 03:20:09 Cleaning resources for uninstall
2021/01/21 03:20:10 Removing CassandraDatacenter(s) managed in release auth-test from namespace default
2021/01/21 03:20:10 Failed to list CassandraDatacenters in namespace: default
```

The problem is `cleaner.go` here:

```go
func (a *Agent) removeCassandraDatacenter(releaseName string) error {
	log.Printf("Removing CassandraDatacenter(s) managed in release %s from namespace %s\n", releaseName, a.Namespace)
	list := &cassdcapi.CassandraDatacenterList{}
	err := a.Client.List(context.Background(), list, client.InNamespace(a.Namespace), client.MatchingLabels(map[string]string{managedLabel: managedLabelValue}))
	if err != nil {
		log.Fatalf("Failed to list CassandraDatacenters in namespace: %s", a.Namespace)
		return err
	}

	for _, cassdc := range list.Items {
		if release, found := cassdc.Annotations[releaseAnnotation]; found {
			if release == releaseName {
				err = a.Client.Delete(context.Background(), &cassdc)
				if err != nil {
					log.Fatalf("Failed to delete CassandraDatacenter: %v\n", cassdc)
					return err
				}
			}
		}
	}

	return nil
}
```
If the `Client.List` call fails we should be calling `errors.IsNotFound()`, and if returns `true`, just return.

* Helm charts version info
k8ssandra 0.27.1

**Comment by jsanda** [comment]
You should be able to reproduce this easily by manually deleting the CassandraDatacenter followed by `helm uninstall`.

**Comment by burmanm** [comment]
I did not manage to replicate this actually, I even wrote a test for it:

```go
	Specify("even in empty namespaces", func() {
		cleaner := &Agent{
			Client:    k8sClient,
			Namespace: CleanerTestNamespace + "notReal",
		}

		Consistently(func() error {
			return cleaner.RemoveResources(cleanerTestRelease)
		}, 1*time.Second, interval).Should(Succeed())
	})
```

Reason it shouldn't fail is because it doesn't return the error, it only logs that issue. But then it throws the error away:

```go
	if err := a.removeCassandraDatacenter(releaseName); err != nil {
		log.Fatalf("Failed to remove Cassandra cluster(s): %v", err)
	}
	return nil
}
```

So that BackoffLimitExceeded with failed job is something else.

**Comment by burmanm** [comment]
And actually, even adding the following:

```go
		result := &cassdcapi.CassandraDatacenterList{}
		Expect(k8sClient.List(context.Background(), result, client.InNamespace(CleanerTestNamespace+"notReal"))).Should(Succeed())
```

Does not fail, since Listing empty resources does not return "errors.IsNotFound".

**Comment by jsanda** [comment]
Hmm... I'll see if I can come up with better steps to reproduce. I actually hit this multiple times yesterday before I took a moment to see what was going on. Each time though was caused by a template error that manifested itself at install time.

**Comment by burmanm** [comment]
The test is now in the main repo.

**Comment by jsanda** [comment]
I am closing this since we had trouble reproducing. I haven't run into this since reporting it.
