### ISSUE TITLE
Make garbage collection in Cassandra configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#220]
Because garbage collection tuning can have a major impact on Cassandra's performance, I think we need to expose some GC configuration for the 1.0 release. As with other configuration settings, we should take into consideration best practices and strive to be opinionated. We also need to changes around 4.0. My understanding is that C* 4.0 will support Java 11, so we may want to expose config settings that specific to 4.0 as well.

This may involve a bit of research and we should create additional tickets as necessary.

**Comment by jsanda** [comment]
@adejanovski given your extensive experience with GC analysis and tuning, it would be great to get your thoughts on this.

**Comment by adejanovski** [comment]
@jsanda, this is totally mandatory IMO. 
You'll need to expose at least the following settings:
- the GC algorithm (CMS, G1, ZGC, Shenandoah)
- the heap size
- the new gen size (which would mean two different things for CMS and G1. With G1, it would be the minimum size that the new gen can take. This is useful to avoid it shrinking too hard after a major collection which can lead to a series of close minor collections before it grows again to a decent size. With CMS it's the fixed size of the new gen)
- The max tenuring threshold

We can probably compute the number of cores for ConcGCThreads and ParallelGCThreads without requiring them to be manually configured.

Then, it could be good to have and `ADDITIONAL_JVM_OPTS` setting that would allow to pass various GC options which will differ from one garbage collector to the other.

Still, while we would allow for flexibility, as you mentioned it would be good to apply best practices settings from the field if nothing is explicitly specified.

For CMS, I'd go with the following defaults:
- Heap size: `min(16G, <half_of_the_available_RAM>)`
- New gen: 40% of the heap size
- Max tenuring threshold: 5
- `min(16, cpu cores)` for ConcGCThreads and ParallelGCThreads

For G1:
- Heap size: `min(31G, <half_of_the_available_RAM>)` (going below 16G isn't really recommended but we're not only dealing with production environments)
- Min new gen size: min(<half of heap size>, 2.5G)
- Max tenuring threshold: 0 
- `min(16, cpu cores)` for ConcGCThreads and ParallelGCThreads

ZGC and Shenandoah will have to be benchmarked a bit more to come up with some proper recommendations.

btw, Shenandoah could be made available with C* 3.11.x if we manage to get/build Cassandra Docker images that use [custom openjdk 8 builds with the Shenandoah backport as base image](https://hub.docker.com/r/shipilev/openjdk-shenandoah/tags?page=1&ordering=last_updated). 
It'll be the same for JDK11 btw as Shenandoah is only being included in the mainstream openjdk builds starting with JDK15 if I remember correctly.

FTR, we have [a section in the tlp-cluster helper script](https://github.com/thelastpickle/tlp-cluster/blob/master/bin/build_cluster.sh#L164-L273) which deals with GC settings. But it's not as configurable as what I'm suggesting here.

**Comment by JeremiahDJordan** [comment]
My recommendation would be you have:
easy mode: C* figures it out by itself
medium mode: User can specify MAX_HEAP_SIZE and HEAP_NEWSIZE
hard mode: User specifies ADDITIONAL_JVM_OPTS with a block that has all their custom stuff in it.  If the custom stuff ends up in the jvm.options / jvm-server.options files then the C* scripts will do the right thing.

**Comment by jsanda** [comment]
As per discussion I am moving this into the 1.0.0 milestone. 

For this ticket ee are only looking to make the minimum changes necessary to allow users to configure garbage collection.
