### ISSUE TITLE
Replace schema job with call to management-api

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#227]
**Is your feature request related to a problem? Please describe.**
When a Reaper object is created, reaper-operator deploys a k8s Job to create the `reaper_db` keyspace. The Reaper application applies its own schema changes, but it does not create the keyspace. The job runs https://github.com/k8ssandra/create_keyspace/blob/master/create_keyspace.py. This was implemented before the management-api exposed a REST endpoint for creating keyspaces. 

**Describe the solution you'd like**
We need to replace the schema job with a call to the management-api. This will be a big improvement as we will no longer have to maintain the python script and its image. Nor will we have to create and run the Job which will be a more efficient workflow.

**Comment by burmanm** [comment]
I wonder if another approach would be to just add support for Keyspace and Roles objects to cass-operator? That way we could simplify the integration, we wouldn't need to call management API from the reaper-operator (thus creating stricter dependency to cass-operator or yet-another-client for management API), but instead just deploy a Keyspace object and let cass-operator take care of processing it.

**Comment by jsanda** [comment]
https://github.com/datastax/cass-operator/issues/382 was recently opened to add support for creating keyspaces and roles. I agree that we ultimately want something for creating keyspaces and roles, but I am not sure I want that to be baked into cass-operator. I might lean more towards some custom jobs. I definitely think it would make sense for reaper-operator to reuse that whatever that solution might be.
