### ISSUE TITLE
Create released versions of medusa-operator

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#234]
**Is your feature request related to a problem? Please describe.**
k8ssandra consumes medusa-operator images that are tagged with commit hashes. We should have release versions which are more easily identifiable.

**Describe the solution you'd like**
Set up GH Actions to create images based off of git tags.

**Comment by jdonenine** [comment]
@jsanda Same question here as in reaper-operator... to simplify things for 1.0.0 can we manually build, tag, and publish the images? Automate things through GH actions post-1.0.0?

**Comment by jsanda** [comment]
I would like to get some initial automation set up. It should take very little time. If it does not happen though, we can definitely do it manually.

**Comment by jsanda** [comment]
Moving this out of the 1.0 bucket. I researched this a bit last night. It will probably take a bit longer than I had anticipated.

**Comment by jdonenine** [comment]
This was wrapped up in 1.0.0.
