### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#239]
Update: Generalizing this issue to cover general developer documentation in addition to the troubleshooting focused content originally requested, we need more than that :-) 

Provide developer-focused documentation via a README in the repository.  Enhanced developer guides will be generated later for the website, likely based on some of the content created here.

Cover enough ground that a newcomer to the project can:
* Get up and running with a basic IDE environment
* Deploying to a local docker-based cluster environment (kind)
* Get a basic lay of the code structure
* Run and debug unit tests
* Have some tips and tricks when troubleshooting template rendering and issues that may occur, which can be misleading
  * Basic guidelines and steps for k8ssandra developers to reference and avoid known issues when changes are made to the various chart models.
  * For example, template rendering output diagnostics and issues with unmarshalling into k8ssandra chart structures.

**Comment by jdonenine** [comment]
I updated this issue to become a more holistic need for developer documentation.

**Comment by johnwfrancis** [comment]
Hi guys, I've self-assigned this, but I'll need guidance.

**Comment by jsanda** [comment]
Would it make more sense for one of the devs on the team to tackle this one?

**Comment by johnwfrancis** [comment]
@jsanda sure, for the first version, but I figure docs would be responsible for the final disposition.

**Comment by jdonenine** [comment]
@johnwfrancis I'd love to see some of our content make it into a more polished form, but definitely this first iteration we're targeting here should be generated by the development team.  Once we have something going it would be awesome if we could get your help reviewing it a bit and making sure it's readable, but I'd like to let it evolve a bit within the team before we try to make it something we'd publish to the website or anything like that.

**Comment by jsanda** [comment]
I have said this before, and I still feel like we have two target audiences with developer docs. I absolutely think we need developer docs on k8ssandra.io for working with the charts. Then consider #462. It involves a number of things outside of the charts such as updating reaper-operator and medusa-operator images, running kustomize to generate updated manifests and CRDs. Of course these things impact the charts so maybe I am looking at this the wrong way.

**Comment by jeffbanks** [comment]
For our current sprint underway, I will plan to scope this to a dev README for assisting k8ssandra developers.  

That is, a quick-start setup with docs references and some tips & tricks.
