### ISSUE TITLE
Documentation page with branding guidelines, logos, font face, etc

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#250]
**Is your feature request related to a problem? Please describe.**
It isn't clear where I can get a copy of the K8ssandra logo to use in my presentation, tweet, blog post, etc.

**Describe the solution you'd like**
I would like a page either in the documentation or standalone on the website which provides brand usage guidelines, colors, fonts, vector and rastor logos.

**Describe alternatives you've considered**
Manually saving the SVGs on the website and converting them to raster assets.

**Additional context**
N/A

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-99) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-99
┆Priority: Medium

**Comment by bradfordcp** [comment]
See the Kubernetes [repo](https://github.com/kubernetes/kubernetes/tree/master/logo) and [CNCF branding](https://branding.cncf.io/projects/kubernetes/) pages.

**Comment by johnsmartco** [comment]
Might have dependencies on Chad Alderson's brand team and/or can use recommendations from the DS style guide. Will investigate.
