### ISSUE TITLE
K8SSAND-102 ⁃ K8ssandra installation on newer k8s distributions (v1.19+) generates warnings

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#267]
## Bug Report
**Describe the bug**
When installing k8ssandra on newer versions of k8s, many warning messages are generated and output about deprecated APIs.  This doesn't impact the success of the installation, but it's confusing and gives a poor initial impression.

**To Reproduce**

1. Launch k8s cluster w/ newer version (v1.19+)
1. Install k8ssandra `helm install k8ssandra k8ssandra/k8ssandra`
1. Observe the warning messages:

```
helm install k8ssandra ~/github/k8ssandra/k8ssandra/charts/k8ssandra
W0128 17:17:49.565856   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.579949   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.590579   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.776846   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.791148   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.803617   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.821538   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:49.988395   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:53.009399   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:53.014772   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:53.026684   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0128 17:17:53.032003   77553 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
NAME: k8ssandra
LAST DEPLOYED: Thu Jan 28 17:17:55 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
```

**Expected behavior**
K8ssandra should install without any warning messages.  No deprecated APIs should be used.

**Environment (please complete the following information):**

* Helm charts version info

```
% helm ls -A
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
k8ssandra	default  	1       	2021-01-28 17:17:55.612702 -0500 EST	deployed	k8ssandra-0.34.0	3.11.7 
```

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-22T22:54:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

kind w/ node image kindest/node:v1.19.7

```
% kubectl get nodes
NAME                      STATUS   ROLES    AGE     VERSION
k8ssandra-control-plane   Ready    master   3m3s    v1.19.7
k8ssandra-worker          Ready    <none>   2m30s   v1.19.7
k8ssandra-worker2         Ready    <none>   2m30s   v1.19.7
k8ssandra-worker3         Ready    <none>   2m30s   v1.19.7
```

**Additional context**

I tested version v1.16 - v1.20 and the warnings start appearing in v1.19.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-102) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-102
┆Priority: Medium

**Comment by jsanda** [comment]
We rely on operator-sdk for most k8s API versions. operator-sdk 1.3.0 was released back in December and it bumped dependencies to the k8s 1.19 versions. See https://github.com/operator-framework/operator-sdk/pull/4294. We are currently using 1.0.1. I don't want us to fall too far behind.

**Comment by burmanm** [comment]
Given that we dropped the 1.15 support, this could be more easily solved now as well.

**Comment by burmanm** [comment]
This is missing more deprecations, as ingress is also:

logger.go:66: W0324 14:17:23.209540   65036 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by burmanm** [comment]
And from cass-operator, also this:

admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration

**Comment by jsanda** [comment]
>This is missing more deprecations, as ingress is also:
>
>logger.go:66: W0324 14:17:23.209540 65036 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

We need to see if v1 is available in 1.16. If it is then we should make the change. If it is not available, we will need to add some conditional logic in the templates. Helm makes the k8s version info available through the `Capabilities.Kube` property.

**Comment by jsanda** [comment]
>And from cass-operator, also this:
>
>admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration

@burmanm where is that one coming from? We aren't deploying the webhook.

**Comment by burmanm** [comment]
It's visible in the tests, that's where I caught it from.

**Comment by burmanm** [comment]
https://github.com/k8ssandra/cass-operator/pull/11 fixes this issue for cass-operator
