### ISSUE TITLE
Docs should present more content around Stargate

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#278]
**Is your feature request related to a problem? Please describe.**
Stargate is a big part of the k8ssandra platform, but the current information about how to use it within k8ssandra is a bit buried and hard to find without going looking for it:

https://k8ssandra.io/docs/topics/accessing-services/stargate/

**Describe the solution you'd like**
* The Stargate content that already exists should be molded to be included in the `Getting Started` guide.
* Stargate content should be updated now that default ingress support has been added

**Additional context**
Default ingress support was added:  https://github.com/k8ssandra/k8ssandra/issues/163 with some outstanding decisions still to be made that will be relevant to this documentation effort:  https://github.com/k8ssandra/k8ssandra/issues/253

**Comment by johnsmartco** [comment]
To raise awareness, @johnwfrancis added Stargate info in the Quick start for developers and links to several topics that cover details. From new sections:

- https://k8ssandra.io/docs/getting-started/developer/
- https://k8ssandra.io/docs/getting-started/developer/#access-k8assandra-using-the-stargate-apis 

Introduces Stargate for  info and links to reference docs for: 

- Access Document Data API
- Access REST Data API
- Access GraphQL Data API

Also, Jeff's topic was raised up a level for greater visibility: https://k8ssandra.io/docs/topics/stargate/
... with provided links to the Stargate.io docs.

@jdonenine, should we close this Issue #278? Or, is there more to cover from a K8ssandra user (dev) perspective? Thanks.

**Comment by johnsmartco** [comment]
Closing - can cover additional needed info in subsequent issue.
