### ISSUE TITLE
scripts/delete-crds.sh is deleting too many CRDs

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#285]
## Bug Report

**Describe the bug**
When I run `scripts/delete-crds.sh` it delete all associated CRDs with K8ssandra **AND** Traefik CRDs. Our current guidance installs Traefik separately from K8ssandra so it seems a little odd that this script nukes those CRDs too.

**To Reproduce**
1. Create a K8ssandra release
2. Create a Traefik release
3. Uninstall the K8ssandra release
4. Run `scripts/delete-crds.sh`
5. Note that your Traefik installation is now hosed.

**Expected behavior**
I expect the CRDs to be deleted are those that are installed as part of K8ssandra, **not** Traefik.

**Environment (please complete the following information):**
N/A

* Helm charts version info
```console
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
k8ssandra	default  	3       	2021-01-29 23:10:29.655797077 -0500 EST	deployed	k8ssandra-0.38.0	3.11.7     
```

* Helm charts user-supplied values
Not really relevant for this bug but included anyway.
```console
USER-SUPPLIED VALUES:
cassandra:
  cassandraLibDirVolume:
    storageClass: local-path
stargate:
  enabled: true
```

* Kubernetes version information:
```console
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
```console
k3d version v3.0.1
k3s version v1.18.6-k3s1 (default)
```

**Additional context**
N/A

**Comment by burmanm** [comment]
It's not meant for users, it's a dev tool.

**Comment by jsanda** [comment]
I guess we could add a comment somewhere that it is for dev use.

**Comment by jdonenine** [comment]
Maybe we could drop a README in that directory?

**Comment by jeffbanks** [comment]
I am adding details of the scripts as part of documentation for `developer tools/scripts` section.  There are also scripts provided for `setup`, `install`, `update`, and `removal`.  

This section will include specific notation for Traefik being included by default, but can easily be customized to exclude it from the script as needed.

**Comment by jsanda** [comment]
@jeffbanks where is the `developer tools/scripts` section?

**Comment by jeffbanks** [comment]
In the PR I've put `dev-tools` as a sibling folder to ingress, provide-a-cluster, restore-a-backup, etc. under the `topics` section.  I'm open to where this resides, it seemed to make sense under topics.

The thought is that it now includes only the developer script definitions, but could be a good location to include other developer tools that are related to the use of k8ssandra.

**Comment by jsanda** [comment]
I am on the fence about putting dev docs with the user docs. I mentioned this on another ticket recently but do not recall which one. They are targeting different audiences with different use cases. It might be worth having some discussion on this to see what others think. I may very well be in the minority with my point of view 😄

**Comment by bradfordcp** [comment]
Not looking to reopen the issue, but it is worth noting. I was using this script as a developer. It ended up hosing the functional Traefik install I was running.
