### ISSUE TITLE
Where's values.yaml?

### ISSUE THREAD

**Issue by johnwfrancis** [k8ssandra/k8ssandra#302]
In the getting started:

Stargate deployment is disabled by default. To enable it, modify the values provided to the helm install/upgrade of the k8ssandra chart.

This can be done by adding to the **values.yaml** file provided to helm:

Where is that file? Would this be a separate external step? No context if I do want to enable stargate.

**Comment by bradfordcp** [comment]
During installation you may add `-s stargate.enabled=true` to your `helm install` command. Optionally, helm support something called a values file `values.yaml` here, but any name may be used. All of your configuration overrides are added to this file and it is referenced during `helm install` with `-f values.yaml`

**Comment by johnwfrancis** [comment]
Okay, it would be good to be explicit here. I couldn't figure it out just from the instructions.
