### ISSUE TITLE
After I install k8ssandra using the quick start...

### ISSUE THREAD

**Issue by johnwfrancis** [k8ssandra/k8ssandra#303]
https://k8ssandra.io/docs/getting-started/#install-k8ssandra

Commands worked with no problem, but where do I go now? Shouldn't there be Next steps at the end or something?

**Comment by bradfordcp** [comment]
Definitely, IMHO the getting started section would at a minimum feature

1. Helm repo installation
2. Chart installation
3. Validation (Did all services come up? How do I know it's ready to accept traffic?)
4. Steps to connect to C* with `kubectl port-forward (all users should have this capability). Where can I get cqlsh to test?

From here I'm curious what the best approach is...

* Provide a call to action directing users to explore the other components (Check out X, Get started writing code against Y)
* Continue along with a guided tour of the other interfaces available (Reaper and Grafana come to mind).

What are your thoughts?

**Comment by bradfordcp** [comment]
Any tunneling into the cluster as part of getting started should leverage `kubectl port-forward` over ingress or nodeport.

**Comment by bradfordcp** [comment]
Related #279
