### ISSUE TITLE
Accessing Services > Cassandra...

### ISSUE THREAD

**Issue by johnwfrancis** [k8ssandra/k8ssandra#304]
https://k8ssandra.io/docs/topics/accessing-services/cassandra/

I have no idea what this page accomplishes. It certainly didn't help me access my shiny new C* instance in minikube.

**Comment by bradfordcp** [comment]
This is currently a stub and not very helpful at all. It should be removed until appropriate documentation is developed for accessing Cassandra. I will add comments here with links to follow-up issues.

**Comment by bradfordcp** [comment]
#313 - Within K8s cluster
#314 - Outside via `kubectl port-forward`
#315 - Outside via Ingress (port-based without TLS)
