### ISSUE TITLE
Why are we documenting Ingress setup for K8?

### ISSUE THREAD

**Issue by johnwfrancis** [k8ssandra/k8ssandra#305]
https://k8ssandra.io/docs/topics/ingress/traefik/k3d-deployment/

Are we really expected to document how to set up ingress for any given k8 deployment? This is a hairy subject that's likely different for each customer (and already solved.)

**Comment by bradfordcp** [comment]
This is a very good point. Unfortunately, the ingress spec for Kubernetes is focused solely on HTTP ingress. This works fine for every component except Stargate native protocol (9042) and Cassandra native protocol (9042). Many ingresses provide _some_ way to expose TCP based services via their controller. Configuration for TCP-based ingress is _usually_ handled with a custom resource that is unique to the ingress controller.

* Traefik - [IngressRouteTCP](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp)
* Kong - [TCPIngress](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/guides/using-tcpingress/)
* Voyager - [Ingress](https://voyagermesh.com/docs/7.1.1/guides/ingress/tcp/overview/) - note `apiVersion` is different despite the `kind` matching the native k8s resource.

Installation of the ingress controller is likely outside of scope for our documentation, but if we template any of the above resources (currently only Traefik has been templated for TCP workloads).  We should indicate this somewhere in our docs along with how to enable that functionality (what values need to be set in K8ssandra's `values.yaml`).

**Comment by burmanm** [comment]
I think part of Ingress documentation was also to provide a simple way for laptop-dev, instead of production quality ingress setup. Although for dev-purposes we could probably simplify things even more (like provide a script that setups everything starting from kind).
