### ISSUE TITLE
Backup restore doc too narrow...

### ISSUE THREAD

**Issue by johnwfrancis** [k8ssandra/k8ssandra#307]
https://k8ssandra.io/docs/topics/restore-a-backup/

This is completely specific to Amazon, but SSB&R supports Azure, Google, and local disk options as well as composite solutions: https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/operations/opsBackupRestoreCreateBackupStore.html. It would be nice to address each of them (if possible--I assume there are available yaml options).

**Comment by bradfordcp** [comment]
SSB&R is not a component of K8ssandra. All backup and restore operations are handled via Medusa and the Backup / Restore charts. With that said we I think we should consider a couple of changes

1. Change this page's URL. This page covers both taking a backup and restoring it.
2. Transition this page into an index of multiple examples with each backup target having a separate subpage (AWS, Azure, etc)

What do you think?
