### ISSUE TITLE
K8SSAND-106 ⁃ Document accessing Cassandra via native protocol from within the K8s cluster 

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#313]
**Describe the solution you'd like**
We should indicate where services are listening given a Helm release name, cluster name, dc name, and namespace. Ideally, we should call out if specifying the namespace is required (IIRC it is _not_ if the Cassandra DC is in the same namespace as the client pod).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-106) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-106
┆priority: Medium

**Comment by jsanda** [comment]
When you run `helm create <chart-name>` one of the files it generate is a NOTES.txt. That file can include templates and is output at the end of `helm install`. I thought I already had a ticket for this but I cannot find it. In any event we can add/update to include info such as the following:

* How to access superuser credentials
* How to access cqlsh via port-forward
* How to generate auth token for Stargate
* How to make requests to Stargate

**Comment by johnwfrancis** [comment]
Okay I believe we cover all this currently. Okay to close?

**Comment by jsanda** [comment]
Based on my previous comment I think this is more of a Helm templating update vs a docs update. We definitely should have the NOTES.txt template.

**Comment by bradfordcp** [comment]
Closing this issue as we have other issues discussing retrieving credentials and connecting to services.
