### ISSUE TITLE
K8SSAND-107 ⁃ Document connecting to C* via simple TCP ingress (port-based, no-TLS)

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#315]
Given a K8ssandra cluster deployed with Ingress enabled. Document how to connect via the ingress with cqlsh as an example client.

Key points:

* Without TLS / SNI _each_ C* cluster will require its own dedicated external port

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-107) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-107
┆priority: Medium

**Comment by johnwfrancis** [comment]
I can't seem to remember, did we cover this for 1.0?

**Comment by bradfordcp** [comment]
No, but I'm going to close this issue given configuring ingresses is outside of the scope of our solution
