### ISSUE TITLE
Add default username/password to login to Grafana dashboard

### ISSUE THREAD

**Issue by Liwanshi** [k8ssandra/k8ssandra#319]
## Bug Report

**Describe the bug**
Credentials to login to Grafana dashboard is missing from https://k8ssandra.io/docs/architecture/monitoring/

**Expected behavior**

Document default username/password to login to Grafana dashboard 

username/password: admin/admin

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-108) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-108
┆Priority: Medium

**Comment by bradfordcp** [comment]
Great point @Liwanshi! It's worth noting with the default credentials of `admin:admin` the user is prompted to set a new password. Have we tested to see if setting new credentials persists? Should we change the defaults?

**Comment by jsanda** [comment]
>Have we tested to see if setting new credentials persists? 

Great question. I will err on the side of caution and say no.

>Should we change the defaults?

Yes we probably should; however, Looking at [kube-prometheus-stack/values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml) I don't see any properties for configuring credentials. 

The grafana chart (on which on think kube-prometheus-stack is based for Grafana integration) does allow you to configure admin credentials. See [here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L280).

**Comment by bradfordcp** [comment]
The grafana chart is a sub-chart of kube-prometheus-stack. If we set `kube-prometheus-stack.grafana.adminUser` it will use that value.

**Comment by johnwfrancis** [comment]
So I'm late to the party here, but there are YAML values for setting the Grafana user/password info and defaults if they're not set. Is this issue still relevant?

**Comment by jsanda** [comment]
Yes there are properties in the kube-prometheus-stack chart for the Grafana admin username/password. I am not a fan though of the password property though. Those properties actually come from the Grafana chart (see [here](https://github.com/grafana/helm-charts/tree/main/charts/grafana)). It supports specifying a secret similar to what we do for other users. See [here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L309).

We can generate a Grafana default username/password like we do for other users.

**Comment by johnsmartco** [comment]
The default credentials are described in https://k8ssandra.io/docs/topics/monitoring/index.html.  However, I will add the same info in https://k8ssandra.io/docs/architecture/monitoring/ as requested by @Liwanshi.
