### ISSUE TITLE
Users are unable to run nodetool commands when Reaper is enabled

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#322]
## Bug Report

**Describe the bug**
Reaper is enabled and deployed by default. Reaper requires remote JMX access to Cassandra. We enable remote JMX access along with JMX authentication. We generate JMX credentials for Reaper. This all works perfectly fine. If I want to run `nodetool` against one of my Cassandra nodes, I now need to supply credentials. This will be very confusing for users. In fact I had one user try to use his C* superuser credentials which is actually a logical thing to try (more on this later).

**To Reproduce**
1. `helm install test k8ssandra/k8ssandra`
2. Wait for cluster to initialize with `kubectl -n wait --for=condition=Ready cassandradatacenter/dc1`
3. Try to run `nodetool` It should fail as follows:

```
$ kubectl exec -it test-dc1-default-sts-0 -c cassandra -- nodetool status
nodetool: Failed to connect to '127.0.0.1:7199' - SecurityException: 'Authentication failed! Credentials required'.
command terminated with exit code 1
```

**Expected behavior**
The user should be able to authenticate with the default superuser credentials. 

We also need to update the docs to explain this behavior.
 
**Environment (please complete the following information):**

* Helm charts version info
0.43.0

**Additional context**

**Comment by jdonenine** [comment]
Plan for 1.0.0 is to generate a set of creds to be used for this.  Follow up enhancement to that solution will come in #323 post-1.0.0
