### ISSUE TITLE
K8SSAND-109 ⁃ Use Cassandra internals for JMX authentication

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#323]
**Is your feature request related to a problem? Please describe.**
See #322 for background. Having to maintain credentials for both Cassandra and for JMX is less than ideal. 

**Describe the solution you'd like**
Cassandra provides a proxy named `AuthenticationProxy` which implements `javax.management.remote.JMXAuthenticator`. It can be configured so that JMX authentication is delegated to Cassandra's authentication subsystem. See the _AUTHENTICATION AND AUTHORIZATION WITH CASSANDRA INTERNALS_  section [here](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/configuration/secureJmxAuthentication.html). 

This provides several benefits including:

* Improved security as we no longer have to maintain JMX credentials on the file system
* Less maintenance since we no longer have to create and maintain JMX users
* Simplifies reaper-operator code as it only needs to know about Cassandra credentials

We won't have to generate the `jmxremote.password` file anymore. Nor will we have to generate JMX credentials and corresponding secret for Reaper.

We will need to add the following Java system properties:

```
JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=true"
JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.remote.login.config=CassandraLogin"'
JVM_OPTS="$JVM_OPTS -Djava.security.auth.login.config=$CASSANDRA_HOME/conf/cassandra-jaas.config"
JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy"
```

We can do this by modifying `cassandra-env.sh` or possibly with environment variables. The latter would be easier. If we have to modify `cassandra-env.sh` the easiest way is probably with an initContainer that runs after the `server-config-init` initContainer in the Cassandra pod.

There is something else that will require some investigation. We need to see if/how we can limit JMX access to specific Cassandra roles. I think it would be a big security hole if arbitrary Cassandra roles could execute things like `nodetool assassinate`.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-109) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-109
┆priority: Medium

**Comment by burmanm** [comment]
There's ability to set roles access to ``MBEANS``, even with ``MBEANS ALL``. Are you suggesting we drop mbeans access from all other accounts? The management-API does not currently have support for modifying the role rights.

**Comment by jsanda** [comment]
>Are you suggesting we drop mbeans access from all other accounts?

Are you referring to the Cassandra roles we create for Medusa, Reaper, and Stargate? If so, we are not creating any corresponding JMX credentials for them. We do create JMX credentials for Reaper, but that is entirely separate from the Cassandra role that we create for Reaper.

>The management-API does not currently have support for modifying the role rights.
Using the CassandraLogin module does mean that the roles we create will have JMX access that they previously did not have. I therefore think we need to limit those roles as much as possible. I think it would be scope creep to try and tackle adding support for specifying permissions via management-api in this ticket. 

If we cannot figure out a relatively easy way to specify the permissions we need, then I would prefer to punt on this until have a solution in place for managing or at least creating permissions. @jdonenine / @bradfordcp is that reasonable?

**Comment by olim7t** [comment]
> There is something else that will require some investigation. We need to see if/how we can limit JMX access to specific Cassandra roles. I think it would be a big security hole if arbitrary Cassandra roles could execute things like `nodetool assassinate`.

Thankfully we don't need to do anything, access is limited by default. I've verified this on a local CCM cluster ; once authorization and remote JMX are enabled, regular roles cannot access the JMX server until explicitly authorized to do so:
```cql
GRANT ALL ON ALL MBEANS TO nonsuper_user;
```
I haven't narrowed it down to the exact privilege(s), but they're off by default.
