### ISSUE TITLE
Website search results do not show original search query

### ISSUE THREAD

**Issue by jeffreyscarpenter** [k8ssandra/k8ssandra#341]
When performing a search on the k8ssandra.io website, the search term is not repeated in the results. 

<img width="1203" alt="Screen Shot 2021-02-06 at 12 32 47 PM" src="https://user-images.githubusercontent.com/12115970/107293630-3fb59400-6a29-11eb-8e32-25a6e4457fa7.png">

Also the search results contain 3rd party ads, don't know if it is possible to remove these.

**Comment by bradfordcp** [comment]
We're using Google's Programmable Search (https://programmablesearchengine.google.com). Removing ads is possible, we just have to set up billing and adjust the configuration.
