### ISSUE TITLE
Upfront validations for k8ssandra config files design and prototyping

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#348]
The primary goals of this issue are:

* Evaluate and prototype potential solutions
* Gather feedback on solutions
* Design and outline future tasks to implement validations incrementally

**Describe the solution you'd like**
An upfront validation of configuration files where lint `rules` can be customized to support k8ssandra specific configurations. The solution provides a way to know when values.yaml files are missing required properties with a clear understanding of the issue.

For example, as part of recent story for{{ jvm-option heap settings}} there is a requirement to support the following property structure when customized.

```java
cassandra:
  # cluster-level settings
  heap:
    # min & max equal
    size: 700M
    newGenSize: 1.4Gi
  # dc specific settings
  dataCenters:
    - name: dc1
      size: 1
      heap:
        size: 600M
        newGenSize: 1.2Gi
    - name: dc2
      size: 1
```

When values are not specified, a heap property exists without any child properties, etc. causes (hard to locate) issues for the user when incorrectly defined.

A `configuration linting tool` will allow for catching customized configuration problems in advance of runtime issues. 

**Describe alternatives you've considered**

* For customized lint rules.  One that stands out is [config-lint](https://pkg.go.dev/github.com/stelligent/config-lint) as it is available as a `CLI` for CI/CD purposes and can be used as a Golang `module` in unit and integration tests.
* A complimentary tool to include coverage of k8s standard checks.  [kubeval](https://www.kubeval.com/) allows for YAML manifest validation against specific versions of API Schemas.  Doesn't support CRDs at this point in time however.

**Additional context**

An example `rule` in config-lint:

```java
version: 1
description: k8ssandra heap settings
type: YAML
files:
  - values.yaml
rules:
  - id: K8SSANDRA_CHART_VALUES_HEAP_SETTINGS
    message: RuleSet for YAML required resources section
    resource: cassandra
    severity: FAILURE
    assertions:
      - key: heap
        op: present
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-113) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.3.0

**Comment by jeffbanks** [comment]
Update for consideration and research as part of this story.

[kube-score](https://kube-score.com/), an object analysis with recommendations for improved reliability and security.

**Comment by jsanda** [comment]
@jeffbanks kube-score looks pretty interesting. Would you be willing to do a prototype and demo?

**Comment by jeffbanks** [comment]
@jsanda yes, I will add this to scope for a future sprint.  I thought this one sounded like it could be a good fit for K8ssandra.
