### ISSUE TITLE
Document Reaper's auto scheduling feature

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#352]
**Is your feature request related to a problem? Please describe.**
We added initial support for auto scheduling in #224 but it is not covered in the docs.

**Describe the solution you'd like**
Provide an explanation of auto scheduling which should include what types of repair schedules will get created when it is enabled.

**Comment by jdonenine** [comment]
This is conceptually covered in the reaper docs via their UI:  http://cassandra-reaper.io/docs/usage/schedule/
