### ISSUE TITLE
Ingress template rendering is broken in <1.19

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra#366]
## Bug Report

**Describe the bug**
Stargate Ingress are using ``pathType`` in their Ingress definition, which breaks deploying Ingress to Kubernetes versions prior 1.19. Disabling Stargate solves this issue.

**To Reproduce**
1. Use Kubernetes <1.1.9
2. Enable ingress
3. ?
4. ** PROFIT **

**Expected behavior**
Ingress should be deployable in all supported versions.

**Additional context**
The following patch should fix the issue, but I don't know if it breaks Stargate:

```patch
diff --git a/charts/k8ssandra/templates/stargate/ingress.yaml b/charts/k8ssandra/templates/stargate/ingress.yaml
index dce6b28..c61ed08 100644
--- a/charts/k8ssandra/templates/stargate/ingress.yaml
+++ b/charts/k8ssandra/templates/stargate/ingress.yaml
@@ -40,7 +40,6 @@ spec:
               servicePort: 8080
   {{- if $traefik.stargate.graphql.playground.enabled }}
           - path: /playground
-            pathType: Exact
             backend:
               serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
               servicePort: 8080
```

Also, tests check that the pathType is there, so I assume there's a reason.

**Comment by jsanda** [comment]
Looks like `PathType` is in 1.18. It is not in 1.17 though.

**Comment by jdonenine** [comment]
Ah, I tested this morning 1.18.15, that's why I didn't see it.

We'll definitely need to look at this was 1.17 is on the target list.
