### ISSUE TITLE
Update reaper dependency to latest 2.2 once available

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#391]
**Describe the solution you'd like**
A new release of Reaper is pending which addresses various different issues - k8ssandra should pickup the latest version.

**Describe alternatives you've considered**
N/A

**Additional context**
Depends on k8ssandra/reapoer-operator issue: https://github.com/k8ssandra/reaper-operator/issues/36

**Comment by burmanm** [comment]
Does not depend on the reaper-operator modifications, we set the version inside the helm chart.
