### ISSUE TITLE
K8ssandra 1.0 Release Notes

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra#410]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
* GitHub-hosted generated Release Notes (RNs). 
* Publish RNs starting with the K8ssandra 1.0 GA release, based on a changelog of significant commits (some subset). 
* TBD for K8ssandra 1.0 (GA) RNs: commits since _when_? 
* Markdown version is desired, with post-generation edits if commit titles were unhelpful. 
* Publish to /docs/content/en/docs/release-notes/_index.md.  We'd account for each version (1.0, 1.1, 2.0, etc) with a ## section within the common RNs file; latest version on top. 

**Describe alternatives you've considered**
n/a
 
**Additional context**
* For cass-operator, the RNs point readers to the GH-generated changelog file (JimD creates), such as: https://github.com/datastax/cass-operator/blob/master/CHANGELOG.md#v151. 
* For DS Luna Streaming (Pulsar), the 1.0 RNs include URLs to commits, see https://github.com/datastax/release-notes/blob/master/Luna_Streaming_1.0_Release_Notes.md. (Mentioned just as an example.)
* Note that while Luna Streaming has its RNs on github.com/datastax/..., along with the DSE RNs, we'd of course want K8ssandra RNs separate from datastax, i.e. on our k8ssandra's GH site.

**Comment by jsanda** [comment]
@bradfordcp have you started on this?

**Comment by bradfordcp** [comment]
Yes. Let me pull that into a separate PR.
