### ISSUE TITLE
Package Jolokia instead of downloading it on the fly when Medusa is enabled

### ISSUE THREAD

**Issue by Oro** [k8ssandra/k8ssandra#465]
**Is your feature request related to a problem? Please describe.**
   IMHO there should be as few external dependencies as possible (e.g. downloads). Enabling Medusa though leads to an Init container that tries downloading jolokia from Maven via `wget -O  /config/jolokia-jvm-1.6.2-agent.jar https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar`

This should not be needed, the only downloads that should happen should be the Docker Images which can be set externally. If there is no internet connection (and all Images are cached//saved locally plus equivalent Configuration for ImagePullPolicy) k8ssandra should still be able to handle new Pods//Disaster events.

**Describe the solution you'd like**
    Bundle the jolokia jar inside the Docker Image(s).

**Describe alternatives you've considered**
    Proxying, overwriting Helm Chart, PV with jolokia pre-packaged, silently ignore wget return code. All are worse workarounds IMHO.

**Additional context**
   I think that this project is the correct one to post it to since the init container is only declared when `medusa.enabled` is in `values.yaml` of the k8ssandra Chart.

**Comment by jsanda** [comment]
Hi @Oro 

Thanks for creating this. I absolutely agree that jolokia should be baked into the image. One of the reasons that it has not been addressed is https://github.com/thelastpickle/cassandra-medusa/pull/237. Once that PR is merged we will get rid of that init  container and configure Medusa to make calls through the management-api.

Feel free though to submit a PR to address the current implementation. I would be happy to review it :)

**Comment by Oro** [comment]
Thanks @jsanda for the quick reply and the link to the PR! I am very happy to wait for that, just knowing that this is already underway makes me feel at ease :)

**Comment by jdonenine** [comment]
This will be addressed via #533 so just going to close this version of things.
