### ISSUE TITLE
Track cass-operator ticket 232, allowing non-IP address additional seeds

### ISSUE THREAD

**Issue by jeromatron** [k8ssandra/k8ssandra#476]
This is meant to track https://github.com/datastax/cass-operator/issues/232 which would make it possible to add additional seeds that aren't IP addresses - things like DNS entries.

**Comment by jdonenine** [comment]
Thanks for getting this in for us @jeromatron , much appreciated!

**Comment by jdonenine** [comment]
Resolved with https://github.com/datastax/cass-operator/pull/399
