### ISSUE TITLE
K8SSAND-125 ⁃ cass-operator: Should CalculateDockerImageRunsAsCassandra function be updated for newer Cassandra versions? #353

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#479]
Tracking issue for cass-operator https://github.com/datastax/cass-operator/issues/353:

### Should CalculateDockerImageRunsAsCassandra function be updated for newer Cassandra versions?
>We recently added support for Cassandra 3.11.8 and 3.11.9 in k8ssandra. It led to this issue k8ssandra/k8ssandra#181.
>
>The CalculateDockerImageRunsAsCassandra function checks specifically for the following versions:
>
>3.11.6
>3.11.7
>4.0.0
>Now that we have management-api images for 3.11.8 and 3.11.8, should this function be updated to be behavior consistent? Without updating the function, users may run into problems like we did in k8ssandra as a result of cass-operator creating a SecurityContext where it was not previously.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-125) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-125
┆priority: Medium

**Comment by jsanda** [comment]
Closing since Cassandra is always configured to run as non-root user now.
