### ISSUE TITLE
medusa: Migrate build/packaging/deployment tooling away from Bintray

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#480]
Tracking issue for the work required within the medusa project to migrate build packaging/deployment tooling with the shutdown to Bintray.

TODO: Update with link to medusa issue.

**Comment by adejanovski** [comment]
PR is up for review: https://github.com/thelastpickle/cassandra-medusa/pull/332

**Comment by adejanovski** [comment]
PR merged.
