### ISSUE TITLE
reaper: Migrate build/packaging/deployment tooling away from Bintray

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#481]
Tracking issue for the work required within the reaper project to migrate build packaging/deployment tooling with the shutdown to Bintray.

TODO: Update with link to reaper issue.

**Comment by adejanovski** [comment]
After searching for alternatives, Cloudsmith is the tool that I retained for replacing Bintray.
The changes are very limited for us and our users:
- we can reuse the existing GPG signing key for the packages
- repos are easy to setup for users with all instructions provided by Cloudsmith
- We have quotas for OSS repos which is higher than what Bintray provided
- It supports debian and rpm packages
- A github action is provided to publish the packages easily

**Comment by adejanovski** [comment]
[This PR](https://github.com/thelastpickle/cassandra-reaper/pulls/1049) successfully pushed the 2.2.4 rpm and deb packages of Reaper to Cloudsmith: https://cloudsmith.io/~thelastpickle/repos/reaper/packages/

**Comment by adejanovski** [comment]
PR is ready to be reviewed: https://github.com/thelastpickle/cassandra-reaper/pull/1049

**Comment by adejanovski** [comment]
Thanks for the review @jdonenine 🙏 

Merged!
