### ISSUE TITLE
medusa: Update branding references

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#482]
Tracking issue for the work required within the reaper project to update branding references to use the preferred name "Medusa for Apache Cassandra".

Split into two phases.

* Phase I includes rebranding of the Medusa documentation (this issue).
* Phase II #528 - repository migration

**Comment by emerkle826** [comment]
I have an initial PR here:
https://github.com/thelastpickle/cassandra-medusa/pull/309
And also changes to the Wiki here:
https://github.com/emerkle826/cassandra-medusa-wiki/commit/4e7c2a14f4200c3a0439064e6a0408e918c5eb2c

**Comment by adejanovski** [comment]
PR with the rebranding and shutting down the wiki was merged: https://github.com/thelastpickle/cassandra-medusa/pull/317
