### ISSUE TITLE
K8SSAND-126 ⁃ Add support for allocate_tokens_for_keyspace with Cassandra 3.11.x

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#490]
**Is your feature request related to a problem? Please describe.**
For Cassandra 3.11.x we default `num_tokens` to 256. We were going to use `allocate_tokens_for_keyspace` but cass-config-builder does not have support for it. See #324 for details

**Describe the solution you'd like**
We should update cass-config-builder and cass-config-definitions to add support for `allocate_tokens_for_keyspace`. We could then use a default of 16 tokens for 3.11.x as we do for 4.0. This would make upgrading to 4.0 easier.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-126) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-126
┆priority: Medium

**Comment by adejanovski** [comment]
Closing as won't do
