### ISSUE TITLE
Tracking Reaper #1027: datacenterAvailability: EACH might be broken with useAddressTranslator: true

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#492]
Tracking issue for Reaper issue https://github.com/thelastpickle/cassandra-reaper/issues/1028

### datacenterAvailability: EACH might be broken with useAddressTranslator: true
>I have inherited a cluster and am trying to get Reaper 2.2.1 working, and it seems to be completely unable to start any repairs. Depending on how it's started, either the repair job never appears as running, or every segment is stuck in NOT_STARTED forever.
>
>According to the log, segments keep getting postponed because metrics are unavailable. Also according to the logs, it keeps trying (and failing) to connect to JMX endpoints that are in other datacenters, which doesn't work. I think it shouldn't attempt to do that with datacenterAvailability: EACH, but maybe useAddressTranslator: true is confusing the reachability check?
>
>Starting a new repair job (that isn't already existing and in running state) also fails with a JMX error, from trying to connect to a node it shouldn't connect to.
>
>It's entirely possible I'm using it wrong, I have no previous experience with the reaper, but I feel like I've checked all the obvious things and at this point it seems like a bug.

**Comment by adejanovski** [comment]
[PR is available for review](https://github.com/thelastpickle/cassandra-reaper/pull/1029) which @jsanda will pick up.
Two users that were experiencing the bug tested the patch and [provided positive feedback](https://github.com/thelastpickle/cassandra-reaper/pull/1029#issuecomment-790799638) that repairs were working smoothly.
