### ISSUE TITLE
Tracking Medusa: s3_compatible storage and region parameter #301

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#495]
Tracking issue for Medusa issue https://github.com/thelastpickle/cassandra-medusa/issues/301

### s3_compatible storage and region parameter

>The new version 0.9.0 support s3_compatible storage, this is a good new.
However, I can't figure out how to configure it correctly to upload to a s3 compatible endpoint (for example, I use OVHcloud s3 object storage API).
>
>It looks like the region parameter is not passed to libcloud/minio driver.
>
>If I edit my installed libcloud/storage/drivers/minio.py to hardcode region_name = "gra" as indicated in #272 (comment) + apache/libcloud#1539 (comment), everything is working, I can backup/list etc
>
>My configuration:
>
>[storage]
storage_provider = s3_compatible
host = s3.gra.cloud.ovh.net
bucket_name = mybucket
region = gra
key_file = /etc/medusa/credentials-s3
>
>Am I missing something ? Also, the wiki does not document the new s3_compatible feature :)
>
>Thank you !

**Comment by adejanovski** [comment]
The PR was merged and Medusa 0.9.1 was released.
