### ISSUE TITLE
Tracking cass-operator: Upgrade operator SDK

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#496]
Tracking issue for cass-operator issue related to upgrading the operator SDK: TBD

cass-operator ticket - https://github.com/datastax/cass-operator/issues/395

Multiple aspects (split into two issues):
* Upgrade the APIs used
* Refactor code to reflect the structure common to the later versions of the operator SDK

**Comment by burmanm** [comment]
I'm working on this from two fronts, one to update to newest old-layout: 0.18.2 and one to update beyond it to the newest one. The first one should help with latter one (finding some bugs).
