### ISSUE TITLE
Add underling ops info involved with adding/removing nodes

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra#501]
**Is your feature request related to a problem? Please describe.**
Users may need more info about "underlying operations that are involved with adding/removing nodes," as @jsanda noted in a comment on the provisioning topic.

**Describe the solution you'd like**
Get info from John Sanda, Jeff DiNoto @jdonenine, and others on the team so we can describe the scenarios.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by jsanda** [comment]
@johnsmartco sorry this fell off my radar. I will put together a summary of the steps involved.

**Comment by jdonenine** [comment]
What failure scenarios should we consider here as well to give folks guidance for?

**Comment by jsanda** [comment]
Here are a few suggestions:

* Corrupt disk (mentioned by @adejanovski)
* Cassandra pod repeatedly gets OOM killed
    * Note I am not referring to a Java OutOfMemoryError. I am referring to a scenario in which the pod is terminated because the k8s worker node does not have sufficient memory for all of the pods running on it.
* Running out of disk space on data volume  

Each of these probably deserves separate tickets.

**Comment by johnsmartco** [comment]
Info provided by @jsanda ; I'm adding content to the Scaling topic, https://github.com/k8ssandra/k8ssandra/blob/main/docs/content/en/docs/topics/provision-a-cluster/_index.md
