### ISSUE TITLE
K8SSAND-71 ⁃ Add support for scheduled backups

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#521]
**Is your feature request related to a problem? Please describe.**
k8ssandra does not yet provide anything for scheduled backups. Users can work around this today with a CronJob but k8ssandra handle this directly.

**Describe the solution you'd like**
An easy option is to use CronJobs. A more lightweight approach might be to build a scheduler into medusa-operator. CassKop took the latter approach. 

**Additional context**
For now this is just a place holder. We should come back and add design details.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-71) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-71
┆priority: Medium

**Comment by vcanuel** [comment]
This feature would be great.
Meanwhile, a CronJob example could be a great start :)

**Comment by jsanda** [comment]
@jnavascues take a look at #518 for possible short term solution.
