### ISSUE TITLE
Golang standards for k8ssandra

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#539]
**Requested**
A published document for developers to understand what `Go standards` are expected as part of `k8ssandra` PRs and code reviews.

**Additional context**
An [effective Go site](https://golang.org/doc/effective_go) exists that can be referenced for consideration on building the k8ssandra standards.

**Comment by jsanda** [comment]
Are [effective Go](https://golang.org/doc/effective_go) and [Helm Best Practices](https://helm.sh/docs/chart_best_practices/) sufficient for now?

**Comment by jeffbanks** [comment]
I am good with those two to reference as we review.  

I'll post in Slack to be sure the rest of the folks are onboard.

**Comment by jeffbanks** [comment]
Submitting poll to get feedback from core K8ssandra team.

**Comment by jeffbanks** [comment]
Poll results, majority of the team is in favor of referencing the two sources for reviews, so we will move forward in that direction.

There was some discussion of `Go supported tools` available for automation and may be considered in the future to assist with identifying policy enforcement at `compile` time and/or at CI time.  This would be in addition to some level of manual PR review.  

The thought is that if the tools exists, and can be aligned with the aforementioned standards, catching issues prior to a PR push could be useful for efficiency.
