### ISSUE TITLE
Plan and propose a version and branching strategy for future use

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#549]
**Describe the solution you'd like**
A clear version and branching strategy is needed for the project as it grows.  We need to consider the ways that developers should work within the project as well as its implications of our release channels and chart versioning.  The outcome of this request is to have a proposed plan that is discussed and agreed upon amongst the team.

**Comment by adejanovski** [comment]
This is done and will be publicly documented as part of #550
