### ISSUE TITLE
K8SSAND-63 ⁃ Document agreed upon version and branching strategy for developers

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#550]
**Describe the solution you'd like**
Provide developer/contributor focused documentation related to the version and branching strategy discussed via #549 .  This would reside in the repo and may be translated in some parts up to the project website documentation in a later pass.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-63) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-63
┆priority: Medium

**Comment by bradfordcp** [comment]
Isn't this done? @adejanovski

**Comment by jsanda** [comment]
yup, it's done.
