### ISSUE TITLE
Fix Medusa remote restore issues with client encryption

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#562]
Placeholder for Medusa#241

If client encryption is enabled, the driver will connect through port 9142 by default which Medusa doesn't check. We need to seamlessly check both the native port and the native ssl port to see if any of them is listening, otherwise non seed nodes will never see seed nodes running. I guess we could double down here and also check the gossip ports (with and without encryption) as the native port may not be opened between nodes, but the gossip one surely is.

[This bug](https://sonarcloud.io/organizations/thelastpickle/issues?open=AXhKCJEz9R4aUTPlxqHp&resolved=false&types=BUG) should be fixed in the process. It is the probable reason why we didn't catch this issue in the first place.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-61) by [Unito](https://www.unito.io)

**Comment by jeffbanks** [comment]
System testing scheduled to start 4/2.

**Comment by adejanovski** [comment]
New errors have popped up with the latest changes: 
![Capture d’écran 2021-04-07 à 18 30 49](https://user-images.githubusercontent.com/5096002/113998391-50339080-9859-11eb-95a9-43e64608b6f1.png)

The release version check will fail if Cassandra is down as we have no driver connection. We need to find a reliable way of checking this, by either storing the release version each time we successfully connect to the cluster instead of when we need it, or maybe adding an optional setting to specify the version (which would default to 3.11).

**Comment by jeffbanks** [comment]
Updated with efforts as part of [this PR](https://github.com/thelastpickle/cassandra-medusa/pull/344) in Medusa.
PR is set for final review.

**Comment by jeffbanks** [comment]
Updated:

- Rebased with fix for code coverage issue discovered during CI builds.
- Added unit test coverage to detect `Host` being passed in as string during initial c* health checks.

**Comment by jeffbanks** [comment]
Since CodeCov was added as part of a recent rebase, the tests added as part of this change are all passing, however, the overall project quality gate isn't achieved.  I am planning to add additional test coverage as part of this effort to support the overall code coverage checks.

**Comment by jeffbanks** [comment]
@adejanovski @jdonenine  

For this one, `Codecov patch` increased:  93.45% of diff hit (target 70.55%).
[Latest report here](https://github.com/thelastpickle/cassandra-medusa/pull/344/checks?check_run_id=2580252284)

Also, one remaining error exists with Codecov for the `project coverage` overall.  These appear to be from changes pulled in from a rebase.  

Codecov for project after re-based with branch, showing:
[Latest report here](https://github.com/thelastpickle/cassandra-medusa/pull/344/checks?check_run_id=2580252283)

Remaining:
Determine if we want to pursue this `project coverage` as part of this PR specifically.  There is a long way to go IMO.
Run system test of the PR branch to finalize as a system test before we merge.  I was unable to get that setup for my AWS.

**Comment by jeffbanks** [comment]
Tracking additional work to be targeted in upcoming sprints.

- We should avoid parsing nodetool outputs, they're fairly unreliable and we won't be able to use them in the context of k8ssandra.
- Get the release version from the driver in this block and save it as a member of the RestoreJob class
- Allow to set/override it with a command line argument here and here.
- Pass it to the restore-node command as a new argument here.
- If not passed, default to 3.11 in restore_node.py (folks can call medusa restore-node directly).
