### ISSUE TITLE
Tracking reaper: Make Reaper support JDK11 #1039

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#563]
Tracking issue for cassandra-reaper: https://github.com/thelastpickle/cassandra-reaper/issues/1039

Reaper only supports jdk8, which will become problematic with the C* 4.0 release which will support jdk11.

We must make the necessary changes to support both jdk8 and jdk11 in Reaper.

This is also blocking SonarCloud analysis.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-60) by [Unito](https://www.unito.io)

**Comment by burmanm** [comment]
Here's some of the work that blocked me at least previously:

https://github.com/burmanm/cassandra-reaper/tree/jdk11

Includes some maven updates, dependency updates, copying JAXB code to avoid that dependency etc

**Comment by jdonenine** [comment]
This is now properly tracked in https://github.com/thelastpickle/cassandra-reaper/issues/1085
