### ISSUE TITLE
What would be appropriate approach to expose Grafana/reaper/cqlsh/Prometheus to be accessible remotely?

### ISSUE THREAD

**Issue by navjyotnishant** [k8ssandra/k8ssandra#568]
**Type of question**
How to perform a particular operation

**What did you do?**
Would like to access dashboards remotely.
Is changing service "TYPE" from `ClusterIP `to `NodePort `a appropriate way or something else should be used?
 I am able to achieve my goal with "Nodeport" changes. Just looking for standards.

**Did you expect to see some different?**
NA

**Environment**
DEV

* Helm charts version
`k8ssandra-1.0.0`

**Comment by jsanda** [comment]
Hi @navjyotnishant 

You might want have a look at setting up ingress. Start here in the docs https://k8ssandra.io/docs/topics/ingress/.

**Comment by navjyotnishant** [comment]
@jsanda - 

- port-mapping isn't reliable and connection gets killed/timeout after some time of inactivity. I have found even port-forward background jobs killed automatically after sometime. (have to have a continuous ping to keep connection alive) so have switched to Service type "NodePort"
- I am new to Traefik, can it provide stable connection on exposed port? If you can share a bit detailed doc that would be much helpful.

**Comment by jsanda** [comment]
kubectl port-forward is fine for local development/testing but not intended for production use. It uses tunneling and as you noted can time out with idle connections. It also requires an authenticated k8s user with access to the api server. Lastly you need to do run a separate port-forward for each internal service you want to access.

None of the above apply with ingress with make it much better suited for production use. There is no tunneling involved so you won't hit the connection timeouts.

https://k8ssandra.io has a good bit of info on ingress. Go through that and come back with any specific questions.

Good luck!

**Comment by jsanda** [comment]
Hi @navjyotnishant 

I am going to close this issue. If your questions have not been fully answered, please feel free to reopen it!
