### ISSUE TITLE
medusa container does not handle SIGTERM signal

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#570]
## Bug Report

**Describe the bug**
When a pod is deleted, the kubelet will send each of the containers in the pod the SIGTERM signal. The Cassandra pod is configured with a termination grace period of two minutes. This is the amount of time that the containers have to gracefully shutdown. After the grace period is up, the kubelet will forcefully terminate the containers. 

While developing/testing backup/restore I have always noticed that the pod restarts are really, really slow. Over the past couple days I have been doing some investigation and discovered that the `medusa` container is not handling the SIGTERM signal. As a result, it takes two minutes for the pod to be deleted.

This is pretty bad for rolling restart situations as it will take at least `2 min * N` (where `N` is the cluster size) for the rolling restart to complete.

**To Reproduce**
1. Install k8ssandra with backup/restore enabled
2. Wait for the Cassandra pods to become ready
3. Exec into the `medusa` container with `kubectl exec -it <cassandra-pod> -c medusa -- /bin/bash`
4. List the running processes with `ps -x`. `python3 -m medusa.service.grpc.server server.py` should be PID 1.
5. Send the SIGTERM signal with `kill -SIGTERM 1`.
6. List the processes again. `server.py` is still running.

**Expected behavior**
`python3 -m medusa.service.grpc.server server.py` should terminate when it receives the SIGTERM signal which will cause the container to terminate and thus allow the pod deletion to complete more quickly.

**Environment (please complete the following information):**

* Helm charts version info
1.0.0

**Additional context**
There is a question of what we should do if a backup or restore operation is in progress. These could be long running operations that could easily take several minutes or even hours. Fortunately I do not think we need to worry about those scenarios here. We can use finalizers with the CassandraBackup and CassandraRestore objects to allow operations to complete before deletion can proceed.

We have a similar problem with the `server-system-logger` container. See #571.

**Comment by jsanda** [comment]
Here is the PR with the fix https://github.com/thelastpickle/cassandra-medusa/pull/313.

**Comment by adejanovski** [comment]
@jsanda, can we close this ticket now? The fix was released in Medusa 0.10 which was part of K8ssandra 1.1.0.
