### ISSUE TITLE
what License is k8ssandra under?

### ISSUE THREAD

**Issue by tseelbach** [k8ssandra/k8ssandra#574]
I looked in FAQ, Doc (skimmed) and 3rd party license page, but did not find what license applies to K8ssandra itself.  Is this documented somewhere and i've missed it?   Should be just one click from the homepage.
Thanks!  
Tom Seelbach

**Comment by bradfordcp** [comment]
I wonder if it's currently not listed on the website.

In the repository's root there is a [`LICENSE` file](https://github.com/k8ssandra/k8ssandra/blob/main/LICENSE) which contains the Apache 2.0 license.
