### ISSUE TITLE
Resolve Grafana namespace issues

### ISSUE THREAD

**Issue by jakerobb** [k8ssandra/k8ssandra#58]
## Bug Report

**Describe the bug**

We have multiple bug reports open with grafana-operator: 
https://github.com/integr8ly/grafana-operator/issues/303
https://github.com/integr8ly/grafana-operator/issues/304
https://github.com/integr8ly/grafana-operator/issues/305
https://github.com/integr8ly/grafana-operator/issues/306

These bugs combine to make it so that if you install k8ssandra-cluster in a namespace other than the one in which you installed k8ssandra, Grafana will not have a datasource and so the dashboards will not function. Furthermore, you cannot install multiple clusters into the same namespace.

**To Reproduce**
```lang-sh
helm install k8ssandra k8ssandra
helm install cluster1 k8ssandra-cluster -n cluster1 --create-namespace
helm install cluster2 k8ssandra-cluster -n cluster2 --create-namespace
```

**Expected behavior**
There should be Grafana instances created in both namespaces (cluster1 and cluster2). Each should:
1. have a datasource configured to point to Prometheus
2. have copies of the three dashboards (overview, condensed, and system)
3. show data from their respective clusters

**Solution**
Until the listed issues are resolved, in order to play nice with multiple clusters deployed to the same Kubernetes, we need to have a single Grafana instance with a single DataSource and a single set of Dashboards, and they all need to be in the same namespace as the operator.

**Comment by jsanda** [comment]
I added this [FAQ](https://k8ssandra.io/docs/faqs/#can-i-install-multiple-releases-of-k8ssandra-cluster) about this.

**Comment by jakerobb** [comment]
If I understand everything correctly, @jsanda fixed this pre-KubeCon, but by going in the other direction -- rather than have a single copy of Grafana/DataSource/Dashboards in the operator namespace, we instead create one of each of those in the cluster namespace. 

I'm closing this issue.
