### ISSUE TITLE
Refactor the Reaper ITs to use the Reaper go client

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#580]
The first iteration on integration tests used Resty to interact with Reaper. 
It would be good to augment the Reaper Go client with the missing operations and use it instead of Resty in the k8ssandra ITs.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-56) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
There are currently 3 Resty calls that could be replaced:

### Create a repair run
```
	response, err := restClient.R().
		SetHeader("Content-Type", "application/json").
		SetQueryParams(map[string]string{
			"clusterName":  "k8ssandra",
			"keyspace":     keyspace,
			"owner":        "k8ssandra",
			"segmentCount": "5",
		}).
		Post("http://repair.127.0.0.1.nip.io:8080/repair_run")
```
From all the possible optional parameters, only `segmentCount` is used. Speaking of which, `segmentCount` is not the right name, it's `segmentCountPerNode` in recent versions of Reaper. This parameter is probably being ignored.

### Abort a repair run
```
	response, err := restClient.R().
		SetHeader("Content-Type", "application/json").
		Put(fmt.Sprintf("http://repair.127.0.0.1.nip.io:8080/repair_run/%s/state/ABORTED", repairId))
```

### Get repair run segments
```
	response, err := restClient.R().Get(fmt.Sprintf("http://repair.127.0.0.1.nip.io:8080/repair_run/%s/segments", repairId))
```

**Comment by adutra** [comment]
Darn, the switch to `segmentCountPerNode` is very recent, see https://github.com/thelastpickle/cassandra-reaper/commit/9a3d11005b1f9991e51da5ee040a0ccae603c86a.

I think it would be wise to support both in the client.
