### ISSUE TITLE
There is a race condition that can cause backup operations to be scheduled twice

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#592]
## Bug Report

**Describe the bug**
The `CassandraBackup.Status` is of the type `CassandraBackupStatus` which is defined as follows:

```go
type CassandraBackupStatus struct {
	CassdcTemplateSpec CassandraDatacenterTemplateSpec `json:"cassdcTemplateSpec"`

	StartTime metav1.Time `json:"startTime,omitempty"`

	FinishTime metav1.Time `json:"finishTime,omitempty"`

	InProgress []string `json:"inProgress,omitempty"`

	Finished []string `json:"finished,omitempty"`

	Failed []string `json:"failed,omitempty"`
}
```
Before making any gRPC calls to the `medusa` containers medusa-operator sets the `StartTime` and `InProgress` properties. All of the pods' hostnames are added to `InProgress`. The status is updated on the api server via a patch request. Next medusa-operator makes the gRPC backup requests in a fire and forget fashion. It wraps the call to each `medusa` container in a separate goroutine. That ends the reconciliation request.

At the start of reconciliation, medusa-operator checks to see if the `StartTIme` and `InProgress` properties are set as a way to determine if backups are already in progress. If backups are already in progress, reconciliation ends early.

The k8s client medusa uses does not read directly from the api server. It reads from a cache that is periodically updated. Writes however go directly to the api server. Note that this is the most common type of client used. 

I added some logging in my local repo to confirm what I thought what was happening. Here are the logs:

**1** `2021-03-26T01:33:38.647Z**        INFO    controllers.CassandraBackup     starting reconciliation {"ResourceVersion": "8532427", "StartTime": "0001-01-01 00:00:00 +0000 UTC", "InProgress": []}`
**2** `2021-03-26T01:33:39.012Z        INFO    controllers.CassandraBackup     starting backup {"ResourceVersion": "8532432", "StartTime": "2021-03-26 01:33:38 +0000 UTC", "InProgress": ["test-dc2-default-sts-0", "test-dc2-default-sts-1", "test-dc2-default-sts-2"]}`
**3** `2021-03-26T01:33:39.012Z        INFO    controllers.CassandraBackup     finished reconciliation`
**4** `2021-03-26T01:33:39.012Z        INFO    controllers.CassandraBackup     starting backup {"CassandraPod": "test-dc2-default-sts-1"}`
**5** `2021-03-26T01:33:39.012Z        INFO    controllers.CassandraBackup     starting reconciliation {"ResourceVersion": "8532430", "StartTime": "0001-01-01 00:00:00 +0000 UTC", "InProgress": []}`
**6** `2021-03-26T01:33:39.013Z        INFO    controllers.CassandraBackup     starting backup {"CassandraPod": "test-dc2-default-sts-2"}`
**7** `2021-03-26T01:33:39.013Z        INFO    controllers.CassandraBackup     starting backup {"CassandraPod": "test-dc2-default-sts-0"}`
**8** `2021-03-26T01:33:39.046Z        INFO    controllers.CassandraBackup     starting backup {"ResourceVersion": "8532433", "StartTime": "2021-03-26 01:33:39 +0000 UTC", "InProgress": ["test-dc2-default-sts-0", "test-dc2-default-sts-1", "test-dc2-default-sts-2", "test-dc2-default-sts-2", "test-dc2-default-sts-0", "test-dc2-default-sts-1"]}`
**9** `2021-03-26T01:33:39.047Z        INFO    controllers.CassandraBackup     finished reconciliation`
**10** `2021-03-26T01:33:39.047Z        INFO    controllers.CassandraBackup     starting backup {"CassandraPod": "test-dc2-default-sts-0"}`

The `starting reconciliation` statements at line 1 logs the `StartTime` and `InProgress` properties. They have their default values with the first statement as expected. At line 2 we have message logged from the goroutine that makes the gRPC call to medusa. Line 3 is logged at the end of the reconciliation. At line 4 we have another message logged from another goroutine. All good so far.

At line 5 the next reconciliation request start. `StartTime` and `InProgress` still have their default values even though they were updated previously! This is bad because medusa-operator will now proceed to start the backup operations again. Lines 7 and 10 reveal this happening.

Why did this happen? The client cache wasn't up to date. This is standard operating procedure with controllers. Kubernetes uses optimistic concurrency control and will prevent an older version of an object overwriting a newer version. The problem here is that we are not dealing with a k8s object. Technically we are dealing with one - the `medusa` container. There is nothing in a pod or container status that would indicate a backup operation is in progress. (The astute reader may be wondering why this isn't implemented with a k8s job. I am happy to discuss that in a follow up comment.)

One option to fix this might be to use a client that reads directly from the api server. I would prefer that not to be the first option we explore. The cache based clients are widely used (even with Kubernetes itself) in an effort to reduce load on the api server.

Another option might be do some additional polling. medusa-operator creates the goroutines to start the gRPC calls and then ends the reconciliation. Before ending reconciliation medusa-operator could call the `GetBackups` gRPC method in the main goroutine to verify that the backups are in progress. At the start of reconciliation medusa-operator could also call `GetBackups`. The `GetBackups` method returns both finished and in progress backups. 

I think the additional polling approach works for the happy path. I need to think more about different failure scenarios. In general though with failure scenarios for backups, I think we need to do a couple things:

* Detect that one or more of backup operations failed
* Record and indicate that the back operation failed so that the user knows and so that medusa-operator knows

**To Reproduce**

**Expected behavior**
There should be no duplicate backup operation kicked off for a given CassandraBackup object

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
1.0.0

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 

* Kubernetes version information:

`kubectl version`

* Kubernetes cluster kind:

**Additional context**

**Comment by burmanm** [comment]
I was able to fix this with just using optimisticLocking writing. When we receive a new backup object, we write the InProgress state with OptimisticLocking. If the state was already set, it means we're updating a stale object -> we get an error (the error message itself says the object we try to update is stale - but I haven't found yet if this is a typed error somewhere) and thus we know we should simply requeue and next time probably the cache has been updated.

With some other api server call reductions, there's no increase in the amount of calls made by medusa-operator.

**Comment by burmanm** [comment]
Also, this same bug exists in the restore process as well.

**Comment by jsanda** [comment]
@burmanm nice work! I had been working under the assumption that the `Patch` function used optimistic locking by default. Your code changes along with comment https://github.com/kubernetes-sigs/controller-runtime/issues/736#issuecomment-571342852 confirm that my assumptions were incorrect.
