### ISSUE TITLE
Integration tests should only be triggered for changes in the `charts/` directory

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#604]
**Is your feature request related to a problem? Please describe.**
While making edits to the documentation site I had to wait for integration tests to pass before merging a PR.

**Describe the solution you'd like**
Changes under `/docs` should not require integration tests to run.

**Describe alternatives you've considered**
Merging before the tests finish, but that seems like poor form.

**Comment by jsanda** [comment]
Actually, I think tests should be triggered for changes in any of the following directories:

* charts/
* tests/integration
* pkg/
* cmd/
