### ISSUE TITLE
Be able to set the affinity for Stargate pods so that it will not share workers with C* pods

### ISSUE THREAD

**Issue by tlasica** [k8ssandra/k8ssandra#617]
**Is your feature request related to a problem? Please describe.**
When I try to create a cluster with 3 C* pods and 1 * Stargate pod
Even when I use 4 k8s worker nodes
I get Stargate pod placed on same worker as one of the C* pods.

**Describe the solution you'd like**
Specify affinity for Stargate pods so that they are placed on separate workers from C* pods.
If there is not enough workers fail badly.

**Describe alternatives you've considered**
Nothing came to my mind

**Additional context**
Performance testing in which we would like to keep C* and Stargate on separate workers.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-47) by [Unito](https://www.unito.io)
┆Epic: Pod Scheduling Control
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
Hi @tlasica 

Just wanted to let you know that wrapping up sprint 5 and we will tackle this in sprint 6. #740 added support for tolerations and that should be sufficient for making sure Stargate pods don't get scheduled onto the same worker node where C* pods are running.

We could simply expose affinity like we did tolerations. I want to take a little time to think about it to see if we should try provide something more consistent with what cass-operator does.

**Comment by mparikhcloudbeds** [comment]
If I may, IMHO, since stargate should scale independently, anffinity setup would help.
