### ISSUE TITLE
K8SSAND-46 ⁃ Stargate nodes need to bootstrap serially 

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#625]
## Bug Report

**Describe the bug**
This is a follow up to #612. As adejanovski mentioned in #612 if multiple Stargate nodes are deployed they need to bootstrap one at a time just like Cassandra nodes; otherwise, we can wind up with errors similar to the ones reported in #612.

**To Reproduce**
See #612 for steps to reproduce. The only difference here is you want to install multiple Stargate nodes.

**Expected behavior**
Stargate nodes should bootstrap serially. To accomplish this, we should use a StatefulSet instead of a Deployment. 

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
1.0.0
* Helm charts user-supplied values
* Kubernetes version information:
* Kubernetes cluster kind:

**Additional context**

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-46) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-46
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/625?planning-poker) with ZenHub @adejanovski @adutra @jeffbanks @jsanda

**Comment by adejanovski** [comment]
@bradfordcp, as 1.x is in maintenance only mode, don't you think we may want to close this as "won't do"?

**Comment by jsanda** [comment]
Closing since this is already done in k8ssandra-operator.
