### ISSUE TITLE
K8SSAND-42 ⁃ Medusa - security update to PROTOCOL_TLSv1_2

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#652]
## Bug Report
Error reported for `Python SCA checks` related to [RSPEC-4423](https://rules.sonarsource.com/python/type/Vulnerability/RSPEC-4423).

**Describe the bug**
Tracking Medusa repository [issue](https://github.com/thelastpickle/cassandra-medusa/issues/328) opened.

adejanovski I wanted to get your thoughts on what is involved for this one if upgraded to v1_2?

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-42) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-42
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/652?planning-poker) with ZenHub @adejanovski @jeffbanks

**Comment by adejanovski** [comment]
We've already fixed this by using `PROTOCOL_TLS` instead of `PROTOCOL_TLSv1`.
`PROTOCOL_TLSv1_2` wasn't suitable for communicating with Cassandra.
I'll close the ticket.
