### ISSUE TITLE
K8SSAND-41 ⁃ The data_endpoint_auth Stargate keyspace should be altered to have a proper RF

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#659]
The data_endpoint_auth keyspace is created by Stargate using SimpleStrategy and RF=1.
We'd need to disable the auto creation and handle this in an init container or a job to match the topology of our cluster. That includes multi DC when we start supporting it.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-41) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-41
┆priority: Medium

**Comment by jsanda** [comment]
Closing since this is addressed in k8ssandra-operator.
