### ISSUE TITLE
Rack support doesn't seem to work

### ISSUE THREAD

**Issue by steve-todorov** [k8ssandra/k8ssandra#663]
## Bug Report

**Describe the bug**

I've been trying to get rack support working properly for a few hours now without any luck. It looks like it's not working as expected for some reason and I'm unsure if this is a bug or simply not implemented yet.

**To Reproduce**

1. Clone repo and switch to version `1.1`
2. Download and apply [changes.diff.txt](https://github.com/k8ssandra/k8ssandra/files/6297992/changes.diff.txt)
3. `make -f Makefile create-kind-cluster`
4.  ```
     $ helm install rack-test ./charts/k8ssandra --create-namespace --namespace=k8ssandra --values ./tests/integration/charts/cluster_rack.yaml

     W0412 18:13:12.997086 2454940 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
     W0412 18:13:13.829987 2454940 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
     W0412 18:13:13.853653 2454940 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
     W0412 18:13:13.879877 2454940 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
     NAME: rack-test
     LAST DEPLOYED: Mon Apr 12 18:13:15 2021
     NAMESPACE: k8ssandra
     STATUS: deployed
     REVISION: 1
     ```

5. `watch -n 2 -- kubectl get pods --namespace=k8ssandra`
6. `kubectl get events --watch --namespace=k8ssandra`

**Expected behavior**

Cassandra nodes should start when configured using rack / availability zones.

**Screenshots And Logs**

* `$ watch -n 2 -- kubectl get pods --namespace=k8ssandra`
    ```
    Every 2,0s: kubectl get pods --namespace=k8ssandra             Mon Apr 12 18:34:22 2021

    NAME                                                  READY   STATUS    RESTARTS   AGE
    prometheus-rack-test-kube-prometheus-prometheus-0     2/2     Running   1          9m3s
    rack-test-cass-operator-57db9d99db-ncc99              1/1     Running   0          9m19s
    rack-test-dc1-n1-sts-0                                0/1     Running   0          8m52s
    rack-test-dc1-n2-sts-0                                0/1     Running   0          8m52s
    rack-test-dc1-n4-sts-0                                0/1     Running   0          8m52s
    rack-test-dc1-stargate-86bf859647-c4xq2               0/1     Running   3          9m19s
    rack-test-grafana-f7589786b-7kssl                     2/2     Running   0          9m19s
    rack-test-kube-prometheus-operator-5c67ddd4b6-2b5gz   1/1     Running   0          9m19s
    rack-test-reaper-operator-679bf48fd5-b9dtl            1/1     Running   0          9m19s
    ```

* `$ kubectl get events --namespace=k8ssandra --watch` (too long to insert, check attached file [k8s-events.log](https://github.com/k8ssandra/k8ssandra/files/6297903/k8s-events.log))

* `$ kubectl logs --namespace=k8ssandra pod/rack-test-dc1-n1-sts-0 -c cassandra`  (full log attached as 
[cassandra.log](https://github.com/k8ssandra/k8ssandra/files/6297969/cassandra.log))
   ```
    INFO  [main] 2021-04-12 15:27:53,114 IPCController.java:105 - Starting Server
    INFO  [main] 2021-04-12 15:27:53,123 IPCController.java:114 - Started Server
    Started service on file:///tmp/oss-mgmt.sock
    INFO  [nioEventLoopGroup-3-1] 2021-04-12 15:28:02,129 DefaultMavenCoordinates.java:37 - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.10.0
    INFO  [epollEventLoopGroup-5-1] 2021-04-12 15:28:02,749 Clock.java:47 - Using native clock for microsecond precision
    WARN  [epollEventLoopGroup-5-2] 2021-04-12 15:28:02,787 AbstractBootstrap.java:452 - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x240f270c]'
    WARN  [epollEventLoopGroup-5-2] 2021-04-12 15:28:02,866 Loggers.java:39 - [s0] Error connecting to Node(endPoint=/tmp/cassandra.sock, hostId=null, hashCode=26ced054), trying next node (FileNotFoundException: null)
    INFO  [nioEventLoopGroup-2-2] 2021-04-12 15:28:02,929 Cli.java:617 - address=/10.244.3.2:42844 url=/api/v0/metadata/endpoints status=500 Internal Server Error
    INFO  [epollEventLoopGroup-6-1] 2021-04-12 15:28:16,349 Clock.java:47 - Using native clock for microsecond precision
    WARN  [epollEventLoopGroup-6-2] 2021-04-12 15:28:16,351 AbstractBootstrap.java:452 - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x239486bb]'
    WARN  [epollEventLoopGroup-6-2] 2021-04-12 15:28:16,355 Loggers.java:39 - [s1] Error connecting to Node(endPoint=/tmp/cassandra.sock, hostId=null, hashCode=4246a032), trying next node (FileNotFoundException: null)
    INFO  [nioEventLoopGroup-2-1] 2021-04-12 15:28:16,358 Cli.java:617 - address=/10.244.1.1:45612 url=/api/v0/probes/readiness status=500 Internal Server Error
    INFO  [nioEventLoopGroup-2-2] 2021-04-12 15:28:18,224 Cli.java:617 - address=/10.244.1.1:45634 url=/api/v0/probes/liveness status=200 OK
    INFO  [epollEventLoopGroup-7-1] 2021-04-12 15:28:26,363 Clock.java:47 - Using native clock for microsecond precision
    WARN  [epollEventLoopGroup-7-2] 2021-04-12 15:28:26,365 AbstractBootstrap.java:452 - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x7ba8050c]'
    WARN  [epollEventLoopGroup-7-2] 2021-04-12 15:28:26,370 Loggers.java:39 - [s2] Error connecting to Node(endPoint=/tmp/cassandra.sock, hostId=null, hashCode=2a6ad53), trying next node (FileNotFoundException: null)
    INFO  [nioEventLoopGroup-2-1] 2021-04-12 15:28:26,372 Cli.java:617 - address=/10.244.1.1:45804 url=/api/v0/probes/readiness status=500 Internal Server Error
   .... repeats forever and no node ever actually starts...
   ```


**Environment (please complete the following information):**

* Helm charts version info
<!-- list installed charts and their versions from all namespaces -->
<!-- Replace the command with its output -->
```
$ helm ls -A
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
rack-test       k8ssandra       1               2021-04-12 18:24:21.033828061 +0300 EEST        deployed        k8ssandra-1.2.0-SNAPSHOT                   
``` 

* Helm charts user-supplied values
<!-- For each k8ssandra chart involved list user-supplied values -->
<!-- Replace the commands with its output -->
```
helm get values rack-test --namespace=k8ssandra 
USER-SUPPLIED VALUES:
cassandra:
  cassandraLibDirVolume:
    size: 5Gi
    storageClass: local-path
  datacenters:
  - heap:
      newGenSize: 200m
      size: 500
    name: dc1
    racks:
    - affinityLabels:
        topology.kubernetes.io/zone: n1
      name: n1
    - affinityLabels:
        topology.kubernetes.io/zone: n2
      name: n2
    - affinityLabels:
        topology.kubernetes.io/zone: n4
      name: n4
    size: 3
  enabled: true
  loggingSidecar:
    enabled: false
  version: 4.0.0
```

* Kubernetes version information:
<!-- Replace the command with its output -->
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-03-11T06:23:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: RKE, but it's reproducible with kind as well (use the diff)


<!-- Insert how you created your cluster: kind, kops, bootkube, etc. -->

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by jsanda** [comment]
Hi @steve-todorov 

Thanks for the detailed bug report. The `cassandra.log` file you attached provides the logs from the management-api. It would be helpful to see Cassandra's logs if there are any. Since you have the logging sidecar disabled, you can get them with `kubectl cp` as follows:

```
$ kubectl cp k8ssandra/rack-test-dc1-n1-sts-0:/var/log/cassandra/system.log rack-test-dc1-n1-sts-0.log
```

If there is `system.log` then that may indicate a startup problem that is happening before the logging system is initialized. 

I will try to reproduce as well.

**Comment by steve-todorov** [comment]
Hi @jsanda 

Thanks for the fast reply! :) 

Unfortunately there aren't any logs nor a log file being created: 

```
$ kubectl cp k8ssandra/rack-test-dc1-n1-sts-0:/var/log/cassandra/system.log rack-test-dc1-n1-sts-0.log
tar: Removing leading `/' from member names
tar: /var/log/cassandra/system.log: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

Let me know if you need more info or anything else I could do to help.

**Comment by jsanda** [comment]
Can you try increasing the heap size?

**Comment by jsanda** [comment]
@steve-todorov I see the problem. You heap size value is invalid. It should be `500M`. You are missing the `M` :)

**Comment by steve-todorov** [comment]
@jsanda you are absolutely right! I don't know how I missed that!! Everything seems to be working just fine now! I'm going to close this now. Thanks for your help!
