### ISSUE TITLE
Replace all ® with ™ in relation to Apache Cassandra

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#665]
## Bug Report

**Describe the bug**
We've been using the incorrect mark with the name `Apache Cassandra`. Any instances of `Apache Cassandra®` should be replaced with `Apache Cassandra™`.

**Comment by johnwfrancis** [comment]
Please see https://www.apache.org/foundation/marks/list/#:~:text=Cassandra%C2%AE%20software-,The%20ASF%20owns%20the%20following%20registered%20trademarks%20for%20our%20Apache,%2C%20class%209%2C%20reg%20%23%205158968 and close.

**Comment by johnwfrancis** [comment]
@bradfordcp ^

**Comment by bradfordcp** [comment]
Yep after following up with folks this ticket is super wrong. Closing. Thanks y'all
