### ISSUE TITLE
Taints and Tolerations for Cassandra pods/racks

### ISSUE THREAD

**Issue by mparikhcloudbeds** [k8ssandra/k8ssandra#673]
Our Multi-service Kubernetes cluster has other Statefulset such as Kafka, Zookeeper are set up with taints and tolerations

In order to make sure, Cassandra pods/racks are scheduled on dedicated node groups, it would be ideal to introduce taints and tolerations feature in Cassandra operator.

Our requirement mandates that, we need to reserve dedicated nodes for Cassandra only, avoid having any unrelated pods starting up there.

Benefit : It leads to more Conventional approach to schedule Kubernetes pods.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-36) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-36

**Comment by jsanda** [comment]
Hi @mparikhcloudbeds 

Thanks for creating this issue!

We definitely need support for taints and tolerations. There are two parts to this. First, we need to make sure that taint and tolerations are configurable in the CassandraDatacenter CRD (i.e., cass-operator). There are no properties that are specific to taints and tolerations. They can be configured indirectly through the `.spec.podTemplateSpec` property, but I would like to consider adding something in the [Racks](https://github.com/k8ssandra/cass-operator/blob/master/operator/pkg/apis/cassandra/v1beta1/cassandradatacenter_types.go#L264). Then we need to expose the configuration in the Helm chart.

**Comment by jsanda** [comment]
In my previous comment I floated the idea of a [Rack](https://github.com/k8ssandra/cass-operator/blob/master/operator/pkg/apis/cassandra/v1beta1/cassandradatacenter_types.go#L264)-level property. I think a top-level `tolerations` property that would be applied across all racks is adequate.

@mparikhcloudbeds what do you think?

**Comment by adejanovski** [comment]
Fixed by #740
