### ISSUE TITLE
Helm install throwing invalid values errors

### ISSUE THREAD

**Issue by sinohC** [k8ssandra/k8ssandra#675]
Hi!

I'm currently trying to deploy k8ssandra following the steps from https://k8ssandra.io/docs/getting-started/#install-k8ssandra

I have created the k8ssandra.yaml with all the default values except the version (I'm setting 3.11.7 version) but next errors appear after executing helm install command:

`Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: spec.serverVersion: Unsupported value: "3.11.7": supported values: "6.8.0", "3.11.6", "4.0.0"`

Sounds a bit "weird" as 3.11.7 version is supposed to be added by default in the versionImageMap property.

I've also tried with 3.11.6 , but next error appears:
`
Error: template: k8ssandra/templates/cassandra/cassdc.yaml:5:6: executing "k8ssandra/templates/cassandra/cassdc.yaml" at <fail (print .Values.cassandra.version " is not a supported Cassandra version")>: error calling fail: 3.11.6 is not a supported Cassandra version`

Any idea?

Thanks in advance!

**Comment by burmanm** [comment]
Which version of k8ssandra?

**Comment by sinohC** [comment]
The latest available in the helm chart stable repo : 1.1.0

Steps to reproduce:

-  `helm repo add k8ssandra https://helm.k8ssandra.io/stable`
-  `helm repo update`
-  Copy the example yaml from the quick start guide
-  `helm install -f k8ssandra.yaml k8ssandra k8ssandra/k8ssandra`

**Comment by burmanm** [comment]
Do you have something else installed in the same cluster? The first error comes from old cass-operator's webhookvalidation, but our chart does not install it.

**Comment by sinohC** [comment]
Yep, we had a cluster deployed with cass-operator but everything was supposed to be removed (at least I don't see any remnant from that cluster)

Your suggestion makes sense... do you have any idea what I should look for?

**Comment by sinohC** [comment]
I found this cassandradatacenter-webhook-registration from the old cluster I mentioned.

`NAME                                       WEBHOOKS   AGE
cassandradatacenter-webhook-registration   1          26d`

I removed it, but the error persists:

`Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: spec.serverVersion: Unsupported value: "3.11.7": supported values: "6.8.0", "3.11.6", "4.0.0"`

**Comment by jsanda** [comment]
See what the following returns:

kubectl get validatingwebhookconfiguration

**Comment by sinohC** [comment]
That validatingwebhookconfiguration is already removed.

Proble has been fixed by removing some old CRD from the "old" installation:

kubectl delete crd cassandradatacenters.cassandra.datastax.com

**Comment by slayerjain** [comment]
I'm facing the same issue. I have `1.4.1` installed. Can someone please guide me how to move it to k8ssandra with minimal downtime? 

```
$ helm install prod-k8ssandra k8ssandra/k8ssandra -f test.yaml

Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: spec.serverVersion: Unsupported value: "3.11.10": supported values: "6.8.0", "6.8.1", "6.8.2", "6.8.3", "3.11.6", "3.11.7", "4.0.0"
```

**Comment by jsanda** [comment]
Hi @slayerjain 

>Can someone please guide me how to move it to k8ssandra with minimal downtime?

See https://github.com/k8ssandra/k8ssandra/issues/669#issuecomment-833907014
