### ISSUE TITLE
Backups fail after a restore

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#678]
## Bug Report

**Describe the bug**
On a 3 node cluster, performing a backup consistently fails on one of the Cassandra pods after a restore has been performed. The error logged by Medusa looks like this:

```
[2021-04-18 18:12:09,441] WARNING: [control connection] Error connecting to 10.40.1.14:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3544, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 836, in cassandra.connection.Connection.factory
cassandra.connection.ProtocolVersionUnsupported: Unsupported protocol version on 10.40.1.14:9042: 4
```

**To Reproduce**
1. Install a 3 node cluster with backup/restore enabled - `helm install test k8ssandra/k8ssandra -f values.yaml`

values.yaml:
```yaml
cassandra:
  auth:
    enabled: false
  heap:
    size: 768M
    newGenSize: 256M
  - name: dc1
    size: 3
  loggingSidecar:
    enabled: false
medusa:
  enabled: true
  storage: s3
  bucketName: changeme
  storageSecret: changeme
  storage_properties:
    region: us-east-1
```
2. Wat for cluster to initialize
3. Create a backup - `helm install test-backup k8ssandra/backup --set name=backup-1,cassandraDatacenter.name=dc1`
4. Wait for backup operation to complete
5. Restore the backup - `helm install test-restore k8ssandra/restore -f restore-values.yaml`

restore-values.yaml:
```yaml
name: restore-1
backup:
  name: backup-1
cassandraDatacenter:
  name: dc1
  clusterName: test
inPlace: true
shutdown: true
```
6. Wait for restore operation to complete
7. Create a backup - `helm install test-backup k8ssandra/backup --set name=backup-2,cassandraDatacenter.name=dc1`
8. Monitor the logs of the `medusa` container. You should see the error reported above.

**Expected behavior**
The backup should complete without error.

* Helm charts version info
1.1.0

**Additional context**
I first encountered this while working on automated tests for medusa-operator. Initially I thought that there was a problem with my test code, so I tested manually and reproduced the behavior.

I noticed the following in the logs of the Cassandra node where the operation failed:

```
INFO  [main] 2021-04-18 17:41:04,012 StorageService.java:667 - Native protocol supported versions: 3/v3, 4/v4, 5/v5-beta (default: 4/v4)
...
INFO  [main] 2021-04-18 17:41:14,491 ConfiguredLimit.java:108 - Detected peers which do not fully support protocol V4. Capping max negotiable version to V3
```
Here is the relevant change in Medusa https://github.com/thelastpickle/cassandra-medusa/commit/df95d2d457062c745d125b2586f26c5cfc6296dc.

**Comment by mparikhcloudbeds** [comment]
@jsanda - Is this consistently reproducible on k8ssandra 1.1.0? 
We tried to reproduce this on our EKS dev environment and could not see the issue and all the medusa containers (log) reported Backup done without the issue.

**Comment by jsanda** [comment]
I was hitting it frequently with automated tests, but I do not think it was every time.
