### ISSUE TITLE
k8ssandra-operator design proposal and documentation

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#683]
Document and foster discussions about the potential planning and development of a higher-level operator and CRD for k8ssandra:

* What functionality would it provide?
* Design documentation
* Discussion with stakeholders
* Generate issues for planning into future sprints if pursued

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-33) by [Unito](https://www.unito.io)

**Comment by jsanda** [comment]
Here is a design doc for a k8ssandra operator - https://docs.google.com/document/d/1ioSglrAy_0mUBPvbWZ0jA2_u-1CaRZ19N2zr0m0ksTM/edit?usp=sharing
