### ISSUE TITLE
Support Azure Blob Storage for backup/restore workflows

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#685]
Currently, we support `s3_compatible` and `gcs` as backend storage mechanisms for backup/restore.  We'd also like support for [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/).

ABS is already supported by [medusa](https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/azure_blobs_setup.md) and should be configurable through k8ssandra.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-32) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.3.0

**Comment by bradfordcp** [comment]
I _just_ hit this issue prepping the AKS docs. Leaving a comment here so I know when to go back and fix them.
