### ISSUE TITLE
Performance benchmarking on EKS

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#687]
Apply performance benchmarking methodology to EKS and document results.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-468) by [Unito](https://www.unito.io)

**Comment by jeffbanks** [comment]
My AWS key-pair and Okta auth issues have been resolved as part of this effort.  EKS performance details were obtained and documented by @adejanovski.
