### ISSUE TITLE
Backup/restore support for local storage

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#69]
**Is your feature request related to a problem? Please describe.**
Currently, backup/restore is only supported for AWS S3 and Google Cloud storage.

**Describe the solution you'd like**
Add support for local storage as a means for backup/restore so that it can operate in environments where using cloud based blob storage is not an option.

**Describe alternatives you've considered**
Leveraging [MinIO](https://min.io/) as an AWS S3 compatible locally hosted object storage mechanism.

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-106)

**Comment by burmanm** [comment]
Closing this, as we currently do allow local, but what we want is to support CSI and other storageClasses to be this feature useful. Tracking in #560
