### ISSUE TITLE
Enhanced backup/restore workflow/scenario design

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#694]
Enhancing support for backup/restore functionality is an issue likely spans work across medusa, medusa-operator, and k8ssandra and warrants bit of upfront research/design to:

* Identify and prioritize workflows/requirements
* Discuss and propose solution approaches
* Scope future work

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-31) by [Unito](https://www.unito.io)

**Comment by adejanovski** [comment]
Design doc is available here: https://docs.google.com/document/d/1Ynr-FrgfwBm_QulvhbURJXv0QdMs0Lx52Bi7vlwgoyA/edit?usp=sharing
