### ISSUE TITLE
Provide a way to set tolerations for different types of pods.

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#698]
We do not yet provide a way to set tolerations on our deployments, which does not allow controlling on which k8s nodes specific pods will be deployed.
Cassandra nodes specifically shouldn't be collocated with other pods as they require lots of resources.

**Comment by gkocur** [comment]
First I would like to appreciate a great work you do in this project, thank you!
I would like to "vote" for this issue, without this it's practically useless on production, where - @adejanovski wrote - shouldn't be located on the same nodes as services.
We try to achieve it by setting `Cassandra.enabled: false` and adding the cassdc manifest with custom `podTemplateSpec` but it requires  log of hacking and we are not happy with this.
IMO the best approach would be to allow set `podTemplateSpec` which could be merged with generated by helm template. 
On the other hand adding only taints and tolerations seems to be much easier.
How can I help to have this issue resolved soon?

**Comment by jsanda** [comment]
Hi @gkocur 

Thanks for the feedback!

>We try to achieve it by setting Cassandra.enabled: false and adding the cassdc manifest with custom podTemplateSpec but it requires log of hacking and we are not happy with this.

Agreed

>IMO the best approach would be to allow set podTemplateSpec which could be merged with generated by helm template.

I am not sure I am a fan of exposing `podTemplateSpec`. It couples you to the implementation of cass-operator which I think is a bit dangerous. A subsequent minor release of cass-operator could change the implementation around tolerations and `podTemplateSpec` while still keeping API compatibility with previous versions. 

I would prefer to consider how we want expose tolerations in chart properties in more explicit way. I think this would be more consistent with how we expose other settings. Then we can look and see what CRD changes would be required in cass-operator. How does that sound?

>How can I help to have this issue resolved soon?

If you could put together some sort of design doc  that would be great.

**Comment by gkocur** [comment]
After re-thinking it I agree - exposing `podTemplateSpec` will be complicated for users.

I don't think we need any changes in cass-operator  CRD - it already has everything we need to do it:
https://github.com/k8ssandra/k8ssandra/blob/0f94f55364d4f0180df39b944c55813490ccb4f7/charts/cass-operator/crds/customresourcedefinition.yaml#L4502
https://github.com/k8ssandra/k8ssandra/blob/0f94f55364d4f0180df39b944c55813490ccb4f7/charts/cass-operator/crds/customresourcedefinition.yaml#L180

About the design doc - how do you image it should look like? Is there some example?

**Comment by jsanda** [comment]
The properties you are referencing are from `podTemplateSpec`. Let me take a step back and ask a couple questions.

* Would you specify tolerations globally to be applied to all Cassandra pods, or would you do it per rack like we do with affinity labels, or some other way?
* Would you make tolerations configurable for other pods, like for Reaper and Stargate?

**Comment by mparikhcloudbeds** [comment]
@jsanda - Looking at our current EKS cluster that supports multiple services aside from what we have in k8ssandra, we do think having a flexibility to define taints and tolerations for most (if not all depending upon what purpose they serve) would be helpful such that we can have k8ssandra services avoids other general purpose services not stumble upon the same nodes. We can achieve it quite a few different ways but IMHO it keeps k8ssandra boundary isolated from other.

Let me know your thoughts

**Comment by jsanda** [comment]
@mparikhcloudbeds agreed.

We already have #673 to add support for specifying tolerations for Cassandra. kube-prometheus-stack already exposes properties for tolerations and affinity for both Prometheus and Grafana. That leaves us the following that needs be done:

* Tolerations for Stargate
* Affinity for Stargate
* Tolerations for Reaper
* Affinity for Reaper
* Tolerations / affinity for each of the operators
    * I lumped these together because I think they are lower priority. Please let me know if you feel otherwise.

**Comment by gkocur** [comment]
Sorry for late answer, short vacations ;)
I agree we should have affinity and tolerations for all pods, it will make it elastic.
But obviously - the most important is Cassandra.
Since there is already affinity on rack level probably having tolerations on the rack level is most consistent approach.

**Comment by jsanda** [comment]
Affinity at the rack level makes sense because we want to pin each rack to a different availability zone. With tolerations we to taint worker nodes for Cassandra. I don't think it makes sense though to taint worker nodes for rack1 vs rack2 etc. The Cassandra nodes and their configurations should be the same across racks. If they differ, it could lead to performance problems. This is why I think it is sufficient to specify tolerations at the DC level. 

@gkocur does that make sense?
