### ISSUE TITLE
Update GKE install documentation to recommend premium-rwo storage class

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra#709]
**Is your feature request related to a problem? Please describe.**

The [current doc page on GKE](https://docs.k8ssandra.io/install/gke/) recommends standard-rwo as the storage class for persistent volumes.

We found out that standard-rwo should be avoided. It corresponds to pd-balanced disks as shown in the below table:

![image](https://user-images.githubusercontent.com/463876/116703021-11ad7380-a9ca-11eb-9c98-d821a3b7c64a.png)

Cassandra persistent volumes should use instead premium-rwo, which offers much better IOPS and throughput.

**Describe the solution you'd like**

Change the snippet here: https://docs.k8ssandra.io/install/gke/#generate-gkevaluesyaml.

Instead of:

```
  # Configuration for the /var/lib/cassandra mount point
  cassandraLibDirVolume:
    # GCP provides this storage class on GKE clusters out of the box. Note we
    # are using `standard-rwo` here as it has `volumeBindingMode:
    # WaitForFirstConsumer` which is important during scheduling.
    storageClass: standard-rwo
```

We should advertise:

```
  # Configuration for the /var/lib/cassandra mount point
  cassandraLibDirVolume:
    # GCP provides this storage class on GKE clusters out of the box.
    # It corresponds to SSD persistent disks (pd-ssd) and is the 
    # recommended storage class for Cassandra.
    # See https://cloud.google.com/compute/docs/disks/performance#type_comparison
    storageClass: premium-rwo
```

**Describe alternatives you've considered**

None

**Additional context**

**Comment by bradfordcp** [comment]
Nice catch. This has been updated in #700 and should roll out here shortly.

**Comment by adutra** [comment]
Sorry to surface this again... It turns out that standard-rwo is good enough for large volumes (> 1Ti – allowed IOPS depends on the disk size), and is much cheaper. So we're changing again our recommendation back to standard-rwo since the recommended volume size is 2Ti.

**Comment by johnsmartco** [comment]
Ok thanks @adutra , I can edit the text back to standard-rwo today unless Chris @bradfordcp beats me to it.  :-)
