### ISSUE TITLE
Configure Grafana root_url sub-path

### ISSUE THREAD

**Issue by shallada** [k8ssandra/k8ssandra#71]
I need to run K8ssandra behind a proxy which will not allow me to use the virtual-host approach to access the various services. I can create a path that I can expose through the proxy. Grafana has some settings in the config file for just this situation.

[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true

I would like some way to configure these values.

**Comment by jsanda** [comment]
These settings are exposed through the `Grafana` CRD. I will try submit a PR tomorrow.
