### ISSUE TITLE
DS K8ssandra blog content availability from k8ssandra.io

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#710]
With the k8ssandra.io site, we should consider the inclusion of blog postings related to `K8ssandra technical deep-dives` to be available from the k8ssandra.io site's `blog` posts.   

This allows visitors looking specifically for K8ssandra content to find information being published for a wider audience at https://www.datastax.com/blog.

Example, [this one](https://www.datastax.com/blog/2021/04/kubernetes-data-simplicity-getting-started-k8ssandra) (from Jeff Banks) is not available from the k8ssandra.io site and another K8ssandra deep-dive (from John Sanda) will be published in the near future.

This could be useful for KubeCon Europe 2021 visitors.

**Comment by bradfordcp** [comment]
We'll get this added to the new site today. We have CMS training this afternoon.

**Comment by jdonenine** [comment]
@jeffreyscarpenter took care of things for us, the blogs are getting linked as news articles on the site to connect to the content.

**Comment by johnsmartco** [comment]
All set, closing.
