### ISSUE TITLE
Operator Design Discussions

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#719]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-24) by [Unito](https://www.unito.io)
┆Epic: K8ssandra Operator

**Comment by jsanda** [comment]
Here is a design doc for a k8ssandra operator - https://docs.google.com/document/d/1ioSglrAy_0mUBPvbWZ0jA2_u-1CaRZ19N2zr0m0ksTM/edit?usp=sharing

**Comment by arianvp** [comment]
@jsanda would it be possible to make the google doc public? I'm curious what the design ideas are.

**Comment by jsanda** [comment]
Link to design doc - https://docs.google.com/document/d/1ioSglrAy_0mUBPvbWZ0jA2_u-1CaRZ19N2zr0m0ksTM/edit?usp=sharing

**Comment by jdonenine** [comment]
Hi @arianvp we've moved the design doc into the repo to make it a bit easier to share.  We'd love to get your feedback via the PR that it's open within anytime you have a chance:

https://github.com/k8ssandra/k8ssandra/pull/818
