### ISSUE TITLE
Reaper: Make incremental schedules trigger on %unrepaired threshold #1058

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#728]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-19) by [Unito](https://www.unito.io)
┆Epic: Incremental Repair
┆Issue Number: K8SSAND-19

**Comment by adejanovski** [comment]
Closing as "won't do".
This can be configured in Reaper though.
