### ISSUE TITLE
Reaper: Collect %repaired for incremental repair schedules #1057

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#729]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-18) by [Unito](https://www.unito.io)
┆Epic: Incremental Repair
┆Issue Number: K8SSAND-18

**Comment by adejanovski** [comment]
PR is ready for review: https://github.com/thelastpickle/cassandra-reaper/pull/1062
