### ISSUE TITLE
Add documentation related to the configuration of StorageClasses

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#73]
**Is your feature request related to a problem? Please describe.**
It's unclear how to properly configure the required StorageClass for various types of storage.

**Describe the solution you'd like**
Provide examples of StorageClass configuration, similar to what is found in the documentation for the [cass-operator](https://github.com/datastax/cass-operator#creating-a-storage-class), for the following types of providers in the documentation:
- GKE
- EKS
- AKS
- Local/Development

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-57)

**Comment by johnwfrancis** [comment]
So all we support right now is AWS--any idea when this will be ready?

**Comment by jsanda** [comment]
A storage class is a kubernetes type that allows you to specify details about the different types of storage available in the k8s cluster.

**Comment by johnsmartco** [comment]
@johnwfrancis covered this info in https://k8ssandra.io/docs/getting-started/#storage-classes.  Closing.
