### ISSUE TITLE
Storage and datacenter management improvement suggestions; medusa restore operaiton issue

### ISSUE THREAD

**Issue by michalschott** [k8ssandra/k8ssandra#733]
Hello,

First of all great job on delivering a solution which will allow to run production-grade Cassanra instances inside kubernetes!
I've been playing with k8ssandra on EKS for a while, wanted to share my findings and potential improvements.

1. Storage
EKS comes by default with default storageClass `gp2` which does not allow for volume expansion (`allowVolumeExpansion: false`). It also have reclaim policy set to `Delete`.
I know that storageClasses are vendor specific, but I'd a least mention consequences in documentation:

* deleting `cassdc` without backup will make you loose data;
* changing storageClass is not easy operation and is forbidden to update this field withing StatefulSet;
* `medusa` restoration for now downloads content of s3 bucket to local storage - I have seen `disk full` errors so many times. Being able to extend disks on the fly is really helpful.

Maybe mentioning these bullets in `Getting started` documentation will prevent people to put precious data into provisioned-by-defualt `dc1` without any disaster recovery strate

1. Datacenter management
Because of reasons in #1 I believe datacenter management should happen outside of k8ssandra helm chart. Here's why:

* `kubectl delete cassdc dc1`
* `helm upgrade k8ssandra k8ssandra/k8ssandra --version 1.1.0` won't restore `cassdc dc1` because theres no drift in value file / values provided to helm
* same applies to [Terraform Helm Provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs)

Following above steps you essentially need to forcefully reinstall helm release in order to bring back dc1.

1. Medusa restoration
I have tried to restore medusa backup from installation performed with chart version 0.17.1 to the other one hosted on different cluster and installed with chart version 1.1.0.

* created backup using medusa on old k8s cluster
* created s3 bucket on new AWS account where new EKS instance and k8ssandra runs
* synced bucket content
* noticed there was a naming change, so for instance `k8ssandra-dc1-default-sts-0.k8ssandra-dc1-service.production.svc.cluster.local` was copied/renamed to `k8ssandra-production-dc1-default-sts-0.k8ssandra-production-dc1-service.production.svc.cluster.local` within new s3 bucket
* tried to restore by applying this:

```
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraRestore
metadata:
  name: restore
spec:
  backup: backup
  inPlace: true
  shutdown: true
  cassandraDatacenter:
    name: dc1
    clusterName: dc1
```

* in medusa operator logs I have spotted error saying something like `backup object with name backup does not exist`
* so I assumed medusa operator is using `cassandrabackup` for restoration - so I have recreated this object with:

```
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraBackup
metadata:
  name: backup
spec:
  name: backup
  cassandraDatacenter: dc1
```

* it failed saying backup already exist, so I have cleaned up s3 bucket and deleted backup object and reapplied backup definition
* to ensure data is consistent I have repeated s3 'folder' rename operation
* after recreating restore object - restoration have started!

... but at some time it failed after a lot debug informations about 'table is empty, won't import'.

Then I found [this document](https://docs.google.com/document/d/1Ynr-FrgfwBm_QulvhbURJXv0QdMs0Lx52Bi7vlwgoyA/edit#heading=h.j61iqxlkkhlb)

* if I understand correctly this isn't really supported now?

Best,
Michal

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-16) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-16
┆Priority: Medium

**Comment by jsanda** [comment]
Hi @michalschott 

Sorry for the delayed response. You covered a lot in this ticket. It might be easier to separate out some of these things into separate issues. I'll respond to some of them now.

>Maybe mentioning these bullets in Getting started documentation will prevent people to put precious data into provisioned-by-defualt dc1 without any disaster recovery strate

Can you open a PR for this?

>Because of reasons in #1 I believe datacenter management should happen outside of k8ssandra helm chart.

Keep an eye on #719. I have been working on a design doc for an operator. I will post a link to it soon.

>Then I found this document - if I understand correctly this isn't really supported now?

Unfortunately you ran into #70 and yes, the plan is to address remote restore with that document.
