### ISSUE TITLE
Improve developer documentation

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#75]
**Is your feature request related to a problem? Please describe.**
I'm a developer who wants to get involved in the project, but I don't know how to get started.

**Describe the solution you'd like**
Provide documentation related to:
- Development environment requirements
- Development environment setup
- Executing tests
- Writing tests

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-62) [Jira](https://k8ssandra.atlassian.net/browse/K8C-37)

**Comment by bradfordcp** [comment]
This may be an excellent time to build out the contributing section which currently focuses solely on docs.

**Comment by jsanda** [comment]
I am not entirely convinced dev docs should be stored with user docs, i.e., on k8ssandra.io.

**Comment by johnwfrancis** [comment]
Closing this as a dupe of #239
