### ISSUE TITLE
K8SSAND-12 ⁃ Migrate cass-config-builder to k8ssandra organization

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#751]
Migrate cass-config-builder code and packaging repositories to the k8ssandra organization:

* Code repo to migrate:  https://github.com/datastax/cass-config-builder
  * A GH transfer seems reasonable
* Docker repository to migrate:  https://hub.docker.com/r/datastax/cass-config-builder
  * Leave existing repo in place to not break existing usage
  * New builds should be published to a new cass-config-builder repo under the k8ssandra DH org

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-12) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-12
┆priority: Medium

**Comment by bradfordcp** [comment]
GH transfer is reasonable, but just like the `cass-operator` it feels like that's not really possible given history of the project. There are some conversations happening now around replacing the config builder. If that's the direction we're headed I think this ticket should just be closed.
