### ISSUE TITLE
Run EKS benchmarks using direct attached NVMe drives.

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#754]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-9) by [Unito](https://www.unito.io)
┆Epic: Cloud Provider Performance Benchmarking

**Comment by adejanovski** [comment]
Based on our latest research and discussions, we won't perform benchmarks on direct attached storage as it is not how storage should be provisioned for stateful workloads in managed k8s services.
