### ISSUE TITLE
Update GKE documentation with settings and guidelines used during benchmarks.

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#756]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-7) by [Unito](https://www.unito.io)

**Comment by johnsmartco** [comment]
Gents, @adejanovski , @bradfordcp, in PR https://github.com/k8ssandra/k8ssandra/pull/924/files, I've incorporated a subset of settings and guidelines for GCP GKE from the benchmark report, and linked readers to the full blog for throughput & latency results. Please take a look, and let me know your thoughts. If the updates for GKE look good, I'll make similar edits in the K8ssandra install topics for AKS and EKS. Thanks.

**Comment by johnsmartco** [comment]
Followup: in addition to reviewing the topic's next text, please compare the guidance from the benchmark with the current  gke.values.yaml settings. It's imported into the install on GKE topic. I wasn't sure whether any of those settings should be tweaked.  

https://github.com/k8ssandra/k8ssandra/blob/main/docs/content/en/install/gke/gke.values.yaml
