### ISSUE TITLE
K8SSAND-135 ⁃ The k8ssandra-cluster chart instructions should say how to connect to Cassandra via cqlsh

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#78]
**Is your feature request related to a problem? Please describe.**
Similar to #77 after the chart installs, more info should be provided as to how to access the C* cluster.

**Describe the solution you'd like**
The chart instructions should tell the user how to connect to the Cassandra cluster with cqlsh.

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-26)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-135) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-135
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/78?planning-poker) with ZenHub @adejanovski @adutra @jeffbanks @jsanda

**Comment by adejanovski** [comment]
Closing as won't do.
