### ISSUE TITLE
Add multi-DC support

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#83]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to create a multi-DC cluster with the k8ssandra-cluster chart. 

**Describe the solution you'd like**
This would likely come in the form of a helm upgrade. As a user, I may create a cluster with one DC. Later I decided that I want to add a second DC.

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-71)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-138) by [Unito](https://www.unito.io)

**Comment by jsanda** [comment]
related to #109

**Comment by jdonenine** [comment]
Closing as an old dup of newer ticket https://github.com/k8ssandra/k8ssandra/issues/524
