### ISSUE TITLE
Unable to uninstall or reuse helm name after failed installation

### ISSUE THREAD

**Issue by TheSamabo** [k8ssandra/k8ssandra#838]
## Bug Report
**Describe the bug**
Im trying to transfer from our cass cluster to k8ssandra with new storageClass and with datacenter migration. The cluster name is 2 words where each is starts with capital letter. This was problem for reaper, so i looked over few issues here and found https://github.com/k8ssandra/k8ssandra/pull/740. When i tried to run helm install again i got `Error: cannot re-use a name that is still in use` so i changed the helm install name and ran again. I get the same error for Stargate.

After i tried running `helm uninstall k8ssandra k8ssandra/k8ssandra` the cleaner pods failed with:  `Failed to list CassandraDatacenters in namespace: custom`. Even then i could not run the same `helm install k8ssandra k8ssandra/k8ssandra -f k8ssandra.yaml` becouse it threw:  `Error: cannot re-use a name that is still in use`

**To Reproduce**

1. Create new k8ssandra.yaml wth cluster name with capital letter and/or space between words. eg: "Custom Cluster"
1. Run `helm install k8ssandra k8ssandra/k8ssandra -f k8ssandra.yaml`
1. Install will fail with Invalid value for `metadata.name` for reaper and stargate maybe others
1. fix reaper and stargate names with `tolerations` definition
1. Run the same `helm install k8ssandra k8ssandra/k8ssandra -f k8ssandra.yaml`
1. Get error: Error: cannot re-use a name that is still in use
1. Run `helm uninstall k8ssandra  k8ssandra/k8ssandra `
1. Cleaner Container will error: Failed to list CassandraDatacenters in namespace: custom
1. Running num. 5 will result in the same error as in  num. 6

**Expected behavior**
Install via the same name as with the previous failed installations

**Environment (please complete the following information):**

* Helm charts version info
`NAME           	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
haproxy-ingress	ingress-controller	1       	2021-05-03 10:01:00.093435476 +0000 UTC	deployed	haproxy-ingress-0.12.3	v0.12.3

ingress-nginx  	custom       	1       	2021-05-06 13:31:41.210254344 +0000 UTC	deployed	ingress-nginx-3.30.0  	0.46.0

k8ssandra   	custom       	1       	2021-05-28 09:29:07.703904769 +0000 UTC	failed  	k8ssandra-1.1.0` 

* Kubernetes version information:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster kind:
kubeadm

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-492) by [Unito](https://www.unito.io)

**Comment by jsanda** [comment]
Hi @TheSamabo 

Can you share your `k8ssandra.yaml`?

Can you explain step 4? Are you saying that you used invalid identifier names and then tried to resolve it by setting tolerations?

**Comment by TheSamabo** [comment]
Hi! soory for late response
my k8ssandra.yaml: https://pastebin.com/Jm4J05Ey

I tried to fix: `Error: Secret "Custom Cluster-reaper" is invalid: metadata.name: Invalid value: "Custom Cluster-reaper": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`
This prompted me to try those tolerations to modify reaper and stargate made objects name.

**Comment by jsanda** [comment]
You have `clusterName: "Custom Cluster"`. k8ssandra generates multiple secrets that include `clusterName` in the secret name, one of which is of the form `{{ clusterName }}-reaper` where `{{ clusterName }}` evaluates to `Custom Cluster`. I would simply change the value of `clusterName` to `customer-cluster`. Setting the tolerations won't do anything about those object names.

**Comment by TheSamabo** [comment]
I understand, but the problem is that i am migrating from statefulset cassandra cluster to k8ssandra. My already created and data filled cluster is called: `Custom Cluster`. That is why i tried to manualy rename reaper and stargate components in k8ssandra

**Comment by jsanda** [comment]
You could manually create manually the secrets. You might run into this problem with other objects though.

**Comment by TheSamabo** [comment]
I thought so. Looks like the only option is to build new cluster with more appropriate name from backed up SSTables.
Thank you anyway.

**Comment by jeffreyscarpenter** [comment]
This is a really interesting use case for K8ssandra adoption - the migration aspect. I'd be interested in hearing more about what the experience has been like overall and what else K8ssandra should be providing. One easy place for us to converse would be on our [Discord](https://discord.com/invite/qP5tAt6Uwt) server.
