### ISSUE TITLE
Helm Charts - cassdc.yaml, no possiblity to define private registry to busybox

### ISSUE THREAD

**Issue by mehmetsalgar** [k8ssandra/k8ssandra#840]
## Bug Report
'charts/k8ssandra/templates/cassandra/cassdc.yaml' use busybox image to set JMX CREDENTIAL unfornately our Kubernetes Cluster is behind a company firewall and we have no access to public docker registries and for this reason busybox image can't be downloaded and the Helm Charts installation fails.

**To Reproduce**
Try to install K8ssandra Helm Chart from private rdocker registry while all the public registry accress prevented with firewall.

**Expected behavior**
It should be possible to configure private docker registry to be able to download the busybox image.

**Environment (please complete the following information):**

* Helm charts version info
3.5.2
k8ssandra Helm Chart Version 1.1.0
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7",
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9",
* Kubernetes cluster kind:
Rancher

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-494) by [Unito](https://www.unito.io)
┆Epic: Image Access Enhancements
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
Hi @mehmetsalgar ,

Is this issue the same as #420?

**Comment by mehmetsalgar** [comment]
Yep, it is the same problem
