### ISSUE TITLE
DOC - Missing page - Retrieve K8ssandra superuser credentials

### ISSUE THREAD

**Issue by ErickRamirezDS** [k8ssandra/k8ssandra#842]
## Bug Report
**Describe the bug**
The page [Retrieve K8ssandra superuser credentials](https://docs.k8ssandra.io/quickstarts/#superuser) is missing from docs.k8ssandra.io

**To Reproduce**

1. Browse to [Quickstart for Site Reliability Engineers](https://docs.k8ssandra.io/quickstarts/site-reliability-engineer/)
1. Scroll down to **step 2** of [Access the Apache Cassandra® nodetool utility](https://docs.k8ssandra.io/quickstarts/site-reliability-engineer/#nodetool)
1. The link to [Retrieve K8ssandra superuser credentials](https://docs.k8ssandra.io/quickstarts/#superuser) just goes to the Quickstarts page and not the instructions for retrieving credentials.

**Expected behavior**
I expect to be taken to the page with instructions for retrieving K8ssandra superuser credentials.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**

* Helm charts version info
Not applicable.
* Helm charts user-supplied values
Not applicable.
* Kubernetes version information:
Not applicable.
* Kubernetes cluster kind:
Not applicable.

**Additional context**
Not applicable.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-495) by [Unito](https://www.unito.io)

**Comment by johnsmartco** [comment]
Thanks, fixing.
