### ISSUE TITLE
Allow configuration of ServiceMonitor namespace

### ISSUE THREAD

**Issue by arianvp** [k8ssandra/k8ssandra#844]
**Is your feature request related to a problem? Please describe.**
I already have a prometheus stack installed (In the `monitoring` namespace) so I disabled K8ssandra's kube-prometheus-stack. However it doesn't pick up the `ServiceMonitor` as it's deployed in the wrong namespace.    Would it be possible to define the namespace the `ServiceMonitor` is defined in?

**Describe the solution you'd like**
Usually charts expose a `metrics.serviceMonitor.namespace` option to specify where the chart's servicemonitor is installed. See e.g. https://github.com/bitnami/charts/blob/395934bfc46804f5aa1b96d2fca416c0d5bfa02e/bitnami/rabbitmq/templates/servicemonitor.yaml#L6

**Describe alternatives you've considered**
None

**Additional context**

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-499) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
Hey @arianvp 

This sounds like a good enhancement. Would you like to contribute a PR for it?

**Comment by arianvp** [comment]
Just noticed; cass-operator itself also deploys a `ServiceMonitor` and it's always deployed in the operator's namespace. I suppose to fully fix this issue a PR to `cass-operator` is needed as well
