### ISSUE TITLE
Affinity configuration support for C* pod scheduling

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#846]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Provide support within the k8ssandra chart for the specification of affinity configuration to allow for further control of the scheduling of C* pods within a deployment.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-501) by [Unito](https://www.unito.io)
┆Epic: Pod Scheduling Control
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
@jdonenine cass-operator does not directly expose affinity. Racks are an abstraction for affinity. You can specify labels per rack which cass-operator in turn uses for affinity. See https://github.com/k8ssandra/k8ssandra/blob/main/tests/unit/testdata/racks-affinity-values.yaml for an example.

We can close this ticket.

@johnsmartco I checked the docs and did not see anything on configuring racks. If that is missing, we definitely need content for that. I am happy to assist.
