### ISSUE TITLE
Affinity configuration support for Grafana pod scheduling

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#849]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Provide support within the k8ssandra chart for the specification of affinity configuration to allow for further control of the scheduling of Grafana pods within a deployment.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-504) by [Unito](https://www.unito.io)
┆Epic: Pod Scheduling Control
┆Fix Versions: k8ssandra-1.3.0

**Comment by jsanda** [comment]
@jdonenine I think we can close this. Affinity is already configurable. The kube-promtheus-stack chart depends on the Grafana chart. The Grafana chart exposes affinity. See https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L238. This means it is exposed and accessible to kube-prometheus-stack and in turn accessible to kssandra.
