### ISSUE TITLE
Document authorization configuration

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#85]
**Is your feature request related to a problem? Please describe.**
How can authorization be configured and provided?

**Describe the solution you'd like**
Documentation outlining options and examples related to authorization.

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-17)

**Comment by johnsmartco** [comment]
Done, thanks.   https://docs.k8ssandra.io/tasks/secure/
