### ISSUE TITLE
Make the chart available on artifacthub.io/helm search hub

### ISSUE THREAD

**Issue by jeantil** [k8ssandra/k8ssandra#87]
**Is your feature request related to a problem? Please describe.**
Helm and CNCF have introduced an aggregator for charts repositories that lets users easily discover, pull charts or add them as dependencies to other charts.
k8ssandra is not listed in the aggregator or helm search results which makes it less discoverable.

neither 
* https://artifacthub.io/packages/search?page=1&ts_query_web=cassandra 
* https://artifacthub.io/packages/search?page=1&ts_query_web=k8ssandra
return the k8ssandra  chart information and instead list 3rd party charts.

**Describe the solution you'd like**
I would like for k8ssandra to appear in the search results :) 

The [3rd page](https://helm.sh/docs/intro/using_helm/) of the introduction to  helm demonstrates using `helm search hub` which makes `helm search hub cassandra` the obvious thing to run for people looking for a cassandra chart.

**Comment by jeantil** [comment]
Relevant documentation: https://artifacthub.io/docs/topics/repositories/ to add https://helm.k8ssandra.io/ to artifacthub

**Comment by bradfordcp** [comment]
Thanks for the tip. We should now be showing up in searches on Artifact Hub. See https://artifacthub.io/packages/search?page=1&ts_query_web=k8ssandra
