### ISSUE TITLE
GH publish-website action impacted by new dependencies, cannot finish build/deploy docs

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra#873]
## Bug Report

**Describe the bug**
Looks like an issue popped up with our GH publish-website action when we bumped dependencies. 

**To Reproduce**
See https://github.com/k8ssandra/k8ssandra/actions/workflows/publish-website.yaml.  Jobs since about 5-6 days ago (June 5) have stopped working. 

**Expected behavior**
Updated docs that pass validation tests can build and deploy to docs.k8ssandra.io.

**Additional context**
Build : "Process completed with exit code 255."
For example, see https://github.com/k8ssandra/k8ssandra/actions/runs/915391191. 

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-566) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
Hmm, I will try to fix this today. 

I see the problem, although I’m not sure why the changes broke this. In any case, the fix should be simple. 

> npm WARN autoprefixer@10.2.6 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
7
npm WARN postcss-cli@8.3.1 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
8
npm WARN postcss-reporter@7.0.2 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
