### ISSUE TITLE
Allow for custom labels and annotations in values.yaml

### ISSUE THREAD

**Issue by debjitk** [k8ssandra/k8ssandra#874]
Allow for custom `labels` and `annotations` for the `Cassandra` services. For example `Service Mesh` like `Istio`, `Consul` and others require custom annotations to work.

┆Issue is synchronized with this [Jiraserver Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-567) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-567
┆Priority: Medium

**Comment by jsanda** [comment]
Hi @debjitk 

Support for custom labels and annotation in services was added in cass-operator 1.7.0 (see https://github.com/datastax/cass-operator/pull/398). It just needs to be exposed in k8ssandra. Would you be interested in submitting a PR for this?
