### ISSUE TITLE
function "lookup" not defined due to bitnami/common version

### ISSUE THREAD

**Issue by klingerr** [k8ssandra/k8ssandra#882]
## Bug Report
**Describe the bug**
We've got the error message:
`Error: parse error at (cassandra-source-dev/charts/cassandra-template/charts/k8ssandra/charts/reaper-operator/charts/k8ssandra-common/charts/common/templates/_secrets.tpl:84): function "lookup" not defined`
while installing a helm chart which uses k8ssandra in its dependency hierarchy. I.e. we created a helm chart with k8ssandra as dependency, it's called "cassandra-template". "Cassandra-template" is used as a helm dependency in another helm chart called "cassandra-source-dev" and the error occurs during the installation of "cassandra-source-dev".

Interestingly the installation of "cassandra-template" works fine.

An similar issue is descibed here: https://github.com/bitnami/charts/issues/5032#issuecomment-762481030
Since bitnami/common is used as dependency in `k8ssandra/charts/k8ssandra-common/Chart.yaml` we assume that it's necessary to increase the version of bitnami/common to at least 1.3.5 to resolve this issue.

**To Reproduce**

1. Create a helm chart "cassandra-template" with k8ssandra as dependency
1. Create a helm chart "cassandra-source-dev" with "cassandra-template" as dependency
1. Install the helm chart "cassandra-source-dev"
1. See error

**Expected behavior**
The installation should run without errors.

**Environment (please complete the following information):**

* Helm charts version info

```
NAME                 	NAMESPACE               	REVISION	UPDATED                                 	STATUS  	CHART                                                                             	APP VERSION
fleet-agent          	fleet-system            	2       	2021-05-21 14:59:53.640357064 +0000 UTC 	deployed	fleet-agent-v0.0.0+s-2879661f9d0e3cfaea1b12951bb30640413f45ac5ccec4579b5c261733160	           
kube-prometheus-stack	monitoring              	4       	2021-04-26 16:35:12.54944821 +0200 CEST 	deployed	kube-prometheus-stack-14.9.0                                                      	0.46.0     
loki                 	loki                    	2       	2021-04-21 10:43:39.191398784 +0200 CEST	deployed	loki-2.5.0                                                                        	v2.2.0     
metallb              	metallb-system          	3       	2021-04-21 10:37:55.485587642 +0200 CEST	deployed	metallb-2.3.5                                                                     	0.9.6      
minio                	velero                  	3       	2021-04-21 10:39:27.596650169 +0200 CEST	deployed	minio-8.0.10                                                                      	master     
promtail             	loki                    	1       	2021-04-21 10:45:30.513558048 +0200 CEST	deployed	promtail-3.5.0                                                                    	2.2.0      
traefik              	traefik                 	1       	2021-04-21 10:38:32.680010835 +0200 CEST	deployed	traefik-9.18.2                                                                    	2.4.8      
vault                	vault                   	4       	2021-06-01 12:22:40.140533842 +0200 CEST	deployed	vault-0.12.0                                                                      	1.7.2      
velero               	velero                  	3       	2021-04-21 10:39:40.353016735 +0200 CEST	deployed	velero-2.17.2                                                                     	1.6.0      
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

* Kubernetes cluster kind:

Kubernetes is provisioned by Rancher. Node OS is Ubuntu 20.10.

**Additional context**
An similar issue is descibed here: https://github.com/bitnami/charts/issues/5032#issuecomment-762481030
Since bitnami/common is used as dependency in `k8ssandra/charts/k8ssandra-common/Chart.yaml` we assume that it's necessary to increase the version of bitnami/common to at least 1.3.5 to resolve this issue.

**Screenshot**
![image](https://user-images.githubusercontent.com/5718789/121673753-87b8f600-cab1-11eb-8998-a0de3fec4243.png)

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-571) by [Unito](https://www.unito.io)

**Comment by klingerr** [comment]
We identified the problem. We used an old helm version (3.0.0). Using a newer version solved the issue.

**Comment by bradfordcp** [comment]
Interesting, what version did you move to?

**Comment by klingerr** [comment]
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
Newer versions of helm should also work, but we did not try yet.
