### ISSUE TITLE
ingressroutes are lost during scale up / scale down operations

### ISSUE THREAD

**Issue by tomereli** [k8ssandra/k8ssandra#89]
## Bug Report

**Describe the bug**
k8ssandra-cluster scale up/down reverts changes to ingress

**To Reproduce**
1. Provision a Cassandra cluster according to https://k8ssandra.io/docs/getting-started/
2. Install traefik according to https://k8ssandra.io/docs/topics/ingress/traefik/kind-deployment/#4-install-traefik-via-helm
3. Upgrade the cluster by enabling ingress. Example command:
```
helm upgrade k8ssandra-cluster  ./charts/k8ssandra-cluster --set ingress.traefik.enabled=true --set ingress.traefik.monitoring.grafana.host=grafana.tomer-cass --set ingress.traefik.monitoring.prometheus.host=prometheus.tomer-cass --set ingress.traefik.repair.host=repair.tomer-cass
```
4. Verify access to services UIs (should work) and ingressroutes are in place:
![image](https://user-images.githubusercontent.com/13386849/100151145-70197780-2ea9-11eb-92a6-ade100af68b0.png)

5. Scale up the cluster to 3 nodes and wait for it to be fully operational
6. Scale down the cluster back to 1 node
7. See error - cannot access services. The reason is that the ingressroutes dissapeared.

**Expected behavior**
ingressroutes should not get affected by scale up / scale down operations.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

![image](https://user-images.githubusercontent.com/13386849/100151394-bff83e80-2ea9-11eb-97a0-453811a80947.png)

* Helm charts user-supplied values

![image](https://user-images.githubusercontent.com/13386849/100151485-e027fd80-2ea9-11eb-812f-012cc95bd49e.png)

* Kubernetes version information:

![image](https://user-images.githubusercontent.com/13386849/100151573-fe8df900-2ea9-11eb-9479-89736942e7c8.png)

* Kubernetes cluster kind:
On premises (multiple VM nodes) provisioned using kubeadm

**Additional context**

**Comment by jsanda** [comment]
@jeffbanks Can you take a look at this?

**Comment by jeffbanks** [comment]
Yes, researching and reaching out to get more information regarding commands in steps 5 & 6.

**Comment by jeffbanks** [comment]
Hi @tomereli can you provide some more details for us to further investigate?

What commands did you use for the following steps:
- Scale up the cluster to 3 nodes and wait for it to be fully operational
- Scale down the cluster back to 1 node

Also, did you possibly perform two Helm upgrade commands by chance? That could be wiping out the original settings.

**Comment by tomereli** [comment]
> Hi @tomereli can you provide some more details for us to further investigate?
> 
> What commands did you use for the following steps:
> 
> * Scale up the cluster to 3 nodes and wait for it to be fully operational
> * Scale down the cluster back to 1 node
> 
> Also, did you possibly perform two Helm upgrade commands by chance? That could be wiping out the original settings.

I used helm upgrade commands to scale up and down, according to the documentation:
scale up - https://k8ssandra.io/docs/topics/provision-a-cluster/#scale-up-the-cluster
scale down - https://k8ssandra.io/docs/topics/provision-a-cluster/#scale-down-the-cluster

What do you mean that it could be wiping out the original settings?

**Comment by jeffbanks** [comment]
Thanks for providing the details.  I wanted to verify that those steps didn't override something previously set.  I was referring to how multiple helm upgrades or two same key assignments can override the original intention.
`helm upgrade --set foo=bar --set foo=baz k8ssandra ./k8ssandra`

[Helm upgrade reference](https://helm.sh/docs/helm/helm_upgrade/)

Given this detail, I will go through your exact steps and attempt to reproduce this locally.

**Comment by burmanm** [comment]
@tomereli Applying ``--set`` in the command line resets the previous settings to defaults. From helm help:

``-reuse-values                 when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored``

Thus, your previous setting of:

``--set ingress.traefik.enabled=true``

If set to false after you applied the ``--set size=3``. To keep the previous ingress values, you need to apply the ``--reuse-values`` to your later upgrades. So, the size upgrade would be:

``helm upgrade k8ssandra-cluster-a k8ssandra/k8ssandra-cluster --set size=3 --reuse-values``

That is assuming the behavior is the same as before as described better in this article:

https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

**Comment by tomereli** [comment]
> @tomereli Applying `--set` in the command line resets the previous settings to defaults. From helm help:
> 
> `--reuse-values when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored`
> 
> Thus, your previous setting of:
> 
> `--set ingress.traefik.enabled=true`
> 
> If set to false after you applied the `--set size=3`. To keep the previous ingress values, you need to apply the `--reuse-values` to your later upgrades. So, the size upgrade would be:
> 
> `helm upgrade k8ssandra-cluster-a k8ssandra/k8ssandra-cluster --set size=3 --reuse-values`
> 
> That is assuming the behavior is the same as before as described better in this article:
> 
> https://medium.com/@kcatstack/understand-helm-upgrade-flags-reset-values-reuse-values-6e58ac8f127e

Well I guess this is it then - nice catch. I think it would be good to add this to the documentation, cause I guess more users may fall in this pitfall.

**Comment by burmanm** [comment]
@jeffbanks I think you were in process of verifying this? Could you send update to the doc or should I?

**Comment by jeffbanks** [comment]
> @jeffbanks I think you were in process of verifying this? Could you send update to the doc or should I?

@burmanm I will take care of updating the documentation to avoid future confusion.  Thanks for the additional information here to assist @tomereli.
