### ISSUE TITLE
K8SSAND-607 ⁃ Feature to allow adding custom labels to Service Monitor

### ISSUE THREAD

**Issue by ASHISH932** [k8ssandra/k8ssandra#900]
**Is your feature request related to a problem? Please describe.**
ServiceMonitor lables is a good way for prometheus to detect them in a cluster. Current k8ssandra ServiceMonitor configuration would work fine till we are using the Prometheus from k8ssandra chart, as the selector looks for release-name and it would match as they both are same release, but if we want to integrate with an external kube-prometheus-stack with a different release name, we need to add some other labels, than just releaseName.

**Describe the solution you'd like**
Taking extra labels as an input from users through Values would resolve the issue. The kube-prometheus-stack would be finding that label in the complete cluster, and thus would make the integration simple

**Describe alternatives you've considered**
Alternative solution is to change the selector of external prometheus-stack to consider this release also, but it would require to configuration at 2 place, which destroys the purpose of selector to automatically search the cluster.

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-607) by [Unito](https://www.unito.io)
┆Reviewer: Alexander Dejanovski
┆friendlyId: K8SSAND-607
┆priority: Medium

**Comment by jsanda** [comment]
Hi @ASHISH932 

Accepting additional labels definitely sounds like the way to go. Would you be interested in submitting a PR for this?

**Comment by jsanda** [comment]
@adejanovski have you already started working on this issue?

**Comment by adejanovski** [comment]
Nope @jsanda, I'm working on #844 which allows to create the service monitors in a different namespace than the release.

**Comment by bradfordcp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/900?planning-poker) with ZenHub @adejanovski

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra/900?planning-poker) with ZenHub @jeffbanks @Miles-Garnsey @adutra

**Comment by Miles-Garnsey** [comment]
My telemetry implementation in k8ssandra-operator already allows user-defined labels in the [Prometheus spec](https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/telemetry/v1alpha1/telemetry_types.go#L13). 

This ticket appears to relate to the v1 Helm charts, are we still adding new features to these? I'm fuzzy on time estimate as this is not in my wheelhouse, I'd say 3 days to be safe.

**Comment by adejanovski** [comment]
@bradfordcp @jsanda, can we close this ticket since k8ssandra-operator supports this already?

**Comment by jsanda** [comment]
@bradfordcp feel free to reopen if you want to revisit this in 1.x.

For reference, here is the relevant api in k8ssandra-operator - https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/telemetry/v1alpha1/telemetry_types.go#L13.
