### ISSUE TITLE
Restoring a backup in a different dc or release

### ISSUE THREAD

**Issue by ashishFarEye** [k8ssandra/k8ssandra#910]
**Is your feature request related to a problem? Please describe.**
What we want is whenever cassandra is down for some reason and if we could not debug it, we could start a new cluster of k8ssandra and restore the existing backup there. So that our applications don't have to face large downtime.
But in case of K8ssandra backup we could not restore backup of other k8ssandra release into another k8ssandra release. Thus such feature would be helpful in quick recovery from downtime.

**Describe the solution you'd like**
Backups could be restored in any k8ssandra instance irrespective of which k8ssandra release created it

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-618) by [Unito](https://www.unito.io)

**Comment by jdonenine** [comment]
Hi @ashishFarEye thanks for submitting the issue!

This is actually a feature we're working on right now.  You can check out the design documentation [here](https://github.com/k8ssandra/k8ssandra/blob/main/technical-docs/2021-05-remote-restore-redesign.md) we'd love to hear any feedback you've got on it.

We're tracking the overall project to add the remote restore capability across a number of issues you can check out if you're interested [here in Jira](https://k8ssandra.atlassian.net/browse/K8SSAND-515) -- we track the individual issue in GH but the higher-level epics in Jira - both are sync'd and open for anyone to browse and contribute through.

Take a look at what we're working towards in the design document and see if you think that will fit your needs or if there are any other use-cases that we should capture here.

Thanks!
