### ISSUE TITLE
K8SSAND-627 ⁃ Provide image digest as part of image coordinates

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#916]
**Is your feature request related to a problem? Please describe.**
This is related to #420, #839 and #840. 

Image tags are immutable, but they can point to different images over time. For example, suppose`k8ssandra/cass-management-api:4.0.0-v0.1.25` uses Cassandra 4.0-RC1. When RC-2 comes out we may rebuild the image and apply the same tag. The tag however will point to a different image. More specifically the tag points to an image digest.

From a security standpoint it is good to include the digest for verification purposes. To that point, some users/enterprises may require this,

**Describe the solution you'd like**
Include the image digest in the image coordinates for every image that k8ssandra deploys. We should make the digest a configurable property like the image tag.

The example above would be specified as `k8ssandra/cass-management-api:4.0.0-v0.1.25@sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb579860a1dac6c0103`.

**Describe alternatives you've considered**

**Additional context**

┆Issue is synchronized with this [Jira Feature](https://k8ssandra.atlassian.net/browse/K8SSAND-627) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-627
┆priority: Medium

**Comment by bradfordcp** [comment]
Marking this as closed since it has been resolved in #23
