### ISSUE TITLE
K8SSAND-641 ⁃ CRD upgrader job hang forever in cluster without internet.

### ISSUE THREAD

**Issue by kien-truong** [k8ssandra/k8ssandra#925]
## Bug Report

**Describe the bug**
When we perform `helm upgrade` to upgrade configuration on a cluster without internet,  the CRD upgrade job's pod will hang forever and the upgrade will fail.

The workaround for us is to run `helm upgrade --no-hooks` to avoid running the upgrader job.
**To Reproduce**

1. Use a K8S cluster where nodes do not have Internet access.
1. Fetch the helm chart, copy and unpack it to the cluster's controller machine
1. Run `helm install` from the unpacked chart directory to deploy a release.
1. Run `helm upgrade` from the unpacked chart directory to upgrade the release configurations.
1. The upgrade job run forever and `helm upgrade` will time-out.

**Expected behavior**
The upgrade job should be able to run without internet if the helm chart is not updated.

**Environment (please complete the following information):**

* Helm charts version info

`$ helm ls -A` 

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
cassandra       cassandra       14              2021-06-29 10:40:20.411059412 +0700 +07 deployed        k8ssandra-1.2.0
```

* Kubernetes version information:

`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: `Bare-metal deployments`

**Additional context**

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-641) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-641
┆priority: Medium

**Comment by jsanda** [comment]
Hi @kien-truong 

Thanks for creating the issue! 

There are CRD updates in 1.2.0 and to get those updates it does require internet access. `helm upgrade --no-hooks` is not safe workaround. 

Thinking out log... maybe we should update the job so it does not require internet access. It would be great to some community feedback on this.

There may be a work around but it involves some steps.

* Clone the git repo if you have not already done so
* Check out the v1.2.0 tag
* From the project root run `make ORG=<your-docker hub-org> tools-docker-build`
    * This will build a version of the CRD updater image that copies the CRDs into the image. We used this during testing.
* If necessary push the image to registry
    *  `docker push `<your-docker-hub-org> /k8ssandra-tools:v1.2.0 
* Update image coordinates in chart properties (see [here](https://github.com/k8ssandra/k8ssandra/blob/v1.2.0/charts/k8ssandra/values.yaml#L624))
* Retry the helm upgrade
* Report results 😄

**Comment by kien-truong** [comment]
Our CRD is already on 1.2.0 though, so we dont need to upgrade it.

The job is run regardless of the current CRD version.


On 29 Jun 2021 at 11:52, John Sanda ***@***.***> wrote:

Hi @kien-truong <https://github.com/kien-truong>

Thanks for creating the issue!

There are CRD updates in 1.2.0 and to get those updates it does require
internet access. helm upgrade --no-hooks is not safe workaround.

Thinking out log... maybe we should update the job so it does not require
internet access. It would be great to some community feedback on this.

There may be a work around but it involves some steps.

   - Clone the git repo if you have not already done so
   - Check out the v1.2.0 tag
   - From the project root run make ORG=<your-docker hub-org>
   tools-docker-build
      - This will build a version of the CRD updater image that copies the
      CRDs into the image. We used this during testing.
   - If necessary push the image to registry
      - docker push /k8ssandra-tools:v1.2.0
   - Update image coordinates in chart properties (see here
   <https://github.com/k8ssandra/k8ssandra/blob/v1.2.0/charts/k8ssandra/values.yaml#L624>
   )
   - Retry the helm upgrade
   - Report results 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/k8ssandra/k8ssandra/issues/925#issuecomment-870233294>,
or unsubscribe

**Comment by jsanda** [comment]
Try running with the --no-hooks option

**Comment by bradfordcp** [comment]
Did running without --no-hooks work @kien-truong?

**Comment by kien-truong** [comment]
Yes, '--no-hooks' works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
