### ISSUE TITLE
K8SSAND-646 ⁃ Consider shortening or trimming value of app.kubernetes.io/part-of label

### ISSUE THREAD

**Issue by mrjbanksy** [k8ssandra/k8ssandra#929]
## Bug Report

**Describe the bug**
The current value of the `app.kubernetes.io/part-of` label is `k8ssandra-{{ .Release.Name }}-{{ .Release.Namespace }}`, where each of the parts is fine, but if one or more of those parts is longer, could lead to the following error:

```
Error: ServiceAccount "k8ssandra-3aee00f5-cleaner-k8ssandra" is invalid: metadata.labels: Invalid value: "k8ssandra-k8ssandra-3aee00f5-cassandra-application-this-is-a-branch": must be no more than 63 characters
```

**To Reproduce**

1. Pick a release name and namespace combination where the character count sum is more than 52 characters. This may happen due to the combination of needing a unique name per k8ssandra instance and namespace naming scheme - we use `cassandra-<application name>-<branch name>`.
  * Example values:
    * release name: `k8ssandra-3aee00f5`
    * namespace: `cassandra-application-this-is-a-branch`
1. Create the namespace `cassandra-application-this-is-a-branch`
1. Run the helm install command `helm install -f k8ssandra.yaml k8ssandra-3aee00f5 k8ssandra/k8ssandra --namespace cassandra-application-this-is-a-branch`

**Expected behavior**
The k8ssandra instance is created with no errors

**Environment (please complete the following information):**

* Helm charts version info

```
$ helm ls -A
NAME              	NAMESPACE                             	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION        
cert-manager      	cert-manager                          	1       	2021-06-22 19:12:49.900866524 +0000 UTC	deployed	cert-manager-v1.1.0 	v1.1.0             
k8ssandra-3aee00f5	cassandra-application-this-is-a-branch	1       	2021-06-29 15:40:10.036005011 -0400 EDT	failed  	k8ssandra-1.2.0     	                   
reloader          	reloader-operator                     	1       	2021-06-22 15:13:26.439430199 -0400 EDT	deployed	reloader-v0.0.94    	v0.0.94            
spark-operator    	spark-operator                        	1       	2021-06-22 15:19:08.529703936 -0400 EDT	deployed	spark-operator-1.1.3	v1beta2-1.2.3-3.1.1
```

* Helm charts user-supplied values

```
$ helm get values k8ssandra-3aee00f5
USER-SUPPLIED VALUES:
cassandra:
  allowMultipleNodesPerWorker: true
  auth:
    superuser:
      secret: k8ssandra-user
  cassandraLibDirVolume:
    size: 10Gi
    storageClass: managed-premium
  datacenters:
  - name: datacenter1
    racks:
    - name: default
    size: 1
  heap:
    newGenSize: 1G
    size: 1G
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  version: 3.11.10
kube-prometheus-stack:
  enabled: false
stargate:
  enabled: false
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+2817867", GitCommit:"2817867655bb7b68215b4e77873a8facf82bee06", GitTreeState:"clean", BuildDate:"2021-06-02T22:14:22Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

OpenShift 4.7.16

**Additional context**

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-646) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-646
┆priority: Medium

**Comment by jsanda** [comment]
Thanks for creating the ticket. The reason for the naming scheme is to have something that is unique cluster-wide. An identifier can have a max of 63 characters. In your example the branch name is 38 characters. Can you use a shorter branch name?

**Comment by mrjbanksy** [comment]
The branch name is only 16 characters - `this-is-a-branch`. The full namespace is longer, because for similar reasons we want to have something that is unique cluster-wide and human readable - cassandra-<application name>-<branch name>
The three parts:
cassandra: to differentiate it from the application namespace
<application name>: to differentiate it from the other applications in case of the same or similar branch names
<branch name>: to differentiate it from the other branches

If I were to make a suggestion, I would trim the value of the label to 63 characters. It'd still likely result in an unique value cluster-wide, while avoiding this issue when the combination of the release name and namespace is on the longer side.

**Comment by jsanda** [comment]
Trimming to 63 characters is certainly doable. It won't completely prevent collisions but it seems to be a common enough approach.

**Comment by mrjbanksy** [comment]
Depending on how you want to balance collision prevention with human readability, some or all of the label value could be a [sha1sum](https://helm.sh/docs/chart_template_guide/function_list/#sha1sum) or other checksum of the existing value. Perhaps `k8ssandra-{{ .Release.Name }}-{{ .Release.Namespace | sha1sum }}`, all trimmed to 63 characters, or something along those lines.

I'd be happy to submit a PR once the final pattern is picked. I just need to make sure my employer and client are ok with it first.

**Comment by jsanda** [comment]
I might lean towards readability considering the end user will use labels for queries.

**Comment by mrjbanksy** [comment]
Unfortunately, it looks like changing the label value to
```
app.kubernetes.io/part-of: {{ printf "k8ssandra-%s-%s" .Release.Name .Release.Namespace | trunc 63 | trimSuffix "-" }}
```

Is only part of the fix to prevent long names from breaking things. If I create a k8ssandra instance with that fix, and using a long but unique and human readable release name, it fails on the creation of other resources.

```
helm install -f ../osd-infrastructure/k8ssandra/templates/k8ssandra-feature.yml k8ssandra-application-this-is-a-branch ./charts/k8ssandra --namespace cassandra-application-this-is-a-branch
```

```
59s         Warning   ReconcileFailed          cassandradatacenter/datacenter1                                                  Service "k8ssandra-application-this-is-a-branch-datacenter1-all-pods-service" is invalid: metadata.name: Invalid value: "k8ssandra-application-this-is-a-branch-datacenter1-all-pods-service": must be no more than 63 characters
```
With possible others waiting after this specific one is fixed. I don't see the logic for naming the Service or other items in the Helm charts. Is this somewhere in the operator itself?

**Comment by jsanda** [comment]
Is the error from cass-operator? Can you provide more details on it? It isn't clear to me what/where the conflict is.

>I don't see the logic for naming the Service or other items in the Helm charts. Is this somewhere in the operator itself?

Helm creates a number of resources including CassandraDatacenter and Reaper objects. When the CassandraDatacenter is created cass-operator starts creating additional objects including services and StatefulSets.

Similarly when the Reaper object is created reaper-operator starts creating additional objects, namely a service and a Deployment.

The only way to modify the names of those objects that the operators creates is through the name of the CassandraDatacenter and Reaper objects themselves.

**Comment by mrjbanksy** [comment]
The error is generated by the cass-operator. That was the output from `oc get events`, this is what the message looks like in the web console:
```
CD: datacenter1
Namespace: cassandra-application-this-is-a-branch
Jul 19, 2021, 10:27 AM
Generated from cass-operator
19 times in the last 35 minutes
Service "k8ssandra-application-this-is-a-branch-datacenter1-all-pods-service" is invalid: metadata.name: Invalid value: "k8ssandra-application-this-is-a-branch-datacenter1-all-pods-service": must be no more than 63 characters
```

**Comment by jsanda** [comment]
Are attempting to do multiple installs in the same namespace?

**Comment by mrjbanksy** [comment]
Nope, single install per namespace. But just using k8ssandra or something similar as the name for all instances doesn't work, unfortunately, if that's what you're thinking.

```
$ oc new-project k8ssandra1
$ oc new-project k8ssandra2
$ helm install -f k8ssandra.yml k8ssandra ./charts/k8ssandra --namespace k8ssandra1
NAME: k8ssandra
LAST DEPLOYED: Mon Jul 19 10:53:29 2021
NAMESPACE: k8ssandra1
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ helm install -f k8ssandra.yml k8ssandra ./charts/k8ssandra --namespace k8ssandra2
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "k8ssandra-cass-operator-cr" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "k8ssandra2": current value is "k8ssandra1"
```

**Comment by jsanda** [comment]
The error about the ClusterRole is from the cass-operator chart vs the cass-operator controller code which creates the underlying objects of the CassandraDatacenter. 

It should be doc'd somewhere that chart release names need to be unique cluster-wide in order to avoid naming collisions. We could however making the naming of cluster-scoped objects a bit more robust in order to avoid naming collisions. 

wdyt?

**Comment by mrjbanksy** [comment]
The fact that it was using a ClusterRole rather than a Role got me thinking, and I saw that cass-operator can operate at a cluster scope rather than a namespace scope. By installing the cass-operator separately, setting the scope to cluster scope, and then creating k8ssandra instances disabling cass-operator as part of those instances, it looks like all the k8ssandra instances can share a name.

Steps:
1. Add the following lines to k8ssandra.yml:
   ```
   cass-operator:
     enabled: false
   ```
2. Install everything
   ```
   $ oc new-project cass-operator
   $ helm install --set clusterScoped=true cass-operator k8ssandra/cass-operator --namespace cass-operator

   NAME: cass-operator
   LAST DEPLOYED: Tue Jul 20 09:27:31 2021
   NAMESPACE: cass-operator
   STATUS: deployed
   REVISION: 1
   TEST SUITE: None

   $ oc new-project k8ssandra1
   $ helm install -f k8ssandra.yml k8ssandra ./charts/k8ssandra --namespace k8ssandra1

   NAME: k8ssandra
   LAST DEPLOYED: Tue Jul 20 09:28:44 2021
   NAMESPACE: k8ssandra1
   STATUS: deployed
   REVISION: 1
   TEST SUITE: None

   $ helm install -f k8ssandra.yml k8ssandra ./charts/k8ssandra --namespace k8ssandra2

   NAME: k8ssandra
   LAST DEPLOYED: Tue Jul 20 09:30:11 2021
   NAMESPACE: k8ssandra2
   STATUS: deployed
   REVISION: 1
   TEST SUITE: None
   ```

I need to do some more testing but I think with that change in architecture and adding some truncation where necessary, the problem I'm facing right now should be solved.

If I may go off on a tangent, it would be great to see all the operators support running in a cluster scope at some point. One concern I had when looking at k8ssandra was the design of having the operators in each namespace. If you have a design like we do, with a decent number of k8ssandra instances, each in its own namespace, it can make managing that and keeping everything up to date a daunting proposal. If all the operators were running in a single place it would make things easier, and if down the road https://github.com/k8ssandra/k8ssandra/issues/120 was implemented to use OLM so that the operators could upgrade themselves and the datacenters automatically, that would be amazing.

**Comment by jsanda** [comment]
>The fact that it was using a ClusterRole rather than a Role got me thinking, and I saw that cass-operator can operate at a cluster scope rather than a namespace scope.

Note that even when cass-operator is namespace-scoped it still needs a ClusterRole for handling PVs when nodes are decommissioned.

>By installing the cass-operator separately, setting the scope to cluster scope, and then creating k8ssandra instances disabling cass-operator as part of those instances, it looks like all the k8ssandra instances can share a name.

Yup, nicely done! 😃 

>If I may go off on a tangent, it would be great to see all the operators support running in a cluster scope at some point. 

Agreed! This is something we have considered from the outset of the project. Here are some older, related tickets for reference:

* https://github.com/k8ssandra/k8ssandra/issues/335
* https://github.com/k8ssandra/k8ssandra/issues/96

We have started work on an operator for k8ssandra. I am not sure how much progress we will see in the near term to better support cluster scoped deployments 1.x but we will definitely have it in 2.x with the operator based implementation. On a slightly unrelated note, the operator will also introduce some initial multi-cluster support.

**Comment by bradfordcp** [comment]
It looks like the core of this issue is resolved. @jsanda is there any work we want to branch off from this ticket or can it be closed?

**Comment by jsanda** [comment]
It can be closed
