### ISSUE TITLE
Best practices or how-to on migrating data from Cassandra cluster outside of Kubernetes to K8ssandra

### ISSUE THREAD

**Issue by ajvn** [k8ssandra/k8ssandra#934]
**Type of question**

Best practices
How to perform a particular operation
Backup/restore-related question

**What did you do?**
Did some research by going through different issues opened in this repository, also checked your Jira project for existing tickets regarding this topic.

**Did you expect to see something different?**
I expected to find a documentation regarding migration from Cassandra cluster hosted on VMs outside of the Kubernetes.

**Environment**
Kubernetes 1.19.11

* Helm charts version
  * backup v0.26.0
  * cass-operator 0.29.2
  * k8ssandra-common 0.29.2
  * k8ssandra 1.2.0
  * reaper-operator 0.30.0
  * medusa-operator 0.29.0
  * restore 0.27.1

Hello,

Thank you for putting effort in creating all-in-one solution for Cassandra deployment. 

I'd like to know if there is a documented way on how to migrate data from existing non-kubernetes Cassandra cluster hosted on VMs to the K8ssandra deployment. 

I've been going through some tickets here, read documentation that assumes that both deployments are in the same Kubernetes cluster, but it doesn't seem like there's a recommended path on achieving migration when both clusters are not on the Kubernetes. 

I assume solution would involve `additionalSeeds` option, where existing nodes should be added to the K8ssandra and let syncing do it's thing, but I'm wondering if this is agreed best way of achieving this, or if there's some other way.

Thank you.

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-658) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-658
┆Priority: Medium

**Comment by jsanda** [comment]
Hi @ajvn 

This is a great question. It is very timely because @adejanovski is working on a blog post to address this very question. Stay tuned 😄

**Comment by ajvn** [comment]
Hey @jsanda that's very fortunate timing. I'm tuned.

**Comment by jsanda** [comment]
@adejanovski can you update this ticket when you blog post is published? Thanks!

**Comment by ajvn** [comment]
@jsanda @adejanovski Would this be the blog post that addresses this question https://k8ssandra.io/blog/tutorials/cassandra-database-migration-to-kubernetes-zero-downtime/ ?

**Comment by jsanda** [comment]
Yup, that's the post :)

**Comment by ajvn** [comment]
Much obliged, I'll give it a go and post a feedback.

**Comment by ajvn** [comment]
#1066 seems to be fixed, I'll most likely decommission old cluster nodes today, if that goes fine, I'll close this issue as well. Thank you.

**Comment by ajvn** [comment]
Decommissioning went fine, thank you for the guide. I'm closing this issue.

**Comment by shradha-doru** [comment]
Will Camel case cluster name work with K8ssandra Operator?

**Comment by jsanda** [comment]
Hi @shradha-doru 

It won't work at the moment due to https://github.com/k8ssandra/k8ssandra-operator/issues/496. We should have a fix out for that soon.
