### ISSUE TITLE
Medusa backup communications - analysis/design

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#936]
**Is your feature request related to a problem? Please describe.**
Addresses the analysis and design efforts for k8ssand-653.

**Describe the solution you'd like**
Feedback on analysis/design details to resolve medusa-376.

**Describe alternatives you've considered**
Existing service in place w/ augmented capabilities as described in this design PR.

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-660) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-660
┆Priority: Medium

**Comment by jeffbanks** [comment]
# Medusa and Medusa-Operator Communications

## Backup Communications: k8ssand-653

Use cases cover the scope of communications required for Medusa-operator to start, query, and delete a backup being performed by Medusa.  gRPC and inner-process communication is identified where applicable.  All calls are assumed to be synchronous unless noted otherwise.

## Example interactions
<<TODO>>

## Primary use case

1. Medusa-operator submits a synchronous backup request using gRPC Backup(BackupRequest).

```protobuf

message BackupRequest {
  string name = 1;
  enum Mode {
    DIFFERENTIAL = 0;
    FULL = 1;
  }
  Mode mode = 2;
}
```

2. Medusa receives the gRPC BackupRequest, starts the backup process in an asynchronous manner and immediately returns the BackupResponse (w/ an identifier of the job) to the medusa-operator.  The backupId is generated by Medusa and is unique to the backup process underway.

3. Medusa utilizes two primary threads, one as a Backup Monitor and the other as a Backup Status. 
The Backup Monitor thread is responsible for handling BackupRequest messages and for kicking off the chunked file backups (same logic that is in-place within do_backup in the backup_node.py).  In addition, the Backup Monitor thread is responsible for handling DeleteBackupRequest messages and stopping the current set of backups for a specified backupId.  It unregisters (or provides an update) for the backupId “scratch pad” it shares with the Backup Status thread. 

4. The Backup Status thread handles requests for BackupStatusRequest messages in a synchronous manner.  Basically, checking on the latest status for a backupId.

```protobuf
message BackupResponse {
  string backupId = 1;
}
```

5. Medusa-operator receives the BackupResponse and retains the backupId, later used to check the status using the BackupStatusRequest.  Thinking of a control loop or cron-like cycle until it gets confirmation of SUCCESS or FAILED.  A status IN_PROGRESS will identify it needs to status-check at a later time.

```protobuf
message BackupStatusRequest {
 string backupName = 1;
}
```

6. Medusa-operator determines it is time to check the BackupStatus, and synchronously invokes the BackupStatusRequest on Medusa, getting an immediate answer back in the form of BackupStatusResponse.  

A statusMessage is included in the response that can be used for details. Allows for things like determining the need to request the backup again (self-healing) or when IN_PROGRESS, the percentage complete could be communicated.

```protobuf
enum BackupStatusType {
  IN_PROGRESS = 0;
  SUCCESS = 1;
  FAILED = 2;
}
```

```protobuf
message BackupStatusResponse {
  repeated string finishedNodes = 1;
  repeated string unfinishedNodes = 2;
  repeated string missingNodes = 3;
  string startTime = 4;
  string finishTime = 5;

  // proposed new properties
  BackupStatusType status = 6;
  string statusMessage = 7;	      
}
```

Medusa reports back with status=SUCCESS, the Medusa-operator removes its watcher and updates its knowledge of the backup.

### Alternate flows

a. medusa reports back as status=IN_PROGRESS, the Medusa-operator resets a time to check on the backup status for a backupId that is not confirmed.

b. Medusa reports back as status=FAILED, the Medusa-operator removes its watcher and updates its knowledge of the backup.

c. Medusa is not accessible and no status could be received, the Medusa-operator resets a time to check on the backup status for a backupId not confirmed.  This allows time for medusa to be restarting, etc.

d. Medusa -operator determines it has been too long or exhausted attempts to obtain a status for a requested backup.  A DeleteBackupRequest can be issued, which will remove the backup processing for that specific backupID.    
			
#### Example delete request

```protobuf
message DeleteBackupRequest {
 string backupId = 1;
}

message DeleteBackupResponse {
  string backupId = 1;
}
```

**Comment by jsanda** [comment]
@jeffbanks Thanks for the very detailed write up! Some questions/comments...

Why do we need the dedicated monitor and status threads? I understand having a dedicated thread pool to perform the backup operations, but the operations you have described for the monitor and status threads seem like they should be fast, non-blocking operations that only involve in-memory data structures.

I would like to know in more detail about the data structure involved for monitoring the progress of backups. It can be 100% in memory. In Medusa goes down, then any running backups terminate.

I don't think we should be retrying backups. IMO backup operations should be treated as idempotent. If the operation fails, then retrying should result in a new backup operation.

**Comment by adejanovski** [comment]
@jeffbanks, awesome write up 👍 

I agree with John that we could probably simplify the design. The overall orchestration of calls looks good to me, but we can probably avoid using dedicated threads outside of the one performing the backup.
What I had in mind was: 
- The sync backup request will create a thread that will be stored in a dict under an entry that could have the backup name as key.
- Subsequent status check would verify that the thread is still running, and if so assume that the backup is in progress.
- If the thread has completed, the state of the actual backup should be checked for completion/failure. That involves creating the actual node_backup object from the storage backend and checking its state.
- During status check, if the thread has completed, the entry can be removed from the dict. 

wdyt? Do you see any caveats in that simpler approach?

I confirm that we don't restart backups. The operation is not idempotent and any attempt to recreate a backup with the same name would fail.

**Comment by jeffbanks** [comment]
@jsanda @adejanovski 

Right, I see your points here as valid.  The idea was really having two separate threads for separation of concern, while still maintaining 100% in-memory checks w/ retry self-healing aspects.  If we go with a simpler approach without retry requests from the medusa-operator, then the threads can be collapsed IMO.

Do we still think that all 3 status types will be helpful to the caller when checking a status?   Or, should we just have in-progress and successful exposed externally?  The initial approach was tracking a failure state to communicate that something bad happened on the Medusa side instead of relying on a timed-out in-progress status.

I will adjust the design to reflect the simpler approach based on your feedback here.

**Comment by jsanda** [comment]
>Do we still think that all 3 status types will be helpful to the caller when checking a status?

This would be very helpful on the operator side if it is possible.

**Comment by jeffbanks** [comment]
Updated sequence diagram based on feedback.  

The `backup_node` will be coordinating the backup unit of work in an async manner so there is no longer the need to wait on its completion for the Backup gRPC operation.

The `gRPC operations` will be synchronous and short-lived communication.  The status types are introduced to let the client/medusa-operator know the status of the backup for a unique name.  Status types are: SUCCESS, FAILED, or IN_PROGRESS.
