### ISSUE TITLE
Medusa needs to be configured with Cassandra credentials secret

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#94]
## Bug Report

**Describe the bug**
There are some places where Medusa makes CQL calls. I need to review to find out exactly where/when. The short of it is, if Cassandra auth is enabled, I am not sure if backup/restore will work.

**Expected behavior**
Backup/restore workflows should work even when auth is enabled on Cassandra.

**Additional context**
Legacy reference: [Jira K8C-99](https://k8ssandra.atlassian.net/browse/K8C-99)

**Comment by jsanda** [comment]
Replaced by #154
