### ISSUE TITLE
K8SSAND-141 ⁃ Add support for cluster-scoped deployments of reaper-operator

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#96]
**Describe the solution you'd like**
Supporting cluster-scoped deployments of the different components is going to be important for a certain segment of users and enterprises. 

It would be particularly useful for larger enterprises in which SREs basically provide a PaaS for other engineers.

**Additional context**
Legacy Reference: [Jira K8C-79](https://k8ssandra.atlassian.net/browse/K8C-79)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-141) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-141
┆priority: Medium

**Comment by jsanda** [comment]
Closing as won't fix since new feature work is now being done in the k8ssandra-operator repo.
