### ISSUE TITLE
Root file system in Reaper image should be read only

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#964]
**Is your feature request related to a problem? Please describe.**
For improved security the root file system in the Reaper image should be read only. See #292 for background.

**Describe the solution you'd like**
This will involve creating a emptyDir volume mount for `/etc/reaper`. Other changes may be needed as well.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-701) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆Epic: Pod Security Enhancements
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-701
┆Priority: Medium

**Comment by jeffbanks** [comment]
* Tracking this effort as part of `K8SSAND-701` for K8ssandra [security epic](https://k8ssandra.atlassian.net/browse/K8SSAND-705).
* The effort to apply non-root to the Reaper image is tracked under `K8SSAND-700`.
