### ISSUE TITLE
Provide additional documentation related to Prometheus setup/access

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#97]
**Describe the solution you'd like**
For the first iteration, we may want to include things like:

- Provide steps to access the PromUI using kubectl port-forward. 
- Show some examples of querying for some different metrics.
- Show how to view scrape targets in PromUI
- Show how to access Prometheus logs

**Additional context**
Legacy reference:  [Jira K8C-46](https://k8ssandra.atlassian.net/browse/K8C-46)

**Comment by johnwfrancis** [comment]
Okay we've improved the quick start. Any further work required on this?

**Comment by johnsmartco** [comment]
Port-forwarding option covered in:
https://k8ssandra.io/docs/topics/monitoring/#prerequisites - "Tip:..." with links to the following topics:
https://k8ssandra.io/docs/getting-started/developer/#set-up-port-forwarding
https://k8ssandra.io/docs/getting-started/site-engineer/#port-forwarding

We need to provide more info before closing this issue's requests.

**Comment by johnsmartco** [comment]
Done, thanks.
