### ISSUE TITLE
K8SSAND-731 ⁃ Need user authentication for Reaper webui

### ISSUE THREAD

**Issue by zhongshuaiz** [k8ssandra/k8ssandra#987]
**Is your feature request related to a problem? Please describe.**
We want to expose Reaper webui to public, but we can't have user authentication in place.
**Describe the solution you'd like**
We want helm chart give us a section to enable user authentication. For now, it's hard code in the code https://github.com/k8ssandra/reaper-operator/blob/master/pkg/reconcile/reconcilers.go#L446

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-731) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-731
┆priority: Medium

**Comment by jsanda** [comment]
Hi @zhongshuaiz 

I think this will be more involved than just making the `REAPER_AUTH_ENABLED` env var configurable. At a minimum we will need to provide a volume mount for the `shiro.ini` config file. Should k8ssandra and/or reaper-operator provide this, or should the user provide it maybe via a ConfigMap? If it is all driven by the user, then this could be pretty easy.

**Comment by zhongshuaiz** [comment]
Thanks for the reply @jsanda. I think a ConfigMap to update the `shiro.ini` would be good way for us. Do you have a plan to have this feaure in upcoming release?

**Comment by jsanda** [comment]
There are no plans yet to do this in an upcoming release. We hope to release 1.3.0 very soon, depending on when Cassandra 4.0 releases. There are no more changes going into 1.3.0. If you wanted this for 1.4.0, your best bet would be to work on a PR for it.

**Comment by Miles-Garnsey** [comment]
This ticket appears to be a zombie and is raised against k8ssandra 1.0 which is now in maintenance. I am closing to keep the backlog clean. @jsanda tagging you as a courtesy in case you disagree.
